package tag_operations

import (
	tag "github.com/bakeable/bkry/internal/server/models/entities/tag"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
	"github.com/bakeable/bkry/internal/server/database"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func QueryGroup(repository repo.IRepository, queries []database.Query) []tag.Tag {
	// Query Tags group
	entities, err := repository.QueryTagsGroup(queries)
	if err != nil {
		panic(err)
	}

	// Process Tag entities
	entities = afterQueryGroup(entities)

	// Return Tags
	return entities
}