import { type PortalEvent } from './entity'
import { type Store } from 'pinia'


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Represents the state of the portalEvent store.
 */
export interface PortalEventStoreState {
  /**
   * The currently active portalEvent ID
   */
  activeID: string | null

  /**
   * A cache of portalEvents.
   */
  cache: Record<string, {
    ids: string[]
    pagination: Pagination
    retrievalTimestamp: number
  }>

  /**
   * The list of portalEvents.
   */
  list: PortalEvent[]

  /**
   * The retrieval timestamp
   */
  retrievalTimestamp: number

  /**
   * A key that is updated to force the update of the entity.
   */
  updateKey: number

  /**
   * A timeout before emitting a store update event.
   */
  storeUpdateTimeout: window.Timeout | null
}

/**
 * Represents an PortalEventStore that extends the Store interface.
 */
export interface PortalEventStore extends PortalEventStoreState, Store {
  /**
   * Fire a form update event for the PortalEvent.
   */
  emitFormUpdateEvent: (id: string) => void

  /**
   * Fire a store update event for all PortalEvent.
   */
  emitStoreUpdateEvent: () => void

  /**
   * The currently active portalEvent
   */
  active: PortalEvent

  /**
   * Adds an portalEvent to the local PortalEventStore.
   * @param portalEvent The portalEvent to be added.
   */
  add: (portalEvent: PortalEvent) => void

  /**
   * Checks whether the list contains an instance with the provided ID.
   * @param id The id to be searched.
   * @returns {boolean} A boolean indicating whether the list contains the ID.
   */
  contains: (id: string) => boolean

  /**
   * Deletes an portalEvent from the PortalEventStore from the external database.
   * @param portalEvent The portalEvent to be deleted.
   * @returns {Promise<void>} A promise that resolves when the portalEvent is deleted.
   */
  delete: (portalEvent: PortalEvent) => Promise<void>

  /**
   * Deletes an portalEvent by ID from the PortalEventStore from the external database.
   * @param id The ID to be deleted.
   * @returns {Promise<void>} A promise that resolves when the portalEvent is deleted.
   */
  deleteById: (id: string) => Promise<void>

  /**
   * Get a PortalEvent from the local PortalEventStore.
   * @returns { PortalEvent | null } The portalEvent.
   */
  get: (id: string) => PortalEvent | null

  /**
   * Reinserts an portalEvent to the PortalEventStore list.
   * @param portalEvent The portalEvent to be reinserted.
   * @returns {void}
   */
  reinsert: (portalEvent: PortalEvent) => void

  /**
   * Removes an portalEvent from the local PortalEventStore.
   * @param portalEvent The portalEvent to be removed.
   * @returns {void}
   */
  remove: (portalEvent: PortalEvent) => void

  /**
   * Determines whether a refresh of the store is required
   */
  refreshRequired: boolean

  /**
   * Retrieves a single PortalEvent from either the local PortalEventStore or external source, if forced or required.
    * @param id The ID of the PortalEvent to retrieve.
    * @param force Indicates whether a refresh is forced.
   * @returns {Promise<void>} A promise that resolves when the portalEvent is set as active.
   */
  retrieve: (id: string, force?: boolean) => Promise<PortalEvent>

  /**
   * Retrieves all portalEvents from the PortalEventStore or external source, depending if a refresh is required.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<void>} A promise that resolves with an array of portalEvents.
   */
  retrieveAll: (force?: boolean) => Promise<{
    active: string | null
    items: PortalEvent[]
  }>

  /**
    * Retrieves portalEvents paginated from the external source
    * @param pagination The pagination to be used for the query.
    * @param force Whether to force the query to the external source.
    * @returns {Promise<void>} A promise that resolves with an array of portalEvents.
    */
  retrievePaginated: (pagination?: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: PortalEvent[]
  }>

  /**
    * Queries portalEvents from the external source
    * @param queries The queries to be used for filtering.
    * @param pagination The pagination to be used for the query.
    * @param force Whether to force the query to the external source.
    * @returns {Promise<void>} A promise that resolves with an array of portalEvents.
    */
  query: (queries: Query[], pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: PortalEvent[]
  }>

  /**
   * Update an portalEvent from the PortalEventStore in the external database.
   * @param portalEvent The portalEvent to be updated.
   * @param connect Indicates whether the portalEvent should be connected to the user on update.
   * @returns {Promise<string>} A promise that resolves to the ID as a string when the portalEvent is updated.
   */
  update: (portalEvent: PortalEvent) => Promise<string>

  /**
    * Searches for portalEvents in the external source.
    * @param query The query to be used for searching.
    * @returns {Promise<void>} A promise that resolves with an array of portalEvents.
    */
  search: (query: string, pagination: Pagination, force?: boolean) => Promise<PortalEvent[]>
}
