package packing_slip_package_operations

import (
	packing_slip_package "github.com/bakeable/bkry/data/entities/packing_slip_package"
	repo "github.com/bakeable/bkry/data/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Save(repository repo.IRepository, entity packing_slip_package.PackingSlipPackage, editorID *string) *string {
	// Preprocess PackingSlipPackage
	entity = beforeSave(entity, editorID)

	// Save PackingSlipPackage
	id, err := repository.SavePackingSlipPackage(entity, editorID)
	if err != nil {
		panic(err)
	}

	// Set ID on entity
	entity.ID = id

	// Take care of business logic after saving PackingSlipPackage entity
	afterSave(entity, editorID)

	// Return PackingSlipPackage
	return &id
}