package product_package_localisation_operations

import (
	product_package_localisation "github.com/bakeable/bkry/internal/server/models/entities/product_package_localisation"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Get(repository repo.IRepository, productPackageID string, productPackageLocalisationID string) product_package_localisation.ProductPackageLocalisation {
	// Get ProductPackageLocalisation
	entity, err := repository.GetProductPackageLocalisation(productPackageID, productPackageLocalisationID)
	if err != nil {
		panic(err)
	}

	// Process ProductPackageLocalisation entity
	entity = afterGet(productPackageID, productPackageLocalisationID, entity)

	// Return ProductPackageLocalisation
	return entity
}