package product_package_localisation_operations

import (
	product_package_localisation "github.com/bakeable/bkry/internal/server/models/entities/product_package_localisation"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAll(repository repo.IRepository, productPackageID string) []product_package_localisation.ProductPackageLocalisation {
	// Get ProductPackageLocalisations
	entities, err := repository.GetAllProductPackageLocalisations(productPackageID)
	if err != nil {
		panic(err)
	}

	// Process ProductPackageLocalisation entities
	entities = afterGetAll(productPackageID, entities)

	// Return ProductPackageLocalisations
	return entities
}