package printing_order_supplier_controllers

import (
	"net/http"
	printing_order_supplier_operations "github.com/bakeable/bkry/internal/server/transport/operations/printing_order_supplier"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func Delete(c *gin.Context) {

	// Get printing_order_supplier ID from URL
	printingOrderSupplierID := c.Param("printingOrderSupplierID")

	// Delete PrintingOrderSupplier
	printing_order_supplier_operations.Delete(getRepository(), printingOrderSupplierID)

	// Send response
	c.Status(http.StatusNoContent)

}

