package printing_order_supplier_controllers

import (
	"net/http"
	printing_order_supplier "github.com/bakeable/bkry/data/entities/printing_order_supplier"
	printing_order_supplier_operations "github.com/bakeable/bkry/data/entities/printing_order_supplier/operations"
	"github.com/bakeable/bkry/tools"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func Update(c *gin.Context) {


	// Get PrintingOrderSupplier mapping from request body
	var mapping map[string]interface{}
	if err := c.ShouldBindJSON(&mapping); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// Decode JSON to PrintingOrderSupplier
	entity := printing_order_supplier.Decode(mapping)

	// Add PrintingOrderSupplier to event
	printing_order_supplier_operations.Save(getRepository(), entity, utils.GetEditorId(c))

	// Return successfull
	c.Status(http.StatusNoContent)
}