import { type JSONData } from '../../base_classes/dto.d'
import type IDto from '../../base_classes/dto.d'
import { type Dimension } from '../../general/dimension'

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////


// Types
export type CarrierCode = "BRTB" | "BRT" | "AFH" | "OEG"
export type PackingSlipStatus = "shipment_not_created" | "shipment_created" | "shipment_ready"

// Interfaces
export interface IAddress {
    // City of the address
      city: string
    // Country of the address
      country: string
    // Description of the address
      description: string
    // Formatted address string
      formatted: string
    // House number of the address
      houseNumber: string
    // Postal code of the address
      postalCode: string
    // Street of the address
      street: string
}
export interface ICustomer {
    // Email of the customer
      email: string
    // Name of the customer
      name: string
    // Phone number of the customer
      phoneNumber: string
}
export interface IDelivery {
    // Time after which the delivery is expected
    afterTime: {
    // Hour of the delivery time
      hour: number
    // Minute of the delivery time
      minute: number
    }
    // Time before which the delivery is expected
    beforeTime: {
    // Hour of the delivery time
      hour: number
    // Minute of the delivery time
      minute: number
    }
    // Date of the delivery
      date: string
    // Notes about the delivery
      notes: string
}
export interface IPackages {
    // Number of packages
      amount: number
    // Dimensions of the package
    dimensions: {
    // Height of the package
      height: Dimension
    // Length of the package
      length: Dimension
    // Width of the package
      width: Dimension
    }
    // Transsmart code for the package
      transsmartCode: string
    // Type of the package
      type: string
    // Weight of the package
      weight: Dimension
}

// Data Transfer Object Interface
export interface IPackingSlipDto extends IDto {
  /// ///////////////////////////////////////
  /// //////// PRIVATE VARIABLES ////////////
  /// ///////////////////////////////////////
  /**
   * The path to the corresponding API endpoint with variables marked as {?}
   */
  _path: string

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////

    // Name of the person who added this packing slip
    addedBy: string

    // Recipient's address
    address: IAddress

    // The administration related to this packing slip
    administration: string

    // Airway bill number
    awb: string

    // Carrier code for the shipment
    carrierCode: CarrierCode

    // List of combined order numbers
    combinedOrderNumbers: string[]

    // List of combined packing slip IDs
    combinedPackingSlipIds: string[]

    // Name of the company
    companyName: string

    // Customer details
    customer: ICustomer

    // Date of the packing slip
    date: string

    // Delivery details
    delivery: IDelivery

    // Description of the packing slip
    description: string

    // Incoterm code for the shipment
    incotermCode: string

    // Type of the packing slip
    _kind: string

    // ID of the main packing slip
    mainPackingSlipId: string

    // Flag indicating if the packing slip is marked as completed
    markedAsCompleted: boolean

    // Flag indicating if the packing slip is marked as printed
    markedAsPrinted: boolean

    // Flag indicating if the packing slip is marked as pushed
    markedAsPushed: boolean

    // Additional note for the packing slip
    note: string

    // Name of the person who created the order
    orderCreatedBy: string

    // Order number associated with the packing slip
    orderNumber: string

    // Order processing details
    orderProcessing: string

    // Original total gross weight of the shipment
    originalTotalGrossWeight: number

    // List of packages in the shipment
    packages: IPackages[]

    // Promised delivery date
    promisedDeliveryDate: string

    // Reference for the packing slip
    reference: string

    // Service details
    service: string

    // Packing slip number
    slipNumber: string

    // Status of the packing slip
    status: PackingSlipStatus

    // The ordering index of the status
    statusIndex: number

    // Name of the supplier contact
    supplierContactName: string

    // ID of the supplier
    supplierId: string

    // Name of the supplier
    supplierName: string

    // Total amount excluding VAT
    totalAmountExcludingVAT: number

    // Total gross weight
    totalGrossWeight: number

    // Total quantity
    totalQuantity: number

    // Tracking URL
    trackingUrl: string

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////

  /**
   * Set the PackingSlip's properties
   */
  set: (data: JSONData) => void
}
