package portal_event_operations

import (
	repo "github.com/bakeable/bkry/data/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Delete(repository repo.IRepository, portalEventID string) {
	// Perform before delete actions for PortalEvent entity
	beforeDelete(portalEventID)

	// Delete PortalEvent
	err := repository.DeletePortalEvent(portalEventID)
	if err != nil {
		panic(err)
	}

	// Perform after delete actions for PortalEvent entity
	afterDelete(portalEventID)
}