package user_operations

import (
	user "github.com/bakeable/bkry/data/entities/user"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Query(repository repo.IRepository, queries []datastore.Query, pagination datastore.Pagination) []user.User {
	// Get Users
	entities, err := repository.QueryUsers(queries, pagination)
	if err != nil {
		panic(err)
	}

	// Process User entities
	entities = afterQuery(entities)

	// Return Users
	return entities
}