import { defineStore } from 'pinia'
import { PrintingOrderItem } from './entity'
import { PrintingOrderItemList } from './list.gen'
import type { PrintingOrderItemStore, PrintingOrderItemStoreState } from './store.gen.d'
import { analytics, auth } from '@/firebase'
import { type JSONData } from '../../base_classes/dto.d'
import { Pagination } from "../../base_classes/pagination";
import { Query } from "../../base_classes/query";
import { paginationAndQueriesToCacheKey } from "../../base_classes/dto_list";


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

const printingOrderItemList = new PrintingOrderItemList()
export const usePrintingOrderItemStore = defineStore('printingOrderItemStore', {
  state: (): PrintingOrderItemStoreState => ({
    activeID: null,
    cache: {},
    list: [] as PrintingOrderItem[],
    retrievalTimestamp: 0,
    updateKey: 0,
    storeUpdateTimeout: null,
  }),
  actions: {
    initializeStore(): void {
      this.convertList()
    },
    emitFormUpdateEvent(id: string): void {
      window.dispatchEvent(new CustomEvent("form-update-PrintingOrderItem", { detail: { id } }));
    },
    emitStoreUpdateEvent(): void {
      // Clear existing timeout
      if (this.storeUpdateTimeout !== null) {
        clearTimeout(this.storeUpdateTimeout)
      }

      // Set new timeout
      this.storeUpdateTimeout = setTimeout(() => {
        window.dispatchEvent(new CustomEvent("store.update.PrintingOrderItem"));
        this.storeUpdateTimeout = null
      }, 1500)
    },
    async activate(printingOrderItem: PrintingOrderItem): Promise<void> {
      // Set active
      await printingOrderItem
        .activate(auth.firebaseUser?.uid)
        .then(() => {
          this.activeID = printingOrderItem.id
        })
        .catch((error) => {
          console.error(error)
          this.activeID = null
        })
    },
    add(printingOrderItem: PrintingOrderItem): void {
      const id = printingOrderItem.id
      if (typeof id === 'string' && !this.contains(id)) {
        this.list.push(printingOrderItem)

        // Set active
        if (this.active === null) {
          this.activeID = printingOrderItem.id
        }
      } else {
        this.reinsert(printingOrderItem)
      }
      this.updateKey += 1;
    },
    convertList(): void {
      this.list = (this.list as PrintingOrderItem[]).map((x: any) => {
        const printingOrderItem = new PrintingOrderItem({})
        printingOrderItem.set(x as JSONData)
        return printingOrderItem
      })
    },
    async delete(printingOrderItem: PrintingOrderItem): Promise<void> {
      await printingOrderItem.delete().then(() => {
        this.remove(printingOrderItem)
      }).finally(() => {
        this.emitStoreUpdateEvent()
      });
    },
    async deleteById(id: string): Promise<void> {
      const printingOrderItem = (this.list as PrintingOrderItem[]).find((x: PrintingOrderItem) => x.id === id)
      if (printingOrderItem !== undefined) {
        await this.delete(printingOrderItem)
      } else {
        throw new Error('Could not find PrintingOrderItem with id: ' + id)
      }
    },
    contains(id: string): boolean {
      return (this.list as PrintingOrderItem[]).some((x: PrintingOrderItem) => x.id === id)
    },
    get(id: string): PrintingOrderItem | null {
      return (this.list as PrintingOrderItem[]).find((x: PrintingOrderItem) => x.id === id) || null
    },
    reinsert(printingOrderItem: PrintingOrderItem): void {
      const index = (this.list as PrintingOrderItem[]).findIndex((x: PrintingOrderItem) => x.id === printingOrderItem.id)
      if (index !== -1) {
        this.list = [
          ...this.list.slice(0, index),
          printingOrderItem,
          ...this.list.slice(index + 1),
        ]
      } else {
        this.add(printingOrderItem)
      }
      this.updateKey += 1;
    },
    remove({ id }: PrintingOrderItem): void {
      const index = (this.list as PrintingOrderItem[]).findIndex((x: PrintingOrderItem) => x.id === id)
      if (index !== -1) {
        this.list = [
          ...this.list.slice(0, index),
          ...this.list.slice(index + 1),
        ]
      }
      this.updateKey += 1;
    },
    async retrieve(id: string, force = false): Promise<PrintingOrderItem> {
      // Check if a refresh is required
      if (!force && !this.refreshRequired) {
        const printingOrderItem = this.get(id)
        if (printingOrderItem !== null) {
          return printingOrderItem
        }
      }

      // Retrieve printingOrderItem
      const printingOrderItem = new PrintingOrderItem({})

      // Get printingOrderItem
      await printingOrderItem.get([id]).then(async (entity) => {
        this.reinsert(entity)

        // Activate printingOrderItem
        await this.activate(entity)
      })

      return printingOrderItem
    },
    async retrieveAll(force = false): Promise<{
      active: string | null
      items: PrintingOrderItem[]
    }> {
      // Check if a refresh is required
      if (!force && !this.refreshRequired) {
        return {
          active: this.activeID,
          items: this.list as PrintingOrderItem[],
        }
      }

      // Clear list
      while (this.list.length > 0) {
        this.list.pop()
      }

      // Retrieve list
      await printingOrderItemList.getAll().then(async (list) => {
        list.forEach((printingOrderItem) => {
          this.reinsert(printingOrderItem)
        })

        // Activate printingOrderItem
        if (list.length > 0) {
          if (printingOrderItemList.active !== null) {
            this.activeID = printingOrderItemList.active
          } else {
            await this.activate(list[0])
          }
        }
      })

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now()

      // Set user property
      if (this.activeID !== null) {
        analytics.setUserProperty('printing_order_item_id', this.activeID)
      }

      return {
        active: this.activeID,
        items: this.list as PrintingOrderItem[],
      }
    },
    async retrievePaginated(pagination: Pagination, force = false): Promise<{
      pagination: Pagination;
      items: PrintingOrderItem[];
    }> {
      // Check pagination
      let newPagination = new Pagination(pagination).deepCopy();

      // Get cachekey
      const cacheKey = pagination.toCacheKey();

      // Check if a refresh is required
      if (!force && this.cache[cacheKey]) {
        const cached = this.cache[cacheKey]
        return {
          pagination: cached.pagination.deepCopy(),
          items: cached.ids.map((id: string) => this.get(id) as PrintingOrderItem),
        };
      }

      // Retrieve list
      const items = await printingOrderItemList.getPaginated(
        [],
        pagination
      ).then(async ({items, pagination }) => {
        items.forEach((printingOrderItem) => {
          this.reinsert(printingOrderItem);
        });

        // Set new pagination
        newPagination = pagination.deepCopy();

        return items;
      });

      // Set cache
      this.cache[cacheKey] = {
        ids: items.map((x: PrintingOrderItem) => x.id),
        pagination: newPagination,
        retrievalTimestamp: Date.now(),
      };

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now();

      return {
        pagination: newPagination,
        items,
      };
    },
    async query(queries: Query[], pagination: Pagination, force = false): Promise<{
      pagination: Pagination;
      items: PrintingOrderItem[];
    }> {
      // Check pagination
      let newPagination = new Pagination(pagination).deepCopy();

      // Get cachekey
      const cacheKey = paginationAndQueriesToCacheKey(pagination, queries);

      // Check if a refresh is required
      if (!force && this.cache[cacheKey]) {
        const cached = this.cache[cacheKey]
        return {
          pagination: cached.pagination.deepCopy(),
          items: cached.ids.map((id: string) => this.get(id) as PrintingOrderItem),
        };
      }

      // Retrieve list
      const items = await printingOrderItemList.query(
        queries,
        pagination,
      ).then(async ({ items, pagination }) => {
        items.forEach((printingOrderItem) => {
          this.reinsert(printingOrderItem);
        });

        // Set new pagination
        newPagination = pagination.deepCopy();;

        return items
      });

      // Set cache
      this.cache[cacheKey] = {
        ids: items.map((x: PrintingOrderItem) => x.id),
        pagination: newPagination.deepCopy(),
        retrievalTimestamp: Date.now(),
      };

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now();

      return {
        pagination: newPagination,
        items: items,
      };
    },
    async search(
      
      query: string,
      pagination: Pagination,
      force = false,
    ): Promise<{
      pagination: Pagination;
      items: PrintingOrderItem[];
    }> {
      // Check pagination
      let newPagination = new Pagination(pagination).deepCopy();

      // Get cachekey
      const cacheKey = query.replaceAll(" ", "_") + '-' + pagination.toCacheKey();

      // Check if a refresh is required
      if (!force && this.cache[cacheKey]) {
        const cached = this.cache[cacheKey]
        return {
          items: cached.ids.map(
            (id: string) => this.get(id) as PrintingOrderItem,
          ),
          pagination: cached.pagination.deepCopy(),
        };
      }

      // Retrieve list
      const items = await printingOrderItemList
        .search(query, pagination)
        .then(async ({ items, pagination }) => {
          items.forEach((printingOrderItem) => {
            this.reinsert(printingOrderItem);
          });

          // Set new pagination
          newPagination = pagination.deepCopy();

          return items;
        });

      // Set cache
      this.cache[cacheKey] = {
        ids: items.map((x: PrintingOrderItem) => x.id),
        pagination: newPagination.deepCopy(),
        retrievalTimestamp: Date.now(),
      };

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now();

      return {
        items: items,
        pagination: newPagination,
      };
    },
    async update(printingOrderItem: PrintingOrderItem): Promise<string> {
      // Update printingOrderItem
      await printingOrderItem.update()

      // Reinsert printingOrderItem
      this.reinsert(printingOrderItem)

      // Activate printingOrderItem
      if (this.active === null) {
        await this.activate(printingOrderItem)
      }
      
      this.emitStoreUpdateEvent()

      return printingOrderItem.id
    },
  },
  getters: {
    active(): PrintingOrderItem | null {
      if (this.activeID === null) {
        return null
      }

      const printingOrderItem = (this.list as PrintingOrderItem[]).find((x: PrintingOrderItem) => x.id === this.activeID)
      if (printingOrderItem === undefined) {
        return null
      }

      return printingOrderItem
    },
    refreshRequired(): boolean {
      return (
        this.retrievalTimestamp === 0 ||
        this.retrievalTimestamp < Date.now() - 30 * 60000 ||
        this.list.length === 0
      )
    },
  },
})

// Export a function to create a new instance of the store
export function createPrintingOrderItemStore(): PrintingOrderItemStore {
  const store = usePrintingOrderItemStore()
  // Run the initializeStore action when the store is created
  store.initializeStore()
  return store as unknown as PrintingOrderItemStore // TODO: Fix this
}
