package attribute_operations

import (
	repo "github.com/bakeable/bkry/data/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Delete(repository repo.IRepository, attributeID string) {
	// Perform before delete actions for Attribute entity
	beforeDelete(attributeID)

	// Delete Attribute
	err := repository.DeleteAttribute(attributeID)
	if err != nil {
		panic(err)
	}

	// Perform after delete actions for Attribute entity
	afterDelete(attributeID)
}