import { type CloudFunction } from './entity'
import { type Store } from 'pinia'


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Represents the state of the cloudFunction store.
 */
export interface CloudFunctionStoreState {
  /**
   * The currently active cloudFunction ID
   */
  activeID: string | null

  /**
   * A cache of cloudFunctions.
   */
  cache: Record<string, {
    ids: string[]
    pagination: Pagination
    retrievalTimestamp: number
  }>

  /**
   * The list of cloudFunctions.
   */
  list: CloudFunction[]

  /**
   * The retrieval timestamp
   */
  retrievalTimestamp: number

  /**
   * A key that is updated to force the update of the entity.
   */
  updateKey: number

  /**
   * A timeout before emitting a store update event.
   */
  storeUpdateTimeout: window.Timeout | null
}

/**
 * Represents an CloudFunctionStore that extends the Store interface.
 */
export interface CloudFunctionStore extends CloudFunctionStoreState, Store {
  /**
   * Fire a form update event for the CloudFunction.
   */
  emitFormUpdateEvent: (id: string) => void

  /**
   * Fire a store update event for all CloudFunction.
   */
  emitStoreUpdateEvent: () => void

  /**
   * The currently active cloudFunction
   */
  active: CloudFunction

  /**
   * Adds an cloudFunction to the local CloudFunctionStore.
   * @param cloudFunction The cloudFunction to be added.
   */
  add: (cloudFunction: CloudFunction) => void

  /**
   * Checks whether the list contains an instance with the provided ID.
   * @param id The id to be searched.
   * @returns {boolean} A boolean indicating whether the list contains the ID.
   */
  contains: (id: string) => boolean

  /**
   * Deletes an cloudFunction from the CloudFunctionStore from the external database.
   * @param cloudFunction The cloudFunction to be deleted.
   * @returns {Promise<void>} A promise that resolves when the cloudFunction is deleted.
   */
  delete: (cloudFunction: CloudFunction) => Promise<void>

  /**
   * Deletes an cloudFunction by ID from the CloudFunctionStore from the external database.
   * @param id The ID to be deleted.
   * @returns {Promise<void>} A promise that resolves when the cloudFunction is deleted.
   */
  deleteById: (id: string) => Promise<void>

  /**
   * Get a CloudFunction from the local CloudFunctionStore.
   * @returns { CloudFunction | null } The cloudFunction.
   */
  get: (id: string) => CloudFunction | null

  /**
   * Reinserts an cloudFunction to the CloudFunctionStore list.
   * @param cloudFunction The cloudFunction to be reinserted.
   * @returns {void}
   */
  reinsert: (cloudFunction: CloudFunction) => void

  /**
   * Removes an cloudFunction from the local CloudFunctionStore.
   * @param cloudFunction The cloudFunction to be removed.
   * @returns {void}
   */
  remove: (cloudFunction: CloudFunction) => void

  /**
   * Determines whether a refresh of the store is required
   */
  refreshRequired: boolean

  /**
   * Retrieves a single CloudFunction from either the local CloudFunctionStore or external source, if forced or required.
    * @param id The ID of the CloudFunction to retrieve.
    * @param force Indicates whether a refresh is forced.
   * @returns {Promise<void>} A promise that resolves when the cloudFunction is set as active.
   */
  retrieve: (id: string, force?: boolean) => Promise<CloudFunction>

  /**
   * Retrieves all cloudFunctions from the CloudFunctionStore or external source, depending if a refresh is required.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<void>} A promise that resolves with an array of cloudFunctions.
   */
  retrieveAll: (force?: boolean) => Promise<{
    active: string | null
    items: CloudFunction[]
  }>

  /**
    * Retrieves cloudFunctions paginated from the external source
    * @param pagination The pagination to be used for the query.
    * @param force Whether to force the query to the external source.
    * @returns {Promise<void>} A promise that resolves with an array of cloudFunctions.
    */
  retrievePaginated: (pagination?: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: CloudFunction[]
  }>

  /**
    * Queries cloudFunctions from the external source
    * @param queries The queries to be used for filtering.
    * @param pagination The pagination to be used for the query.
    * @param force Whether to force the query to the external source.
    * @returns {Promise<void>} A promise that resolves with an array of cloudFunctions.
    */
  query: (queries: Query[], pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: CloudFunction[]
  }>

  /**
   * Update an cloudFunction from the CloudFunctionStore in the external database.
   * @param cloudFunction The cloudFunction to be updated.
   * @param connect Indicates whether the cloudFunction should be connected to the user on update.
   * @returns {Promise<string>} A promise that resolves to the ID as a string when the cloudFunction is updated.
   */
  update: (cloudFunction: CloudFunction) => Promise<string>

  /**
    * Searches for cloudFunctions in the external source.
    * @param query The query to be used for searching.
    * @returns {Promise<void>} A promise that resolves with an array of cloudFunctions.
    */
  search: (query: string, pagination: Pagination, force?: boolean) => Promise<CloudFunction[]>
}
