import { PackingSlip } from './entity'
import DtoList from '../../base_classes/dto_list'
import { type JSONData } from '../../base_classes/dto.d'
import { type IPackingSlipList } from './list.gen.d'
import { Pagination } from "../../base_classes/pagination";
import { Query } from "../../base_classes/query";


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////


export class PackingSlipList 
extends DtoList 
implements IPackingSlipList 
{
  /// ///////////////////////////////////////
  /// //////// PRIVATE VARIABLES ////////////
  /// ///////////////////////////////////////
  _path = '/packing_slip'

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////
  list: PackingSlip[] = []
  queriedList: PackingSlip[] = []

  /// ///////////////////////////////////////
  /// ////////////// METHODS ////////////////
  /// ///////////////////////////////////////

  _buildInstance(data: JSONData): PackingSlip {
    return new PackingSlip([], data)
  }

  override async getAll(
    pathVars?: string | string[] | Record<string, string>
  ): Promise<PackingSlip[]> {
    return (await super.getAll(pathVars)) as PackingSlip[]
  }

  override async getPaginated(
    pathVars: string | string[],
    pagination: Pagination
  ): Promise<{
    items: PackingSlip[],
    pagination: Pagination,
  }> {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    return (await super.getPaginated(pathVars, pagination)) as {
      items: PackingSlip[],
      pagination: Pagination,
    }
  }

  override async query(queries: Query[], pagination?: Pagination): Promise<{
    items: PackingSlip[],
    pagination: Pagination,
  }> {
    return (await super.query(queries, pagination)) as {
      items: PackingSlip[],
      pagination: Pagination,
    }
  }

  override async search(query: string, pagination?: Pagination): Promise<{
    items: PackingSlip[],
    pagination: Pagination,
  }> {
    return (await super.search(query, pagination)) as {
      items: PackingSlip[],
      pagination: Pagination,
    }
  }
}
