package printing_order_item_operations

import (
	repo "github.com/bakeable/bkry/internal/server/database/repository"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Delete(repository repo.IRepository, printingOrderItemID string) {
	// Perform before delete actions for PrintingOrderItem entity
	beforeDelete(printingOrderItemID)

	// Delete PrintingOrderItem
	err := repository.DeletePrintingOrderItem(printingOrderItemID)
	if err != nil {
		panic(err)
	}

	// Perform after delete actions for PrintingOrderItem entity
	afterDelete(printingOrderItemID)
}