package printing_order_item_operations

import (
	printing_order_item "github.com/bakeable/bkry/internal/server/models/entities/printing_order_item"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAll(repository repo.IRepository, ) []printing_order_item.PrintingOrderItem {
	// Get PrintingOrderItems
	entities, err := repository.GetAllPrintingOrderItems()
	if err != nil {
		panic(err)
	}

	// Process PrintingOrderItem entities
	entities = afterGetAll(entities)

	// Return PrintingOrderItems
	return entities
}