package airline_order_operations

import (
	airline_order "github.com/bakeable/bkry/data/entities/airline_order"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAllPaginated(repository repo.IRepository, pagination datastore.Pagination) ([]airline_order.AirlineOrder, datastore.Pagination) {
	// Get AirlineOrders
	entities, pagination, err := repository.GetAllAirlineOrdersPaginated(pagination)
	if err != nil {
		panic(err)
	}

	// Process AirlineOrder entities
	entities = afterGetAllPaginated(entities, pagination.PageSize, pagination.PageNumber, pagination.OrderBy, pagination.Ascending)

	// Return AirlineOrders
	return entities, pagination
}