package price_configuration_operations

import (
	price_configuration "github.com/bakeable/bkry/internal/server/models/entities/price_configuration"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAll(repository repo.IRepository, ) []price_configuration.PriceConfiguration {
	// Get PriceConfigurations
	entities, err := repository.GetAllPriceConfigurations()
	if err != nil {
		panic(err)
	}

	// Process PriceConfiguration entities
	entities = afterGetAll(entities)

	// Return PriceConfigurations
	return entities
}