package category_localisation_operations

import (
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Delete(repository repo.IRepository, categoryID string, categoryLocalisationID string) {
	// Perform before delete actions for CategoryLocalisation entity
	beforeDelete(categoryID, categoryLocalisationID)

	// Delete CategoryLocalisation
	err := repository.DeleteCategoryLocalisation(categoryID, categoryLocalisationID)
	if err != nil {
		panic(err)
	}

	// Perform after delete actions for CategoryLocalisation entity
	afterDelete(categoryID, categoryLocalisationID)
}