package category_localisation_operations

import (
	category_localisation "github.com/bakeable/bkry/internal/server/models/entities/category_localisation"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Get(repository repo.IRepository, categoryID string, categoryLocalisationID string) category_localisation.CategoryLocalisation {
	// Get CategoryLocalisation
	entity, err := repository.GetCategoryLocalisation(categoryID, categoryLocalisationID)
	if err != nil {
		panic(err)
	}

	// Process CategoryLocalisation entity
	entity = afterGet(categoryID, categoryLocalisationID, entity)

	// Return CategoryLocalisation
	return entity
}