package category_localisation_operations

import (
	category_localisation "github.com/bakeable/bkry/internal/server/models/entities/category_localisation"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Save(repository repo.IRepository, categoryID string, entity category_localisation.CategoryLocalisation, editorID *string) *string {
	// Preprocess CategoryLocalisation
	entity = beforeSave(categoryID, entity, editorID)

	// Save CategoryLocalisation
	id, err := repository.SaveCategoryLocalisation(categoryID, entity, editorID)
	if err != nil {
		panic(err)
	}

	// Set ID on entity
	entity.ID = id

	// Take care of business logic after saving CategoryLocalisation entity
	afterSave(categoryID, entity, editorID)

	// Return CategoryLocalisation
	return &id
}