package printing_order_operations

import (
	repo "github.com/bakeable/bkry/data/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Delete(repository repo.IRepository, printingOrderID string) {
	// Perform before delete actions for PrintingOrder entity
	beforeDelete(printingOrderID)

	// Delete PrintingOrder
	err := repository.DeletePrintingOrder(printingOrderID)
	if err != nil {
		panic(err)
	}

	// Perform after delete actions for PrintingOrder entity
	afterDelete(printingOrderID)
}