import { type JSONData } from '../../base_classes/dto.d'
import type IDto from '../../base_classes/dto.d'

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////


// Types
export type ContentType = "image" | "video" | "audio" | "file"

// Interfaces

// Data Transfer Object Interface
export interface IMediaDto extends IDto {
  /// ///////////////////////////////////////
  /// //////// PRIVATE VARIABLES ////////////
  /// ///////////////////////////////////////
  /**
   * The path to the corresponding API endpoint with variables marked as {?}
   */
  _path: string

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////

    // The type of content: image, video, audio or file
    contentType: ContentType

    // The description of the media
    description: string

    // The file extension
    extension: string

    // The filename of the media
    filename: string

    // The official file mimetype
    mimeType: string

    // The size of the file in Kb
    size: string

    // The Firebase Storage location
    storagePath: string

    // The public URL to get media directly from the internet
    url: string

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////

  /**
   * Set the Media's properties
   */
  set: (data: JSONData) => void
}
