import { type TagLocalisation } from './interface.gen'
import { type Store } from 'pinia'
import { Pagination } from "../../general/pagination"
import { Query } from "../../general/query"

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Represents the state of the tagLocalisation store.
 */
export interface TagLocalisationStoreState {
  /**
   * The currently active tagLocalisation ID
   */
  activeID: string | null

  /**
   * A cache of tagLocalisations.
   */
  cache: Record<string, {
    ids: string[]
    pagination: Pagination
    retrievalTimestamp: number
  }>

  /**
   * The list of tagLocalisations.
   */
  list: TagLocalisation[]

  /**
   * The retrieval timestamp
   */
  retrievalTimestamp: number

  /**
   * A key that is updated to force the update of the entity.
   */
  updateKey: number

  /**
   * A timeout before emitting a store update event.
   */
  storeUpdateTimeout: window.Timeout | null
}

/**
 * Represents an TagLocalisationStore that extends the Store interface.
 */
export interface TagLocalisationStore extends TagLocalisationStoreState, Store {
  /**
   * The currently active tagLocalisation
   */
  active: TagLocalisation | null

  /**
   * Adds an tagLocalisation to the local TagLocalisationStore.
   * @param tagLocalisation The tagLocalisation to be added.
   */
  add: (tagLocalisation: TagLocalisation) => void

  /**
   * Checks whether the list contains an instance with the provided ID.
   * @param id The id to be searched.
   * @returns {boolean} A boolean indicating whether the list contains the ID.
   */
  contains: (id: string) => boolean

  /**
   * Creates a new tagLocalisation in the external database and updates the store.
   * @param tagLocalisation The tagLocalisation to be created.
   * @returns {Promise<TagLocalisation>} A promise that resolves with the created tagLocalisation.
   */
  create: (tagId: string, tagLocalisation: TagLocalisation) => Promise<TagLocalisation>

  /**
   * Deletes an tagLocalisation from the TagLocalisationStore from the external database.
   * @param tagLocalisation The tagLocalisation to be deleted.
   * @returns {Promise<void>} A promise that resolves when the tagLocalisation is deleted.
   */
  delete: (tagLocalisation: TagLocalisation) => Promise<void>

  /**
   * Deletes an tagLocalisation by ID from the TagLocalisationStore from the external database.
   * @param id The ID to be deleted.
   * @returns {Promise<void>} A promise that resolves when the tagLocalisation is deleted.
   */
  deleteById: (id: string) => Promise<void>

  /**
   * Fire a form update event for the TagLocalisation.
   */
  emitFormUpdateEvent: (id: string) => void

  /**
   * Fire a store update event for all TagLocalisations.
   */
  emitStoreUpdateEvent: () => void

  /**
   * Get a TagLocalisation from the local TagLocalisationStore.
   * @returns { TagLocalisation | null } The tagLocalisation.
   */
  get: (id: string) => TagLocalisation | null

  /**
   * Queries tagLocalisations from the external source
   * @param queries The queries to be used for filtering.
   * @param pagination The pagination to be used for the query.
   * @param force Whether to force the query to the external source.
   * @returns {Promise<{ pagination: Pagination; items: TagLocalisation[] }>} A promise that resolves with queried tagLocalisations.
   */
  query: (tagId: string, queries: Query[], pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: TagLocalisation[]
  }>

  /**
   * Reinserts an tagLocalisation to the TagLocalisationStore list.
   * @param tagLocalisation The tagLocalisation to be reinserted.
   * @returns {void}
   */
  reinsert: (tagLocalisation: TagLocalisation) => void

  /**
   * Removes an tagLocalisation from the local TagLocalisationStore.
   * @param tagLocalisation The tagLocalisation to be removed.
   * @returns {void}
   */
  remove: ({ id }: TagLocalisation) => void

  /**
   * Determines whether a refresh of the store is required
   */
  refreshRequired: boolean

  /**
   * Retrieves a single TagLocalisation from either the local TagLocalisationStore or external source, if forced or required.
   * @param id The ID of the TagLocalisation to retrieve.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<TagLocalisation>} A promise that resolves when the tagLocalisation is set as active.
   */
  retrieve: (tagId: string, id: string, force?: boolean) => Promise<TagLocalisation>

  /**
   * Retrieves all tagLocalisations from the TagLocalisationStore or external source, depending if a refresh is required.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<{ active: string | null; items: TagLocalisation[] }>} A promise that resolves with an array of tagLocalisations.
   */
  retrieveAll: (tagId: string, force?: boolean) => Promise<{
    active: string | null
    items: TagLocalisation[]
  }>

  /**
   * Retrieves tagLocalisations paginated from the external source.
   * @param pagination The pagination to be used for the query.
   * @param force Whether to force the query to the external source.
   * @returns {Promise<{ pagination: Pagination; items: TagLocalisation[] }>} A promise that resolves with paginated tagLocalisations.
   */
  retrievePaginated: (tagId: string, pagination?: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: TagLocalisation[]
  }>

  /**
   * Searches for tagLocalisations in the external source.
   * @param search The search query string.
   * @param pagination The pagination to be used for the search.
   * @param force Whether to force the search to the external source.
   * @returns {Promise<{ pagination: Pagination; items: TagLocalisation[] }>} A promise that resolves with search results.
   */
  search: (tagId: string, search: string, pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: TagLocalisation[]
  }>

  /**
   * Update an tagLocalisation from the TagLocalisationStore in the external database.
   * @param tagLocalisation The tagLocalisation to be updated.
   * @returns {Promise<TagLocalisation>} A promise that resolves with the updated tagLocalisation.
   */
  update: (tagLocalisation: TagLocalisation) => Promise<TagLocalisation>
}
