package purchase_operations

import (
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Delete(repository repo.IRepository, userID string, purchaseID string) {
	// Perform before delete actions for Purchase entity
	beforeDelete(userID, purchaseID)

	// Delete Purchase
	err := repository.DeletePurchase(userID, purchaseID)
	if err != nil {
		panic(err)
	}

	// Perform after delete actions for Purchase entity
	afterDelete(userID, purchaseID)
}