package purchase_operations

import (
	purchase "github.com/bakeable/bkry/internal/server/models/entities/purchase"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
	"github.com/bakeable/bkry/internal/server/database"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Query(repository repo.IRepository, userID string, queries []database.Query, pagination database.Pagination) []purchase.Purchase {
	// Get Purchases
	entities, err := repository.QueryPurchases(userID, queries, pagination)
	if err != nil {
		panic(err)
	}

	// Process Purchase entities
	entities = afterQuery(userID, entities)

	// Return Purchases
	return entities
}