package entities

var airlinePricingFields = []FieldConfig{
	{
		FieldName: "Kind",
		FieldType: "string",
		JsonName: "kind",
		Description: "The kind of the object",
		DefaultValue: "AirlinePricing",
	},
	{
		FieldName: "Colors",
		FieldType: "[]int",
		JsonName: "colors",
		Description: "The number of colors for the airline pricing",
		DefaultValue: "[]int{}",
	},
	{
		FieldName: "Description",
		FieldType: "string",
		JsonName: "description",
		Description: "The description of the airline pricing",
		DefaultValue: "",
	},
	{
		FieldName: "Dividers",
		FieldType: "int",
		JsonName: "dividers",
		Description: "The number of dividers for the airline pricing",
		DefaultValue: "0",
	},
	{
		FieldName: "Margin",
		FieldType: "Margin",
		JsonName: "margin",
		Description: "The pricing table's margin",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName: "Type",
				FieldType: "string",
				JsonName: "type",
				Description: "The type of margin",
				DefaultValue: "percentage",
			},
			{
				FieldName: "Amount",
				FieldType: "int",
				JsonName: "amount",
				Description: "The amount of margin",
			},
			{
				FieldName: "Percentage",
				FieldType: "int",
				JsonName: "percentage",
				Description: "The percentage of margin",
			},
			{
				FieldName: "PercentageType",
				FieldType: "string",
				JsonName: "percentageType",
				Description: "The type of percentage",
				DefaultValue: "profit-margin",
			},
			{
				FieldName: "Staggered",
				FieldType: "bool",
				JsonName: "staggered",
				Description: "Whether the margin is staggered",
			},
			{
				FieldName: "Values",
				FieldType: "[]interface{}",
				JsonName: "values",
				Description: "The values of the margin",
				DefaultValue: "[]interface{}{}",
			},
		},
	},
	{
		FieldName: "Units",
		FieldType: "[]int",
		JsonName: "units",
		Description: "An array of units for the airline pricing",
		DefaultValue: "[]int{}",
	},
	{
		FieldName: "Values",
		FieldType: "AirlinePricingValue",
		JsonName: "values",
		Description: "An array of values for the airline pricing",
		IsArray: true,
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName: "PricingValue",
				FieldType: "PricingValue",
				JsonName: "value",
				IsChildStruct: true,
				Description: "The value for the airline pricing",
				Fields: []FieldConfig{
					{
						FieldName: "TextValue",
						FieldType: "string",
						JsonName: "textValue",
						Description: "The text value for the airline pricing",
					},
					{
						FieldName: "FloatValue",
						FieldType: "float64",
						JsonName: "floatValue",
						Description: "The float value for the airline pricing",
					},
					{
						FieldName: "IntValue",
						FieldType: "int",
						JsonName: "intValue",
						Description: "The int value for the airline pricing",
					},
					{
						FieldName: "DecimalValue",
						FieldType: "float64",
						JsonName: "decimalValue",
						Description: "The decimal value for the airline pricing",
					},
				},
			},
			{
				FieldName: "PricingAttributes",
				FieldType: "PricingAttributes",
				JsonName: "attributes",
				IsChildStruct: true,
				Description: "The attributes for the airline pricing",
				Fields: []FieldConfig{
					{
						FieldName: "Colors",
						FieldType: "int",
						JsonName: "colors",
						Description: "The colors for the airline pricing",
					},
					{
						FieldName: "Units",
						FieldType: "int",
						JsonName: "units",
						Description: "The units for the airline pricing",
					},
				},
			},
		},
	},
	{
		FieldName: "Width",
		FieldType: "float64",
		JsonName: "width",
		Description: "The width of the airline pricing",
		DefaultValue: "0.0",
	},
	{
		FieldName: "WidthType",
		FieldType: "string",
		JsonName: "widthType",
		Description: "The type of width for the airline pricing",
		DefaultValue: "MILLIMETERS",
	},
}
