package entities

var airlineOrderFields = []FieldConfig{
	{
		FieldName: "Kind",
		FieldType: "string",
		JsonName: "_kind",
		Description: "The kind of the object",
		DefaultValue: "AirlineOrder",
	},
	{
		FieldName: "CustomerId",
		FieldType: "string",
		JsonName: "customerId",
		Description: "The ID of the customer associated with the airline order",
		DefaultValue: "",
	},
	{
		FieldName: "CustomerName",
		FieldType: "string",
		JsonName: "customerName",
		Description: "The name of the customer associated with the airline order",
		DefaultValue: "",
	},
	{
		FieldName: "Date",
		FieldType: "string",
		JsonName: "date",
		Description: "The date of the airline order",
		DefaultValue: "new Date()",
	},
	{
		FieldName: "DeliveryAddress",
		FieldType: "string",
		JsonName: "deliveryAddress",
		Description: "The delivery address of the order",
		DefaultValue: "",
	},
	{
		FieldName: "Description",
		FieldType: "string",
		JsonName: "description",
		Description: "The description of the airline order",
		DefaultValue: "",
	},
	{
		FieldName: "Guid",
		FieldType: "string",
		JsonName: "guid",
		Description: "The unique identifier of the airline order",
		DefaultValue: "",
	},
	{
		FieldName: "IsGrouped",
		FieldType: "bool",
		JsonName: "isGrouped",
		Description: "Whether the airline order has already been grouped",
		DefaultValue: "false",
	},
	{
		FieldName: "Margin",
		FieldType: "Margin",
		JsonName: "margin",
		Description: "The order margin",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName: "Type",
				FieldType: "string",
				JsonName: "type",
				Description: "The type of margin",
				DefaultValue: "percentage",
			},
			{
				FieldName: "Amount",
				FieldType: "int",
				JsonName: "amount",
				Description: "The amount of margin",
			},
			{
				FieldName: "Percentage",
				FieldType: "int",
				JsonName: "percentage",
				Description: "The percentage of margin",
			},
			{
				FieldName: "PercentageType",
				FieldType: "string",
				JsonName: "percentageType",
				Description: "The type of percentage",
				DefaultValue: "profit-margin",
			},
			{
				FieldName: "Staggered",
				FieldType: "bool",
				JsonName: "staggered",
				Description: "Whether the margin is staggered",
			},
			{
				FieldName: "Values",
				FieldType: "[]interface{}",
				JsonName: "values",
				Description: "The values of the margin",
				DefaultValue: "[]interface{}{}",
			},
		},
	},
	{
		FieldName: "OrderNumber",
		FieldType: "string",
		JsonName: "orderNumber",
		Description: "The order number of the airline order",
		DefaultValue: "",
	},
	{
		FieldName: "OriginalTotalCosts",
		FieldType: "int",
		JsonName: "originalTotalCosts",
		Description: "The original total costs (when separately ordered)",
		DefaultValue: "0",
	},
	{
		FieldName: "OriginalUnitCosts",
		FieldType: "int",
		JsonName: "originalUnitCosts",
		Description: "The original unit costs (when separately ordered)",
		DefaultValue: "0",
	},
	{
		FieldName: "SerialNumber",
		FieldType: "int",
		JsonName: "serialNumber",
		Description: "The serial number of the airline order",
		DefaultValue: "0",
	},
	{
		FieldName: "Sku",
		FieldType: "string",
		JsonName: "sku",
		Description: "The SKU (Stock Keeping Unit) of the airline order",
		DefaultValue: "",
	},
	{
		FieldName: "Status",
		FieldType: "string",
		JsonName: "status",
		Description: "The status of the airline order",
		DefaultValue: "",
	},
	{
		FieldName: "Width",
		FieldType: "int",
		JsonName: "width",
		Description: "The width of the ordered airline foil",
		DefaultValue: "",
	},
	{
		FieldName: "WidthUnitType",
		FieldType: "int",
		JsonName: "widthUnitType",
		Description: "The width unit type of the ordered airline foil",
		DefaultValue: "",
	},
	{
		FieldName: "Colors",
		FieldType: "int",
		JsonName: "colors",
		Description: "The number of colors of the airline order",
		DefaultValue: "0",
	},
	{
		FieldName: "Dividers",
		FieldType: "int",
		JsonName: "dividers",
		Description: "The number of dividers of the airline order",
	},
	{
		FieldName: "Units",
		FieldType: "int",
		JsonName: "units",
		Description: "The number of units in the airline order",
		DefaultValue: "0",
	},
	{
		FieldName: "UnitType",
		FieldType: "string",
		JsonName: "unitType",
		Description: "The unit type of the airline order",
		DefaultValue: "",
	},
	{
		FieldName: "Warehouse",
		FieldType: "string",
		JsonName: "warehouse",
		Description: "The warehouse of the airline order",
		DefaultValue: "",
	},
	{
		FieldName: "Nummer",
		FieldType: "string",
		JsonName: "number",
		Description: "The number of the airline order",
		DefaultValue: "",
	},
	{
		FieldName: "Inkooprelatie",
		FieldType: "string",
		JsonName: "supplierId",
		Description: "The ID of the supplier associated with the airline order",
		DefaultValue: "",
	},
	{
		FieldName: "AfasOrderNumber",
		FieldType: "string",
		JsonName: "afasOrderNumber",
		Description: "The AFAS order number of the airline order",
		DefaultValue: "",
	},
	{
		FieldName: "UnitCosts",
		FieldType: "float64",
		JsonName: "unitCosts",
		Description: "The unit costs of the airline order",
		DefaultValue: "0.0",
	},
	{
		FieldName: "TotalCosts",
		FieldType: "float64",
		JsonName: "totalCosts",
		Description: "The total costs of the airline order",
		DefaultValue: "0.0",
	},
}