package entities

var airlineOrderGroupingFields = []FieldConfig{
	{
		FieldName: "Kind",
		FieldType: "string",
		JsonName: "_kind",
		Description: "The kind of the object",
		DefaultValue: "AirlineOrderGrouping",
	},
	{
		FieldName: "AfasOrderNumbers",
		FieldType: "string",
		JsonName: "afasOrderNumbers",
		Description: "The returned order number from AFAS",
		DefaultValue: "[]string{}",
		IsArray: true,
	},
	{
		FieldName: "FirstOrderDate",
		FieldType: "string",
		JsonName: "firstOrderDate",
		Description: "The date the first order was placed",
		DefaultValue: "time.Now()",
	},
	{
		FieldName: "FinalPrice",
		FieldType: "float64",
		JsonName: "finalPrice",
		Description: "The final price of this order grouping",
		DefaultValue: "0",
	},
	{
		FieldName: "MarginAmount",
		FieldType: "float64",
		JsonName: "marginAmount",
		Description: "The total amount of margin",
		DefaultValue: "0",
	},
	{
		FieldName: "MarginPercentage",
		FieldType: "float64",
		JsonName: "marginPercentage",
		Description: "The total amount of margin",
		DefaultValue: "0",
	},
	{
		FieldName: "Name",
		FieldType: "string",
		JsonName: "name",
		Description: "A reference name for the airline order grouping",
		DefaultValue: "",
	},
	{
		FieldName: "OrderIds",
		FieldType: "string",
		JsonName: "orderIds",
		Description: "The list of airline orders within the grouping",
		DefaultValue: "[]string{}",
		IsArray: true,
	},
	{
		FieldName: "OrderGroups",
		FieldType: "airline_order_group.AirlineOrderGroup",
		JsonName: "orderGroups",
		Description: "The list of order groups within the grouping",
		IsArray: true,
	},
	{
		FieldName: "OrderDate",
		FieldType: "string",
		JsonName: "orderDate",
		Description: "The date the order grouping needs to be ordered",
		DefaultValue: "time.Now()",
	},
	{
		FieldName: "OriginalTotalCosts",
		FieldType: "float64",
		JsonName: "originalTotalCosts",
		Description: "The original costs when using separated orders",
		DefaultValue: "0",
	},
	{
		FieldName: "SentToAfas",
		FieldType: "bool",
		JsonName: "sentToAfas",
		Description: "Whether the order grouping has been sent to AFAS",
		DefaultValue: "false",
	},
	{
		FieldName: "SavedCosts",
		FieldType: "float64",
		JsonName: "savedCosts",
		Description: "The costs saved when using this order grouping",
		DefaultValue: "0",
	},
	{
		FieldName: "TotalCosts",
		FieldType: "float64",
		JsonName: "totalCosts",
		Description: "The total costs of this order grouping",
		DefaultValue: "0",
	},
	{
		FieldName: "ProfitAmount",
		FieldType: "float64",
		JsonName: "profitAmount",
		Description: "The total profit amount of this order grouping",
		DefaultValue: "0",
	},
	{
		FieldName: "ProfitPercentage",
		FieldType: "float64",
		JsonName: "profitPercentage",
		Description: "The total profit percentage of this order grouping",
		DefaultValue: "0",
	},
	{
		FieldName: "Units",
		FieldType: "int",
		JsonName: "units",
		Description: "The total number of units of the airline order grouping",
		DefaultValue: "0",
	},
	{
		FieldName: "SentToAfasTimestamp",
		FieldType: "int64",
		JsonName: "sentToAfasTimestamp",
		Description: "The timestamp of when the order grouping was sent to AFAS",
		DefaultValue: "0",
	},
}
