package entities

var examinationSettingsFields = []FieldConfig{
	{
		FieldName:    "Kind",
		FieldType:    "string",
		JsonName:     "kind",
		Description:  "The kind of the object",
		DefaultValue: "'ExaminationSettings'",
	},
	{
		FieldName:    "MinProducts",
		FieldType:    "int",
		JsonName:     "minProducts",
		Description:  "Minimum number of delivery entries to examine",
		DefaultValue: "1",
	},
	{
		FieldName:    "MaxProducts",
		FieldType:    "int",
		JsonName:     "maxProducts",
		Description:  "Maximum number of delivery entries to examine",
		DefaultValue: "10",
	},
	{
		FieldName:    "MinProperties",
		FieldType:    "int",
		JsonName:     "minProperties",
		Description:  "Minimum number of properties to examine",
		DefaultValue: "1",
	},
	{
		FieldName:    "MaxProperties",
		FieldType:    "int",
		JsonName:     "maxProperties",
		Description:  "Maximum number of properties to examine",
		DefaultValue: "5",
	},
	{
		FieldName:    "ExclusionTime",
		FieldType:    "int64",
		JsonName:     "exclusionTime",
		Description:  "Standard timeframe from which to select tasks (in milliseconds)",
		DefaultValue: "2592000000",
	},
	{
		FieldName:    "SelectionTime",
		FieldType:    "int64",
		JsonName:     "selectionTime",
		Description:  "Timeframe from which to select delivery entries (in milliseconds)",
		DefaultValue: "604800000",
	},
	{
		FieldName:    "MaxOpenTasks",
		FieldType:    "int",
		JsonName:     "maxOpenTasks",
		Description:  "Maximum number of open tasks",
		DefaultValue: "20",
	},
	{
		FieldName:    "Properties",
		FieldType:    "string",
		JsonName:     "properties",
		Description:  "Properties to examine",
		DefaultValue: "[]string{\"weightNet\", \"weightGross\"}",
		IsArray:      true,
	},
	{
		FieldName: "ExclusionTimeFrame",
		FieldType: "ExclusionTimeFrame",
		JsonName:  "exclusionTimeFrame",
		Description: "Exclusion time frame",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName:    "Days",
				FieldType:    "int",
				JsonName:     "days",
				Description:  "Number of days in the exclusion time frame",
				DefaultValue: "0",
			},
			{
				FieldName:    "Hours",
				FieldType:    "int",
				JsonName:     "hours",
				Description:  "Number of hours in the exclusion time frame",
				DefaultValue: "0",
			},
		},
	},
	{
		FieldName: "SelectionTimeFrame",
		FieldType: "SelectionTimeFrame",
		IsChildStruct: true,
		JsonName:  "selectionTimeFrame",
		Description: "Selection time frame",
		Fields: []FieldConfig{
			{
				FieldName:    "Days",
				FieldType:    "int",
				JsonName:     "days",
				Description:  "Number of days in the selection time frame",
				DefaultValue: "0",
			},
			{
				FieldName:    "Hours",
				FieldType:    "int",
				JsonName:     "hours",
				Description:  "Number of hours in the selection time frame",
				DefaultValue: "0",
			},
		},
	},
}
