package entities

var packingSlipFields = []FieldConfig{
	{
		FieldName:     "Kind",
		FieldType:     "string",
		JsonName:      "_kind",
		Description:   "Type of the packing slip",
		DefaultValue:  "PackingSlip",
	},
	{
		FieldName:     "Awb",
		FieldType:     "string",
		JsonName:      "awb",
		Description:   "Airway bill number",
		DefaultValue:  "",
	},
	{
		FieldName:     "Address",
		FieldType:     "Address",
		JsonName:      "address",
		Description:   "Recipient's address",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName:     "City",
				FieldType:     "string",
				JsonName:      "city",
				Description:   "City of the address",
				DefaultValue:  "",
			},
			{
				FieldName:     "Country",
				FieldType:     "string",
				JsonName:      "country",
				Description:   "Country of the address",
				DefaultValue:  "",
			},
			{
				FieldName:     "Description",
				FieldType:     "string",
				JsonName:      "description",
				Description:   "Description of the address",
				DefaultValue:  "",
			},
			{
				FieldName:     "Formatted",
				FieldType:     "string",
				JsonName:      "formatted",
				Description:   "Formatted address string",
				DefaultValue:  "",
			},
			{
				FieldName:     "HouseNumber",
				FieldType:     "string",
				JsonName:      "houseNumber",
				Description:   "House number of the address",
				DefaultValue:  "",
			},
			{
				FieldName:     "PostalCode",
				FieldType:     "string",
				JsonName:      "postalCode",
				Description:   "Postal code of the address",
				DefaultValue:  "",
			},
			{
				FieldName:     "Street",
				FieldType:     "string",
				JsonName:      "street",
				Description:   "Street of the address",
				DefaultValue:  "",
			},
		},
	},
	{
		FieldName:     "AddedBy",
		FieldType:     "string",
		JsonName:      "addedBy",
		Description:   "Name of the person who added this packing slip",
		DefaultValue:  "",
	},
	{
		FieldName:     "Administration",
		FieldType:     "string",
		JsonName:      "administration",
		Description:   "The administration related to this packing slip",
		DefaultValue:  "",
	},
	{
		FieldName:     "CarrierCode",
		FieldType:     "CarrierCode",
		IsEnum: 	  	true,
		EnumValues: 	[]string{"BRTB", "BRT", "AFH", "OEG"},
		JsonName:      "carrierCode",
		Description:   "Carrier code for the shipment",
		DefaultValue:  "BRT",
	},
	{
		FieldName:     "CombinedPackingSlipIds",
		FieldType:     "string",
		JsonName:      "combinedPackingSlipIds",
		Description:   "List of combined packing slip IDs",
		IsArray:       true,
	},
	{
		FieldName:     "CombinedOrderNumbers",
		FieldType:     "string",
		JsonName:      "combinedOrderNumbers",
		Description:   "List of combined order numbers",
		IsArray:       true,
	},
	{
		FieldName:     "Customer",
		FieldType:     "Customer",
		JsonName:      "customer",
		Description:   "Customer details",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName:     "Name",
				FieldType:     "string",
				JsonName:      "name",
				Description:   "Name of the customer",
				DefaultValue:  "",
			},
			{
				FieldName:     "Email",
				FieldType:     "string",
				JsonName:      "email",
				Description:   "Email of the customer",
				DefaultValue:  "",
			},
			{
				FieldName:     "PhoneNumber",
				FieldType:     "string",
				JsonName:      "phoneNumber",
				Description:   "Phone number of the customer",
				DefaultValue:  "",
			},
		},
	},
	{
		FieldName:     "Date",
		FieldType:     "string",
		JsonName:      "date",
		Description:   "Date of the packing slip",
		DefaultValue:  "",
	},
	{
		FieldName:     "Delivery",
		FieldType:     "Delivery",
		JsonName:      "delivery",
		Description:   "Delivery details",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName:     "AfterTime",
				FieldType:     "AfterTime",
				JsonName:      "afterTime",
				Description:   "Time after which the delivery is expected",
				IsChildStruct: true,
				Fields: []FieldConfig{
					{
						FieldName:     "Hour",
						FieldType:     "int",
						JsonName:      "hour",
						Description:   "Hour of the delivery time",
						DefaultValue:  "9",
					},
					{
						FieldName:     "Minute",
						FieldType:     "int",
						JsonName:      "minute",
						Description:   "Minute of the delivery time",
						DefaultValue:  "0",
					},
				},
			},
			{
				FieldName:     "BeforeTime",
				FieldType:     "BeforeTime",
				JsonName:      "beforeTime",
				Description:   "Time before which the delivery is expected",
				IsChildStruct: true,
				Fields: []FieldConfig{
					{
						FieldName:     "Hour",
						FieldType:     "int",
						JsonName:      "hour",
						Description:   "Hour of the delivery time",
						DefaultValue:  "17",
					},
					{
						FieldName:     "Minute",
						FieldType:     "int",
						JsonName:      "minute",
						Description:   "Minute of the delivery time",
						DefaultValue:  "0",
					},
				},
			},
			{
				FieldName:     "Date",
				FieldType:     "string",
				JsonName:      "date",
				Description:   "Date of the delivery",
				DefaultValue:  "",
			},
			{
				FieldName:     "Notes",
				FieldType:     "string",
				JsonName:      "notes",
				Description:   "Notes about the delivery",
				DefaultValue:  "",
			},
		},
	},
	{
		FieldName:     "IncotermCode",
		FieldType:     "string",
		JsonName:      "incotermCode",
		Description:   "Incoterm code for the shipment",
		DefaultValue:  "",
	},
	{
		FieldName:     "CompanyName",
		FieldType:     "string",
		JsonName:      "companyName",
		Description:   "Name of the company",
		DefaultValue:  "",
	},
	{
		FieldName:     "MainPackingSlipId",
		FieldType:     "string",
		JsonName:      "mainPackingSlipId",
		Description:   "ID of the main packing slip",
		DefaultValue:  "",
	},
	{
		FieldName:     "MarkedAsCompleted",
		FieldType:     "bool",
		JsonName:      "markedAsCompleted",
		Description:   "Flag indicating if the packing slip is marked as completed",
		DefaultValue:  "false",
	},
	{
		FieldName:     "MarkedAsPrinted",
		FieldType:     "bool",
		JsonName:      "markedAsPrinted",
		Description:   "Flag indicating if the packing slip is marked as printed",
		DefaultValue:  "false",
	},
	{
		FieldName:     "MarkedAsPushed",
		FieldType:     "bool",
		JsonName:      "markedAsPushed",
		Description:   "Flag indicating if the packing slip is marked as pushed",
		DefaultValue:  "false",
	},
	{
		FieldName:     "Note",
		FieldType:     "string",
		JsonName:      "note",
		Description:   "Additional note for the packing slip",
		DefaultValue:  "",
	},
	{
		FieldName:     "OrderCreatedBy",
		FieldType:     "string",
		JsonName:      "orderCreatedBy",
		Description:   "Name of the person who created the order",
		DefaultValue:  "",
	},
	{
		FieldName:     "OrderNumber",
		FieldType:     "string",
		JsonName:      "orderNumber",
		Description:   "Order number associated with the packing slip",
		DefaultValue:  "",
	},
	{
		FieldName:     "OrderProcessing",
		FieldType:     "string",
		JsonName:      "orderProcessing",
		Description:   "Order processing details",
		DefaultValue:  "",
	},
	{
		FieldName:     "OriginalTotalGrossWeight",
		FieldType:     "float64",
		JsonName:      "originalTotalGrossWeight",
		Description:   "Original total gross weight of the shipment",
		DefaultValue:  "0.0",
	},
	{
		FieldName:     "Packages",
		FieldType:     "Package",
		JsonName:      "packages",
		Description:   "List of packages in the shipment",
		ArrayMatchOn:  "transsmartCode",
		IsArray: 		true,
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName:     "Amount",
				FieldType:     "int",
				JsonName:      "amount",
				Description:   "Number of packages",
				DefaultValue:  "0",
			},
			{
				FieldName:     "Dimensions",
				FieldType:     "Dimensions",
				JsonName:      "dimensions",
				Description:   "Dimensions of the package",
				IsChildStruct: true,
				Fields: []FieldConfig{
					{
						FieldName:     "Height",
						FieldType:     "dimension.Dimension",
						JsonName:      "height",
						Description:   "Height of the package",
					},
					{
						FieldName:     "Length",
						FieldType:     "dimension.Dimension",
						JsonName:      "length",
						Description:   "Length of the package",
					},
					{
						FieldName:     "Width",
						FieldType:     "dimension.Dimension",
						JsonName:      "width",
						Description:   "Width of the package",
					},
				},
			},
			{
				FieldName:     "TranssmartCode",
				FieldType:     "string",
				JsonName:      "transsmartCode",
				Description:   "Transsmart code for the package",
				DefaultValue:  "",
			},
			{
				FieldName:     "Type",
				FieldType:     "string",
				JsonName:      "type",
				Description:   "Type of the package",
				DefaultValue:  "",
			},
			{
				FieldName:     "Weight",
				FieldType:     "dimension.Dimension",
				JsonName:      "weight",
				Description:   "Weight of the package",
			},
		},
	},
	{
		FieldName:     "PromisedDeliveryDate",
		FieldType:     "string",
		JsonName:      "promisedDeliveryDate",
		Description:   "Promised delivery date",
		DefaultValue:  "",
	},
	{
		FieldName:     "Reference",
		FieldType:     "string",
		JsonName:      "reference",
		Description:   "Reference for the packing slip",
		DefaultValue:  "",
	},
	{
		FieldName:     "Service",
		FieldType:     "string",
		JsonName:      "service",
		Description:   "Service details",
		DefaultValue:  "",
	},
	{
		FieldName:     "SlipNumber",
		FieldType:     "string",
		JsonName:      "slipNumber",
		Description:   "Packing slip number",
		DefaultValue:  "",
	},
	{
		FieldName:     "Status",
		FieldType:     "PackingSlipStatus",
		JsonName:      "status",
		IsEnum: 	  true,
		EnumValues: []string{"shipment_not_created", "shipment_created", "shipment_ready"},
		Description:   "Status of the packing slip",
		DefaultValue: "shipment_not_created",
	},
	{
		FieldName: "StatusIndex",
		FieldType: "int",
		DefaultValue: "0",
		JsonName:  "statusIndex",
		Description: "The ordering index of the status",
	},
	{
		FieldName:     "TotalAmountExcludingVAT",
		FieldType:     "float64",
		JsonName:      "totalAmountExcludingVAT",
		Description:   "Total amount excluding VAT",
		DefaultValue:  "0.0",
	},
	{
		FieldName:     "TotalGrossWeight",
		FieldType:     "float64",
		JsonName:      "totalGrossWeight",
		Description:   "Total gross weight",
		DefaultValue:  "0.0",
	},
	{
		FieldName:     "TotalQuantity",
		FieldType:     "int",
		JsonName:      "totalQuantity",
		Description:   "Total quantity",
		DefaultValue:  "0",
	},
	{
		FieldName:     "TrackingUrl",
		FieldType:     "string",
		JsonName:      "trackingUrl",
		Description:   "Tracking URL",
		DefaultValue:  "",
	},
	{
		FieldName:     "SupplierContactName",
		FieldType:     "string",
		JsonName:      "supplierContactName",
		Description:   "Name of the supplier contact",
	},
	{
		FieldName: "SupplierID",
		FieldType: "string",
		JsonName: "supplierId",
		Description: "ID of the supplier",
	},
	{
		FieldName: "SupplierName",
		FieldType: "string",
		JsonName: "supplierName",
		Description: "Name of the supplier",
	},
	{
		FieldName: "Description",
		FieldType: "string",
		JsonName: "description",
		Description: "Description of the packing slip",
	},
}
