package entities

var printingOrderFields = []FieldConfig{
	{
		FieldName:    "Kind",
		FieldType:    "string",
		JsonName:     "_kind",
		Description:  "Type of the printing order",
		DefaultValue: "PrintingOrder",
	},
	{
		FieldName:    "AutoCorrespondence",
		FieldType:    "bool",
		JsonName:     "autoCorrespondence",
		Description:  "Flag indicating whether to automatically send correspondence",
		DefaultValue: "true",
	},
	{
		FieldName:    "ArtworkIsUrl",
		FieldType:    "bool",
		JsonName:     "artworkIsUrl",
		Description:  "Flag indicating whether the artwork is a URL or a file",
		DefaultValue: "false",
	},
	{
		FieldName:    "ArtworkApproved",
		FieldType:    "bool",
		JsonName:     "artworkApproved",
		Description:  "Flag indicating whether the artwork is approved",
		DefaultValue: "false",
	},
	{
		FieldName:    "Approved",
		FieldType:    "bool",
		JsonName:     "approved",
		Description:  "Flag indicating if the printing order has been approved",
		DefaultValue: "false",
	},
	{
		FieldName:    "ApprovedTimestamp",
		FieldType:    "int64",
		JsonName:     "approvedTimestamp",
		Description:  "The timestamp of the approved",
		DefaultValue: "0",
	},
	{
		FieldName:    "CompanyName",
		FieldType:    "string",
		JsonName:     "companyName",
		Description:  "The name of the company associated with the printing order",
		DefaultValue: "",
	},
	{
		FieldName:    "Correspondence",
		FieldType:    "PrintingOrderCorrespondence",
		JsonName:     "correspondence",
		Description:  "The correspondence tracking",
		IsArray:      true,
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName:    "Id",
				FieldType:    "string",
				JsonName:     "id",
				Description:  "ID of the correspondence",
				DefaultValue: "",
			},
			{
				FieldName:    "Key",
				FieldType:    "PrintingOrderCorrespondenceTemplateKey",
				JsonName:     "key",
				IsEnum: 	  true,
				EnumValues:   []string{
				"CUSTOMER_APPROVE_SAMPLE",
				"CUSTOMER_PRINTING_ORDER_RECEIVED",
				"CUSTOMER_TRACK_AND_TRACE",
				"SUPPLIER_PRINTING_ORDER_RECEIVED",
				"SUPPLIER_SAMPLE_ACCEPTED",
				"SUPPLIER_SAMPLE_REJECTED",
				},
				Description:  "Key of the correspondence",
				DefaultValue: "CUSTOMER_APPROVE_SAMPLE",
			},
			{
				FieldName:    "Timestamp",
				FieldType:    "int64",
				JsonName:     "timestamp",
				Description:  "Timestamp of the correspondence",
				DefaultValue: "0",
			},
			{
				FieldName:    "Sent",
				FieldType:    "bool",
				JsonName:     "sent",
				Description:  "Flag indicating if the correspondence was sent",
				DefaultValue: "false",
			},
			{
				FieldName:    "SentAt",
				FieldType:    "int64",
				JsonName:     "sentAt",
				Description:  "Timestamp when the correspondence was sent",
				DefaultValue: "0",
			},
			{
				FieldName:    "StatusLogIndex",
				FieldType:    "int",
				JsonName:     "statusLogIndex",
				Description:  "The index of the status log change that triggered the correspondence",
				DefaultValue: "0",
			},
		},
	},
	{
		FieldName:    "CustomerAddress",
		FieldType:    "CustomerAddress",
		JsonName:     "customerAddress",
		Description:  "The address of the customer",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName:    "Line",
				FieldType:    "string",
				JsonName:     "line",
				Description:  "Address line",
				DefaultValue: "",
			},
			{
				FieldName:    "City",
				FieldType:    "string",
				JsonName:     "city",
				Description:  "City of the address",
				DefaultValue: "",
			},
			{
				FieldName:    "Country",
				FieldType:    "string",
				JsonName:     "country",
				Description:  "Country of the address",
				DefaultValue: "NL",
			},
			{
				FieldName:    "PostalCode",
				FieldType:    "string",
				JsonName:     "postalCode",
				Description:  "Postal code of the address",
				DefaultValue: "",
			},
		},
	},
	{
		FieldName:    "CustomerName",
		FieldType:    "string",
		JsonName:     "customerName",
		Description:  "Name of the customer",
		DefaultValue: "",
	},
	{
		FieldName:    "CustomerEmail",
		FieldType:    "string",
		JsonName:     "customerEmail",
		Description:  "Email of the customer",
		DefaultValue: "",
	},
	{
		FieldName:    "Files",
		FieldType:    "PrintingOrderFiles",
		JsonName:     "files",
		Description:  "The files associated with the printing order",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName:    "Artwork",
				FieldType:    "media.Media",
				FieldTypeIsExternal: true,
				JsonName:     "artwork",
				Description:  "The artwork file",
			},
			{
				FieldName:    "OrderConfirmation",
				FieldType:    "media.Media",
				FieldTypeIsExternal: true,
				JsonName:     "orderConfirmation",
				Description:  "The order confirmation file",
			},
			{
				FieldName:    "Media",
				FieldType:    "media.Media",
				FieldTypeIsExternal: true,
				JsonName:     "media",
				Description:  "The media file",
			},
		},
				
	},
	{
		FieldName:    "Description",
		FieldType:    "string",
		JsonName:     "description",
		Description:  "Description of the printing order",
		DefaultValue: "",
	},
	{
		FieldName:    "EmailCode",
		FieldType:    "string",
		JsonName:     "emailCode",
		Description:  "The 10 digit e-mail code",
		DefaultValue: "",
	},
	{
		FieldName:    "ItemIndex",
		FieldType:    "int",
		JsonName:     "itemIndex",
		Description:  "The item index of the printing order",
		DefaultValue: "0",
	},
	{
		FieldName:    "IsAirtableOrder",
		FieldType:    "bool",
		JsonName:     "isAirtableOrder",
		Description:  "Whether the printing order is from Airtable",
		DefaultValue: "false",
	},
	{
		FieldName:    "Notes",
		FieldType:    "string",
		JsonName:     "notes",
		Description:  "Notes of the printing order",
		DefaultValue: "",
	},
	{
		FieldName:    "OrderNumber",
		FieldType:    "string",
		JsonName:     "orderNumber",
		Description:  "The order number of the printing order",
		DefaultValue: "",
	},
	{
		FieldName:    "OrderStatus",
		FieldType:    "string",
		JsonName:     "orderStatus",
		Description:  "The status of the order in Magento",
		DefaultValue: "",
	},
	{
		FieldName:    "ProductOptions",
		FieldType:    "ProductOption",
		JsonName:     "productOptions",
		Description:  "The options of the product",
		IsArray:      true,
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName:    "Id",
				FieldType:    "string",
				JsonName:     "id",
				Description:  "ID of the product option",
				DefaultValue: "",
			},
			{
				FieldName:    "Key",
				FieldType:    "string",
				JsonName:     "key",
				Description:  "Key of the product option",
				DefaultValue: "",
			},
			{
				FieldName:    "Value",
				FieldType:    "string",
				JsonName:     "value",
				Description:  "Value of the product option",
				DefaultValue: "",
			},
		},
	},
	{
		FieldName:    "Rejected",
		FieldType:    "bool",
		JsonName:     "rejected",
		Description:  "Whether the sample was rejected",
		DefaultValue: "false",
	},
	{
		FieldName:    "RejectionReason",
		FieldType:    "string",
		JsonName:     "rejectionReason",
		Description:  "The reason for rejection",
		DefaultValue: "",
	},
	{
		FieldName:    "SupplierContactName",
		FieldType:    "string",
		JsonName:     "supplierContactName",
		Description:  "Name of the supplier contact associated with the printing order",
		DefaultValue: "",
	},
	{
		FieldName:    "SupplierName",
		FieldType:    "string",
		JsonName:     "supplierName",
		Description:  "Name of the supplier associated with the printing order",
		DefaultValue: "",
	},
	{
		FieldName:    "SupplierId",
		FieldType:    "string",
		JsonName:     "supplierId",
		Description:  "ID of the supplier associated with the printing order",
		DefaultValue: "",
	},
	{
		FieldName:    "SupplierReference",
		FieldType:    "string",
		JsonName:     "supplierReference",
		Description:  "The supplier reference",
		DefaultValue: "",
	},
	{
		FieldName:    "Sku",
		FieldType:    "string",
		JsonName:     "sku",
		Description:  "SKU of the printing order",
		DefaultValue: "",
	},
	{
		FieldName:    "Status",
		FieldType:    "PrintingOrderStatus",
		JsonName:     "status",
		Description:  "Status of the printing order",
		DefaultValue: "new",
		IsEnum: 	 true,
		EnumValues:  []string{"new", "waiting_for_sample", "waiting_for_approval", "sample_rejected", "in_production", "shipped"},
	},
	{
		FieldName: "StatusIndex",
		FieldType: "int",
		DefaultValue: "0",
		JsonName:  "statusIndex",
		Description: "The ordering index of the status",
	},
	{
		FieldName:    "StatusLog",
		FieldType:    "PrintingOrderStatusLog",
		JsonName:     "statusLog",
		Description:  "The log of previous statuses",
		IsArray:      true,
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName:    "Status",
				FieldType:    "PrintingOrderStatus",
				JsonName:     "status",
				Description:  "Status of the printing order",
				DefaultValue: "new",
				IsEnum: 	  true,
				IsDuplicateEnum: true,
			},
			{
				FieldName:    "PrevStatus",
				FieldType:    "PrintingOrderStatus",
				JsonName:     "prevStatus",
				Description:  "Previous status of the printing order",
				DefaultValue: "new",
				IsEnum: 	  true,
				IsDuplicateEnum: true,
			},
			{
				FieldName:    "Timestamp",
				FieldType:    "int64",
				JsonName:     "timestamp",
				Description:  "Timestamp of the status change",
				DefaultValue: "0",
			},
		},
	},
	{
		FieldName:    "Quantity",
		FieldType:    "int",
		JsonName:     "quantity",
		Description:  "Quantity of the printing order",
		DefaultValue: "0",
	},
	{
		FieldName:    "QuantityOrdered",
		FieldType:    "int",
		JsonName:     "quantityOrdered",
		Description:  "Quantity ordered of the printing order",
		DefaultValue: "0",
	},
	{
		FieldName:    "NumberOfUnits",
		FieldType:    "int",
		JsonName:     "numberOfUnits",
		Description:  "Number of units ordered per quantity",
		DefaultValue: "0",
	},
	{
		FieldName:    "TrackingUrl",
		FieldType:    "string",
		JsonName:     "trackingUrl",
		Description:  "Tracking URL of the printing order",
		DefaultValue: "",
	},
	{
		FieldName:    "TrackingUrlApproved",
		FieldType:    "bool",
		JsonName:     "trackingUrlApproved",
		Description:  "Whether the tracking URL is approved",
		DefaultValue: "false",
	},
}
