package entities

var quotationFields = []FieldConfig{
	{
		FieldName: "Kind",
		FieldType: "string",
		JsonName: "_kind",
		Description: "The kind of the object",
		DefaultValue: "Quotation",
	},
	{
		FieldName: "LineItems",
		FieldType: "LineItem",
		JsonName: "lineItems",
		Description: "The quotation's added products",
		IsChildStruct: true,
		IsArray: true,
		Fields: []FieldConfig{
			{
				FieldName: "Attributes",
				FieldType: "map[string]string",
				JsonName: "attributes",
				Description: "The quotation's attributes",
				DefaultValue: "map[string]string{}",
			},
			{
				FieldName: "FinalPrice",
				FieldType: "float64",
				JsonName: "finalPrice",
				Description: "The final price of the quotation",
				DefaultValue: "0.0",
			},
			{
				FieldName: "FixedCosts",
				FieldType: "float64",
				JsonName: "fixedCosts",
				Description: "The fixed costs of the quotation",
				DefaultValue: "0.0",
			},
			{
				FieldName: "MarginAmount",
				FieldType: "float64",
				JsonName: "marginAmount",
				Description: "The margin amount of the quotation",
				DefaultValue: "0.0",
			},
			{
				FieldName: "MarginPercentage",
				FieldType: "float64",
				JsonName: "marginPercentage",
				Description: "The margin percentage of the quotation",
				DefaultValue: "0.0",
			},
			{
				FieldName: "Product",
				FieldType: "Product",
				JsonName: "product",
				Description: "The products information",
				IsChildStruct: true,
				Fields: []FieldConfig{
					{
						FieldName: "Name",
						FieldType: "string",
						JsonName: "name",
						Description: "The product's name",
						DefaultValue: "",
					},
					{
						FieldName: "ID",
						FieldType: "string",
						JsonName: "id",
						Description: "The product's id",
						DefaultValue: "",
					},
					{
						FieldName: "Sku",
						FieldType: "string",
						JsonName: "sku",
						Description: "The product's name",
						DefaultValue: "",
					},
				},
			},
			{
				FieldName: "TotalCosts",
				FieldType: "float64",
				JsonName: "totalCosts",
				Description: "The total costs of the quotation",
				DefaultValue: "0.0",
			},
			{
				FieldName: "Units",
				FieldType: "int",
				JsonName: "units",
				Description: "The number of units in the quotation",
				DefaultValue: "0",
			},
			{
				FieldName: "VariableCosts",
				FieldType: "float64",
				JsonName: "variableCosts",
				Description: "The variable costs of the quotation",
				DefaultValue: "0.0",
			},
		},
	},
	{
		FieldName: "Totals",
		FieldType: "Totals",
		JsonName: "totals",
		Description: "The quotation totals",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName: "FinalPrice",
				FieldType: "float64",
				JsonName: "finalPrice",
				Description: "The final price of the quotation",
				DefaultValue: "0.0",
			},
			{
				FieldName: "MarginAmount",
				FieldType: "float64",
				JsonName: "marginAmount",
				Description: "The margin amount of the quotation",
				DefaultValue: "0.0",
			},
			{
				FieldName: "MarginPercentage",
				FieldType: "float64",
				JsonName: "marginPercentage",
				Description: "The margin percentage of the quotation",
				DefaultValue: "0.0",
			},
			{
				FieldName: "TotalCosts",
				FieldType: "float64",
				JsonName: "totalCosts",
				Description: "The total costs of the quotation",
				DefaultValue: "0.0",
			},
		},
	},
	{
		FieldName: "Name",
		FieldType: "string",
		JsonName: "name",
		Description: "The quotation's name",
		DefaultValue: "",
	},
	{
		FieldName: "Status",
		FieldType: "QuotationStatus",
		JsonName: "status",
		Description: "The quotation's status",
		IsEnum: true,
		EnumValues: []string{"concept", "ready"},
		DefaultValue: "concept",
	},
	{
		FieldName: "StatusIndex",
		FieldType: "int",
		DefaultValue: "0",
		JsonName:  "statusIndex",
		Description: "The ordering index of the status",
	},
	{
		FieldName: "Customer",
		FieldType: "Customer",
		JsonName: "customer",
		Description: "The customer's information",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName: "Name",
				FieldType: "string",
				JsonName: "name",
				Description: "The customer's name",
				DefaultValue: "",
			},
			{
				FieldName: "Email",
				FieldType: "string",
				JsonName: "email",
				Description: "The customer's email",
				DefaultValue: "",
			},
			{
				FieldName: "Phone",
				FieldType: "string",
				JsonName: "phone",
				Description: "The customer's phone number",
				DefaultValue: "",
			},
			{
				FieldName: "Address",
				FieldType: "string",
				JsonName: "address",
				Description: "The customer's address",
				DefaultValue: "",
			},
		},
	},
	{
		FieldName: "Notes",
		FieldType: "string",
		JsonName: "notes",
		Description: "Any notes made on the quotation",
		DefaultValue: "",
	},
	{
		FieldName: "ReferralCode",
		FieldType: "string",
		JsonName: "referralCode",
		Description: "A supplied referral code",
		DefaultValue: "",
	},
}
