package entities

var userProfileFields = []FieldConfig{
	{
		FieldName: "Kind",
		FieldType: "string",
		JsonName: "_kind",
		Description: "The kind of the object",
		DefaultValue: "UserProfile",
	},
	{
		FieldName: "AccessLevel",
		FieldType: "AccessLevel",
		IsChildStruct: true,
		JsonName: "accessLevel",
		Description: "Which tools the user has access to",
		DefaultValue: "",
		Fields: []FieldConfig{
			{
				FieldName: "Admin",
				FieldType: "Permission",
				IsEnum: true,
				EnumValues: []string{"none", "read", "read_write"},
				IsDuplicateEnum: true,
				JsonName: "admin",
				DefaultValue: "none",
				Description: "The user's administrative access level",
			},
			{
				FieldName: "PriceConfiguration",
				FieldType: "Permission",
				IsEnum: true,
				EnumValues: []string{"none", "read", "read_write"},
				JsonName: "priceConfiguration",
				DefaultValue: "none",
				Description: "The user's access level to the price configuration tool",
			},
			{
				FieldName: "PackingSlips",
				FieldType: "Permission",
				IsEnum: true,
				EnumValues: []string{"none", "read", "read_write"},
				JsonName: "packingSlips",
				DefaultValue: "none",
				Description: "The user's access level to the packing slip tool",
			},
			{
				FieldName: "PrintingOrders",
				FieldType: "Permission",
				IsEnum: true,
				EnumValues: []string{"none", "read", "read_write"},
				JsonName: "printingOrders",
				DefaultValue: "none",
				Description: "The user's access level to the printing orders tool",
			},
			{
				FieldName: "Quotation",
				FieldType: "Permission",
				IsEnum: true,
				EnumValues: []string{"none", "read", "read_write"},
				IsDuplicateEnum: true,
				JsonName: "quotation",
				DefaultValue: "none",
				Description: "The user's access level to the quotation tool",
			},
			{
				FieldName: "Airlines",
				FieldType: "Permission",
				IsEnum: true,
				EnumValues: []string{"none", "read", "read_write"},
				IsDuplicateEnum: true,
				JsonName: "airlines",
				DefaultValue: "none",
				Description: "The user's access level to the airlines tool",
			},
			{
				FieldName: "SampleTest",
				FieldType: "Permission",
				IsEnum: true,
				EnumValues: []string{"none", "read", "read_write"},
				IsDuplicateEnum: true,
				JsonName: "sampleTest",
				DefaultValue: "none",
				Description: "The user's access level to the sample test tool",
			},
			{
				FieldName: "ApiDocs",
				FieldType: "Permission",
				IsEnum: true,
				EnumValues: []string{"none", "read", "read_write"},
				IsDuplicateEnum: true,
				JsonName: "apiDocs",
				DefaultValue: "none",
				Description: "The user's access level to the API documentation tool",
			},
			{
				FieldName: "UserManagement",
				FieldType: "Permission",
				IsEnum: true,
				EnumValues: []string{"none", "read", "read_write"},
				IsDuplicateEnum: true,
				JsonName: "userManagement",
				DefaultValue: "none",
				Description: "The user's access level to the user management tool",
			},
		},
	},
	{
		FieldName: "Address",
		FieldType: "map[string]interface{}",
		JsonName: "address",
		Description: "A user's address",
		DefaultValue: "",
	},
	{
		FieldName: "Email",
		FieldType: "string",
		JsonName: "email",
		Description: "A user's email address",
		DefaultValue: "",
	},
	{
		FieldName: "FirstName",
		FieldType: "string",
		JsonName: "firstName",
		Description: "A user's first name",
		DefaultValue: "",
	},
	{
		FieldName: "IsAdmin",
		FieldType: "bool",
		JsonName: "isAdmin",
		Description: "Whether the user has administrative rights",
		DefaultValue: "false",
	},
	{
		FieldName: "Infix",
		FieldType: "string",
		JsonName: "infix",
		Description: "A user's infix",
		DefaultValue: "",
	},
	{
		FieldName: "LastName",
		FieldType: "string",
		JsonName: "lastName",
		Description: "A user's last name",
		DefaultValue: "",
	},
	{
		FieldName: "Prefix",
		FieldType: "string",
		JsonName: "prefix",
		Description: "A user's prefix",
		DefaultValue: "",
	},
	{
		FieldName: "Language",
		FieldType: "Language",
		JsonName: "language",
		Description: "A user's language",
		IsEnum: true,
		EnumValues: []string{"en", "nl"},
		DefaultValue: "nl",
	},
	{
		FieldName: "Avatar",
		FieldType: "media.Media",
		JsonName: "avatar",
		Description: "A user's avatar",
	},
	{
		FieldName: "AvatarUrl",
		FieldType: "string",
		JsonName: "avatarUrl",
		Description: "The URL of a user's avatar",
	},
}
