package user_controllers

import (
	"net/http"
	user_operations "github.com/bakeable/bkry/internal/server/transport/operations/user"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func Get(c *gin.Context) {

	// Get user ID from URL
	userID := c.Param("userID")

	// Get user
	entity := user_operations.Get(getRepository(), userID)

	// Return user
	c.JSON(http.StatusOK, gin.H{ "item": entity })
}
