package printing_order_controllers

import (
	"net/http"
	printing_order_operations "github.com/bakeable/bkry/data/entities/printing_order/operations"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func Get(c *gin.Context) {

	// Get printing_order ID from URL
	printingOrderID := c.Param("printingOrderID")

	// Get printing_order
	entity := printing_order_operations.Get(getRepository(), printingOrderID)

	// Return printing_order
	c.JSON(http.StatusOK, gin.H{ "item": entity })
}
