import { Attribute } from './entity'
import DtoList from '../../base_classes/dto_list'
import { type JSONData } from '../../base_classes/dto.d'
import { type IAttributeList } from './list.gen.d'
import { type Pagination, type Query } from '../../base_classes/dto_list.d'


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////


export class AttributeList 
extends DtoList 
implements IAttributeList 
{
  /// ///////////////////////////////////////
  /// //////// PRIVATE VARIABLES ////////////
  /// ///////////////////////////////////////
  _path = '/attribute'
  _kind = 'Attribute'
  _name = 'attribute'

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////
  list: Attribute[] = []
  queriedList: Attribute[] = []

  /// ///////////////////////////////////////
  /// ////////////// METHODS ////////////////
  /// ///////////////////////////////////////

  _buildInstance(data: JSONData): Attribute {
    return new Attribute([], data)
  }

  override async getAll(
    pathVars?: string | string[] | Record<string, string>
  ): Promise<Attribute[]> {
    return (await super.getAll(pathVars)) as Attribute[]
  }

  override async getPaginated(
    pathVars: string | string[],
    pagination: Pagination
  ): Promise<{
    items: Attribute[],
    pagination: Pagination,
  }> {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    return (await super.getPaginated(pathVars, pagination)) as {
      items: Attribute[],
      pagination: Pagination,
    }
  }

  override async query(queries: Query[], pagination?: Pagination): Promise<Attribute[]> {
    return (await super.query(queries, pagination)) as Attribute[];
  }

  override async search(query: string, pagination?: Pagination): Promise<Attribute[]> {
    return (await super.search(query, pagination)) as Attribute[];
  }
}
