package airline_order_group_operations

import (
	airline_order_group "github.com/bakeable/bkry/internal/server/models/entities/airline_order_group"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Find(repository repo.IRepository, queries []datastore.Query) airline_order_group.AirlineOrderGroup {
	// Find AirlineOrderGroup
	entity, err := repository.FindAirlineOrderGroup(queries)
	if err != nil {
		panic(err)
	}

	// Process AirlineOrderGroup entity
	entity = afterFind(entity)

	// Return AirlineOrderGroup
	return entity
}