package portal_event_controllers

import (
	"net/http"
	portal_event_operations "github.com/bakeable/bkry/internal/server/transport/operations/portal_event"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func Delete(c *gin.Context) {

	// Get portal_event ID from URL
	portalEventID := c.Param("portalEventID")

	// Delete PortalEvent
	portal_event_operations.Delete(getRepository(), portalEventID)

	// Send response
	c.Status(http.StatusNoContent)

}

