import { type PackingSlipPackage } from './entity'
import { type Store } from 'pinia'


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Represents the state of the packingSlipPackage store.
 */
export interface PackingSlipPackageStoreState {
  /**
   * The currently active packingSlipPackage ID
   */
  activeID: string | null

  /**
   * A cache of packingSlipPackages.
   */
  cache: Record<string, {
    ids: string[]
    pagination: Pagination
    retrievalTimestamp: number
  }>

  /**
   * The list of packingSlipPackages.
   */
  list: PackingSlipPackage[]

  /**
   * The retrieval timestamp
   */
  retrievalTimestamp: number

  /**
   * A key that is updated to force the update of the entity.
   */
  updateKey: number

  /**
   * A timeout before emitting a store update event.
   */
  storeUpdateTimeout: window.Timeout | null
}

/**
 * Represents an PackingSlipPackageStore that extends the Store interface.
 */
export interface PackingSlipPackageStore extends PackingSlipPackageStoreState, Store {
  /**
   * Fire a form update event for the PackingSlipPackage.
   */
  emitFormUpdateEvent: (id: string) => void

  /**
   * Fire a store update event for all PackingSlipPackage.
   */
  emitStoreUpdateEvent: () => void

  /**
   * The currently active packingSlipPackage
   */
  active: PackingSlipPackage

  /**
   * Adds an packingSlipPackage to the local PackingSlipPackageStore.
   * @param packingSlipPackage The packingSlipPackage to be added.
   */
  add: (packingSlipPackage: PackingSlipPackage) => void

  /**
   * Checks whether the list contains an instance with the provided ID.
   * @param id The id to be searched.
   * @returns {boolean} A boolean indicating whether the list contains the ID.
   */
  contains: (id: string) => boolean

  /**
   * Deletes an packingSlipPackage from the PackingSlipPackageStore from the external database.
   * @param packingSlipPackage The packingSlipPackage to be deleted.
   * @returns {Promise<void>} A promise that resolves when the packingSlipPackage is deleted.
   */
  delete: (packingSlipPackage: PackingSlipPackage) => Promise<void>

  /**
   * Deletes an packingSlipPackage by ID from the PackingSlipPackageStore from the external database.
   * @param id The ID to be deleted.
   * @returns {Promise<void>} A promise that resolves when the packingSlipPackage is deleted.
   */
  deleteById: (id: string) => Promise<void>

  /**
   * Get a PackingSlipPackage from the local PackingSlipPackageStore.
   * @returns { PackingSlipPackage | null } The packingSlipPackage.
   */
  get: (id: string) => PackingSlipPackage | null

  /**
   * Reinserts an packingSlipPackage to the PackingSlipPackageStore list.
   * @param packingSlipPackage The packingSlipPackage to be reinserted.
   * @returns {void}
   */
  reinsert: (packingSlipPackage: PackingSlipPackage) => void

  /**
   * Removes an packingSlipPackage from the local PackingSlipPackageStore.
   * @param packingSlipPackage The packingSlipPackage to be removed.
   * @returns {void}
   */
  remove: (packingSlipPackage: PackingSlipPackage) => void

  /**
   * Determines whether a refresh of the store is required
   */
  refreshRequired: boolean

  /**
   * Retrieves a single PackingSlipPackage from either the local PackingSlipPackageStore or external source, if forced or required.
    * @param id The ID of the PackingSlipPackage to retrieve.
    * @param force Indicates whether a refresh is forced.
   * @returns {Promise<void>} A promise that resolves when the packingSlipPackage is set as active.
   */
  retrieve: (id: string, force?: boolean) => Promise<PackingSlipPackage>

  /**
   * Retrieves all packingSlipPackages from the PackingSlipPackageStore or external source, depending if a refresh is required.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<void>} A promise that resolves with an array of packingSlipPackages.
   */
  retrieveAll: (force?: boolean) => Promise<{
    active: string | null
    items: PackingSlipPackage[]
  }>

  /**
    * Retrieves packingSlipPackages paginated from the external source
    * @param pagination The pagination to be used for the query.
    * @param force Whether to force the query to the external source.
    * @returns {Promise<void>} A promise that resolves with an array of packingSlipPackages.
    */
  retrievePaginated: (pagination?: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: PackingSlipPackage[]
  }>

  /**
    * Queries packingSlipPackages from the external source
    * @param queries The queries to be used for filtering.
    * @param pagination The pagination to be used for the query.
    * @param force Whether to force the query to the external source.
    * @returns {Promise<void>} A promise that resolves with an array of packingSlipPackages.
    */
  query: (queries: Query[], pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: PackingSlipPackage[]
  }>

  /**
   * Update an packingSlipPackage from the PackingSlipPackageStore in the external database.
   * @param packingSlipPackage The packingSlipPackage to be updated.
   * @param connect Indicates whether the packingSlipPackage should be connected to the user on update.
   * @returns {Promise<string>} A promise that resolves to the ID as a string when the packingSlipPackage is updated.
   */
  update: (packingSlipPackage: PackingSlipPackage) => Promise<string>

  /**
    * Searches for packingSlipPackages in the external source.
    * @param query The query to be used for searching.
    * @returns {Promise<void>} A promise that resolves with an array of packingSlipPackages.
    */
  search: (query: string, pagination: Pagination, force?: boolean) => Promise<PackingSlipPackage[]>
}
