package game_modus_localisation_operations

import (
	game_modus_localisation "github.com/bakeable/bkry/internal/server/models/entities/game_modus_localisation"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAll(repository repo.IRepository, gameModusID string) []game_modus_localisation.GameModusLocalisation {
	// Get GameModusLocalisations
	entities, err := repository.GetAllGameModusLocalisations(gameModusID)
	if err != nil {
		panic(err)
	}

	// Process GameModusLocalisation entities
	entities = afterGetAll(gameModusID, entities)

	// Return GameModusLocalisations
	return entities
}