package examination_task_operations

import (
	examination_task "github.com/bakeable/bkry/data/entities/examination_task"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Query(repository repo.IRepository, queries []datastore.Query, pagination datastore.Pagination) []examination_task.ExaminationTask {
	// Get ExaminationTasks
	entities, err := repository.QueryExaminationTasks(queries, pagination)
	if err != nil {
		panic(err)
	}

	// Process ExaminationTask entities
	entities = afterQuery(entities)

	// Return ExaminationTasks
	return entities
}