package question_bundle_localisation_operations

import (
	question_bundle_localisation "github.com/bakeable/bkry/internal/server/models/entities/question_bundle_localisation"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Save(repository repo.IRepository, questionBundleID string, entity question_bundle_localisation.QuestionBundleLocalisation, editorID *string) *string {
	// Preprocess QuestionBundleLocalisation
	entity = beforeSave(questionBundleID, entity, editorID)

	// Save QuestionBundleLocalisation
	id, err := repository.SaveQuestionBundleLocalisation(questionBundleID, entity, editorID)
	if err != nil {
		panic(err)
	}

	// Set ID on entity
	entity.ID = id

	// Take care of business logic after saving QuestionBundleLocalisation entity
	afterSave(questionBundleID, entity, editorID)

	// Return QuestionBundleLocalisation
	return &id
}