package cloud_function_controllers

import (
	"net/http"
	cloud_function_operations "github.com/bakeable/bkry/internal/server/transport/operations/cloud_function"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func GetAll(c *gin.Context) {

	// Get cloud_function
	entities := cloud_function_operations.GetAll(getRepository())

	// Return cloud_function
	c.JSON(http.StatusOK, gin.H{ "items": entities})

}