package printing_order_supplier_operations

import (
	printing_order_supplier "github.com/bakeable/bkry/data/entities/printing_order_supplier"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAllPaginated(repository repo.IRepository, pagination datastore.Pagination) ([]printing_order_supplier.PrintingOrderSupplier, datastore.Pagination) {
	// Get PrintingOrderSuppliers
	entities, pagination, err := repository.GetAllPrintingOrderSuppliersPaginated(pagination)
	if err != nil {
		panic(err)
	}

	// Process PrintingOrderSupplier entities
	entities = afterGetAllPaginated(entities, pagination.PageSize, pagination.PageNumber, pagination.OrderBy, pagination.Ascending)

	// Return PrintingOrderSuppliers
	return entities, pagination
}