package printing_order_supplier_operations

import (
	printing_order_supplier "github.com/bakeable/bkry/data/entities/printing_order_supplier"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Query(repository repo.IRepository, queries []datastore.Query, pagination datastore.Pagination) []printing_order_supplier.PrintingOrderSupplier {
	// Get PrintingOrderSuppliers
	entities, err := repository.QueryPrintingOrderSuppliers(queries, pagination)
	if err != nil {
		panic(err)
	}

	// Process PrintingOrderSupplier entities
	entities = afterQuery(entities)

	// Return PrintingOrderSuppliers
	return entities
}