package game_modus_localisation_controllers

import (
	"net/http"
	game_modus_localisation_operations "github.com/bakeable/bkry/internal/server/transport/operations/game_modus_localisation"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func GetAll(c *gin.Context) {

	// Get gameModus ID from URL
	gameModusID := c.Param("gameModusID")

	// Get game_modus_localisation
	entities := game_modus_localisation_operations.GetAll(getRepository(), gameModusID)

	// Return game_modus_localisation
	c.JSON(http.StatusOK, gin.H{ "items": entities})

}