import { type JSONData } from '../../base_classes/dto.d'
import type IDto from '../../base_classes/dto.d'
import { type Margin } from '../../general/margin'
import { type PriceLayer } from '../price_layer'

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////


// Types
export type ProductStatus = "concept" | "ready"

// Interfaces
export interface IExamination {
    // Whether the examination is a priority
      priority: boolean
    // The priority score of the examination
      priorityScore: number
    // External properties of the examination
      properties: Record<string, any>
    // The timeout of the examination
      timeout: number
}
export interface IMargins {
    // The direct margin
      direct: Margin
    // The premium margin
      premium: Margin
    // The standard margin
      standard: Margin
}

// Data Transfer Object Interface
export interface IProductDto extends IDto {
  /// ///////////////////////////////////////
  /// //////// PRIVATE VARIABLES ////////////
  /// ///////////////////////////////////////
  /**
   * The path to the corresponding API endpoint with variables marked as {?}
   */
  _path: string

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////

    // The Products default attributes
    attributeMap: Record<string, any>

    // The Products default attributes
    attributes: string[]

    // The product's categories
    categories: string[]

    // Whether the product has a configurable price
    configurablePrice: boolean

    // The product's examination
    examination: IExamination

    // Whether the product needs to be examined
    examine: boolean

    // The product's family
    family: string

    // The kind of the object
    _kind: string

    // The product's defalt margin
    margin: Margin

    // The product's margins
    margins: IMargins

    // The product's name
    name: string

    // The products attribute options
    options: string[]

    // Whether all price configurations have been generated
    priceConfigurationsGenerated: boolean

    // Whether all price configurations have been generated
    priceConfigurationGeneratedTimestamp: number

    // The price layers ID's
    priceLayerIds: string[]

    // The price layers determining the product price
    priceLayers: PriceLayer[]

    // External properties of the product
    properties: Record<string, any>

    // The product's SKU
    sku: string

    // The product's status
    status: ProductStatus

    // The ordering index of the status
    statusIndex: number

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////

  /**
   * Set the Product's properties
   */
  set: (data: JSONData) => void
}
