package category_operations

import (
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Delete(repository repo.IRepository, categoryID string) {
	// Perform before delete actions for Category entity
	beforeDelete(categoryID)

	// Delete Category
	err := repository.DeleteCategory(categoryID)
	if err != nil {
		panic(err)
	}

	// Perform after delete actions for Category entity
	afterDelete(categoryID)
}