package category_operations

import (
	category "github.com/bakeable/bkry/internal/server/models/entities/category"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Get(repository repo.IRepository, categoryID string) category.Category {
	// Get Category
	entity, err := repository.GetCategory(categoryID)
	if err != nil {
		panic(err)
	}

	// Process Category entity
	entity = afterGet(categoryID, entity)

	// Return Category
	return entity
}