package category_operations

import (
	category "github.com/bakeable/bkry/internal/server/models/entities/category"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAll(repository repo.IRepository, ) []category.Category {
	// Get Categories
	entities, err := repository.GetAllCategories()
	if err != nil {
		panic(err)
	}

	// Process Category entities
	entities = afterGetAll(entities)

	// Return Categories
	return entities
}