package category_operations

import (
	category "github.com/bakeable/bkry/internal/server/models/entities/category"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Save(repository repo.IRepository, entity category.Category, editorID *string) *string {
	// Preprocess Category
	entity = beforeSave(entity, editorID)

	// Save Category
	id, err := repository.SaveCategory(entity, editorID)
	if err != nil {
		panic(err)
	}

	// Set ID on entity
	entity.ID = id

	// Take care of business logic after saving Category entity
	afterSave(entity, editorID)

	// Return Category
	return &id
}