import type IDtoList from '../../base_classes/dto_list'
import { type JSONData } from '../../base_classes/dto.d';
import { type Pagination } from '../../base_classes/dto_list.d';
import { type PriceLayer } from '.';


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

export interface IPriceLayerList extends IDtoList {

    /// ///////////////////////////////////////
    /// //////// PRIVATE VARIABLES ////////////
    /// ///////////////////////////////////////

    /// ///////////////////////////////////////
    /// ///////// PUBLIC VARIABLES ////////////
    /// ///////////////////////////////////////

    /// ///////////////////////////////////////
    /// ////////////// METHODS ////////////////
    /// ///////////////////////////////////////

    /**
     * Build an instance of type PriceLayer from a JSON object
     * @param pathVars - The path variables
     * @returns A promise of PriceLayer[]
     */
    _buildInstance: (data: JSONData) => PriceLayer

    /**
     * Get all PriceLayers
     * @param pathVars - The path variables
     * @returns A promise of PriceLayer[]
     */
    getAll: (pathVars?: string | string[] | Record<string, string>) => Promise<PriceLayer[]>

    /**
     * Get paginated PriceLayers
     * @param pathVars - The path variables
     * @param pagination - The pagination object
     * @returns A promise of {
     *      items: PriceLayer[],
     *      pagination: Pagination,
     *  }
     */
    getPaginated: (pathVars: string | string[], pagination: Pagination) => Promise<{
        items: PriceLayer[],
        pagination: Pagination,
    }>

    /**
     * Search PriceLayers
     * @param query - The search query
     * @returns A promise of PriceLayer[]
     */
    search: (query: string, pagination?: Pagination) => Promise<PriceLayer[]>
}