package attribute_operations

import (
	attribute "github.com/bakeable/bkry/internal/server/models/entities/attribute"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Find(repository repo.IRepository, queries []datastore.Query) attribute.Attribute {
	// Find Attribute
	entity, err := repository.FindAttribute(queries)
	if err != nil {
		panic(err)
	}

	// Process Attribute entity
	entity = afterFind(entity)

	// Return Attribute
	return entity
}