package attribute_operations

import (
	attribute "github.com/bakeable/bkry/internal/server/models/entities/attribute"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAll(repository repo.IRepository, ) []attribute.Attribute {
	// Get Attributes
	entities, err := repository.GetAllAttributes()
	if err != nil {
		panic(err)
	}

	// Process Attribute entities
	entities = afterGetAll(entities)

	// Return Attributes
	return entities
}