package price_layer_controllers

import (
	"net/http"
	price_layer_operations "github.com/bakeable/bkry/data/entities/price_layer/operations"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func GetAll(c *gin.Context) {

	// Get price_layer
	entities := price_layer_operations.GetAll(getRepository())

	// Return price_layer
	c.JSON(http.StatusOK, gin.H{ "items": entities})

}