import { type JSONData } from '../../base_classes/dto.d'
import type IDto from '../../base_classes/dto.d'

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////


// Types

// Interfaces
export interface IMargin {
    // The amount of margin
      amount: number
    // The percentage of margin
      percentage: number
    // The type of percentage
      percentageType: string
    // Whether the margin is staggered
      staggered: boolean
    // The type of margin
      type: string
    // The values of the margin
      values: any[]
}

// Data Transfer Object Interface
export interface IAirlineOrderDto extends IDto {
  /// ///////////////////////////////////////
  /// //////// PRIVATE VARIABLES ////////////
  /// ///////////////////////////////////////
  /**
   * The path to the corresponding API endpoint with variables marked as {?}
   */
  _path: string

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////

    // The AFAS order number of the airline order
    afasOrderNumber: string

    // The number of colors of the airline order
    colors: number

    // The ID of the customer associated with the airline order
    customerId: string

    // The name of the customer associated with the airline order
    customerName: string

    // The date of the airline order
    date: string

    // The delivery address of the order
    deliveryAddress: string

    // The description of the airline order
    description: string

    // The number of dividers of the airline order
    dividers: number

    // The unique identifier of the airline order
    guid: string

    // The ID of the supplier associated with the airline order
    supplierId: string

    // Whether the airline order has already been grouped
    isGrouped: boolean

    // The kind of the object
    _kind: string

    // The order margin
    margin: IMargin

    // The number of the airline order
    number: string

    // The order number of the airline order
    orderNumber: string

    // The original total costs (when separately ordered)
    originalTotalCosts: number

    // The original unit costs (when separately ordered)
    originalUnitCosts: number

    // The serial number of the airline order
    serialNumber: number

    // The SKU (Stock Keeping Unit) of the airline order
    sku: string

    // The status of the airline order
    status: string

    // The total costs of the airline order
    totalCosts: number

    // The unit costs of the airline order
    unitCosts: number

    // The unit type of the airline order
    unitType: string

    // The number of units in the airline order
    units: number

    // The warehouse of the airline order
    warehouse: string

    // The width of the ordered airline foil
    width: number

    // The width unit type of the ordered airline foil
    widthUnitType: number

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////

  /**
   * Set the AirlineOrder's properties
   */
  set: (data: JSONData) => void
}
