
import { type DocRef } from '../../general/docref'
import { AuditInfo } from '../../general/auditinfo'

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////


// ProductPackageLocalisation Interface
export interface ProductPackageLocalisation {
  // The ID of the ProductPackageLocalisation
  id: string

  // The audit information on the creation of the ProductPackageLocalisation
  created: AuditInfo

  // The audit information on the modification of the ProductPackageLocalisation
  modified: AuditInfo

  // Optional further description of the contents of the package
  description: string

  // The default language code for the package
  language_id: string

  // Reference to the media associated with the package
  media: DocRef

  // The ID of the parent entity for which this is the child document
  product_package_id: string

  // The subtitle of the package
  subtitle: string

  // The title of the package
  title: string
}



// Property Interfaces
