import { type ProductPackageLocalisation } from './interface.gen'
import { type Store } from 'pinia'
import { Pagination } from "../../general/pagination"
import { Query } from "../../general/query"

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Represents the state of the productPackageLocalisation store.
 */
export interface ProductPackageLocalisationStoreState {
  /**
   * The currently active productPackageLocalisation ID
   */
  activeID: string | null

  /**
   * A cache of productPackageLocalisations.
   */
  cache: Record<string, {
    ids: string[]
    pagination: Pagination
    retrievalTimestamp: number
  }>

  /**
   * The list of productPackageLocalisations.
   */
  list: ProductPackageLocalisation[]

  /**
   * The retrieval timestamp
   */
  retrievalTimestamp: number

  /**
   * A key that is updated to force the update of the entity.
   */
  updateKey: number

  /**
   * A timeout before emitting a store update event.
   */
  storeUpdateTimeout: window.Timeout | null
}

/**
 * Represents an ProductPackageLocalisationStore that extends the Store interface.
 */
export interface ProductPackageLocalisationStore extends ProductPackageLocalisationStoreState, Store {
  /**
   * The currently active productPackageLocalisation
   */
  active: ProductPackageLocalisation | null

  /**
   * Adds an productPackageLocalisation to the local ProductPackageLocalisationStore.
   * @param productPackageLocalisation The productPackageLocalisation to be added.
   */
  add: (productPackageLocalisation: ProductPackageLocalisation) => void

  /**
   * Checks whether the list contains an instance with the provided ID.
   * @param id The id to be searched.
   * @returns {boolean} A boolean indicating whether the list contains the ID.
   */
  contains: (id: string) => boolean

  /**
   * Creates a new productPackageLocalisation in the external database and updates the store.
   * @param productPackageLocalisation The productPackageLocalisation to be created.
   * @returns {Promise<ProductPackageLocalisation>} A promise that resolves with the created productPackageLocalisation.
   */
  create: (productPackageId: string, productPackageLocalisation: ProductPackageLocalisation) => Promise<ProductPackageLocalisation>

  /**
   * Deletes an productPackageLocalisation from the ProductPackageLocalisationStore from the external database.
   * @param productPackageLocalisation The productPackageLocalisation to be deleted.
   * @returns {Promise<void>} A promise that resolves when the productPackageLocalisation is deleted.
   */
  delete: (productPackageLocalisation: ProductPackageLocalisation) => Promise<void>

  /**
   * Deletes an productPackageLocalisation by ID from the ProductPackageLocalisationStore from the external database.
   * @param id The ID to be deleted.
   * @returns {Promise<void>} A promise that resolves when the productPackageLocalisation is deleted.
   */
  deleteById: (id: string) => Promise<void>

  /**
   * Fire a form update event for the ProductPackageLocalisation.
   */
  emitFormUpdateEvent: (id: string) => void

  /**
   * Fire a store update event for all ProductPackageLocalisations.
   */
  emitStoreUpdateEvent: () => void

  /**
   * Get a ProductPackageLocalisation from the local ProductPackageLocalisationStore.
   * @returns { ProductPackageLocalisation | null } The productPackageLocalisation.
   */
  get: (id: string) => ProductPackageLocalisation | null

  /**
   * Queries productPackageLocalisations from the external source
   * @param queries The queries to be used for filtering.
   * @param pagination The pagination to be used for the query.
   * @param force Whether to force the query to the external source.
   * @returns {Promise<{ pagination: Pagination; items: ProductPackageLocalisation[] }>} A promise that resolves with queried productPackageLocalisations.
   */
  query: (productPackageId: string, queries: Query[], pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: ProductPackageLocalisation[]
  }>

  /**
   * Reinserts an productPackageLocalisation to the ProductPackageLocalisationStore list.
   * @param productPackageLocalisation The productPackageLocalisation to be reinserted.
   * @returns {void}
   */
  reinsert: (productPackageLocalisation: ProductPackageLocalisation) => void

  /**
   * Removes an productPackageLocalisation from the local ProductPackageLocalisationStore.
   * @param productPackageLocalisation The productPackageLocalisation to be removed.
   * @returns {void}
   */
  remove: ({ id }: ProductPackageLocalisation) => void

  /**
   * Determines whether a refresh of the store is required
   */
  refreshRequired: boolean

  /**
   * Retrieves a single ProductPackageLocalisation from either the local ProductPackageLocalisationStore or external source, if forced or required.
   * @param id The ID of the ProductPackageLocalisation to retrieve.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<ProductPackageLocalisation>} A promise that resolves when the productPackageLocalisation is set as active.
   */
  retrieve: (productPackageId: string, id: string, force?: boolean) => Promise<ProductPackageLocalisation>

  /**
   * Retrieves all productPackageLocalisations from the ProductPackageLocalisationStore or external source, depending if a refresh is required.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<{ active: string | null; items: ProductPackageLocalisation[] }>} A promise that resolves with an array of productPackageLocalisations.
   */
  retrieveAll: (productPackageId: string, force?: boolean) => Promise<{
    active: string | null
    items: ProductPackageLocalisation[]
  }>

  /**
   * Retrieves productPackageLocalisations paginated from the external source.
   * @param pagination The pagination to be used for the query.
   * @param force Whether to force the query to the external source.
   * @returns {Promise<{ pagination: Pagination; items: ProductPackageLocalisation[] }>} A promise that resolves with paginated productPackageLocalisations.
   */
  retrievePaginated: (productPackageId: string, pagination?: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: ProductPackageLocalisation[]
  }>

  /**
   * Searches for productPackageLocalisations in the external source.
   * @param search The search query string.
   * @param pagination The pagination to be used for the search.
   * @param force Whether to force the search to the external source.
   * @returns {Promise<{ pagination: Pagination; items: ProductPackageLocalisation[] }>} A promise that resolves with search results.
   */
  search: (productPackageId: string, search: string, pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: ProductPackageLocalisation[]
  }>

  /**
   * Update an productPackageLocalisation from the ProductPackageLocalisationStore in the external database.
   * @param productPackageLocalisation The productPackageLocalisation to be updated.
   * @returns {Promise<ProductPackageLocalisation>} A promise that resolves with the updated productPackageLocalisation.
   */
  update: (productPackageLocalisation: ProductPackageLocalisation) => Promise<ProductPackageLocalisation>
}
