import { CloudFunction } from './entity'
import DtoList from '../../base_classes/dto_list'
import { type JSONData } from '../../base_classes/dto.d'
import { type ICloudFunctionList } from './list.gen.d'
import { type Pagination, type Query } from '../../base_classes/dto_list.d'


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////


export class CloudFunctionList 
extends DtoList 
implements ICloudFunctionList 
{
  /// ///////////////////////////////////////
  /// //////// PRIVATE VARIABLES ////////////
  /// ///////////////////////////////////////
  _path = '/cloud_function'
  _kind = 'CloudFunction'
  _name = 'cloud_function'

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////
  list: CloudFunction[] = []
  queriedList: CloudFunction[] = []

  /// ///////////////////////////////////////
  /// ////////////// METHODS ////////////////
  /// ///////////////////////////////////////

  _buildInstance(data: JSONData): CloudFunction {
    return new CloudFunction([], data)
  }

  override async getAll(
    pathVars?: string | string[] | Record<string, string>
  ): Promise<CloudFunction[]> {
    return (await super.getAll(pathVars)) as CloudFunction[]
  }

  override async getPaginated(
    pathVars: string | string[],
    pagination: Pagination
  ): Promise<{
    items: CloudFunction[],
    pagination: Pagination,
  }> {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    return (await super.getPaginated(pathVars, pagination)) as {
      items: CloudFunction[],
      pagination: Pagination,
    }
  }

  override async query(queries: Query[], pagination?: Pagination): Promise<CloudFunction[]> {
    return (await super.query(queries, pagination)) as CloudFunction[];
  }

  override async search(query: string, pagination?: Pagination): Promise<CloudFunction[]> {
    return (await super.search(query, pagination)) as CloudFunction[];
  }
}
