package question_context_localisation_operations

import (
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Delete(repository repo.IRepository, questionContextID string, questionContextLocalisationID string) {
	// Perform before delete actions for QuestionContextLocalisation entity
	beforeDelete(questionContextID, questionContextLocalisationID)

	// Delete QuestionContextLocalisation
	err := repository.DeleteQuestionContextLocalisation(questionContextID, questionContextLocalisationID)
	if err != nil {
		panic(err)
	}

	// Perform after delete actions for QuestionContextLocalisation entity
	afterDelete(questionContextID, questionContextLocalisationID)
}