package question_context_localisation_operations

import (
	question_context_localisation "github.com/bakeable/bkry/internal/server/models/entities/question_context_localisation"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
	"github.com/bakeable/bkry/internal/server/database"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func QueryGroup(repository repo.IRepository, queries []database.Query) []question_context_localisation.QuestionContextLocalisation {
	// Query QuestionContextLocalisations group
	entities, err := repository.QueryQuestionContextLocalisationsGroup(queries)
	if err != nil {
		panic(err)
	}

	// Process QuestionContextLocalisation entities
	entities = afterQueryGroup(entities)

	// Return QuestionContextLocalisations
	return entities
}