package author_operations

import (
	author "github.com/bakeable/bkry/internal/server/models/entities/author"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Get(repository repo.IRepository, authorID string) author.Author {
	// Get Author
	entity, err := repository.GetAuthor(authorID)
	if err != nil {
		panic(err)
	}

	// Process Author entity
	entity = afterGet(authorID, entity)

	// Return Author
	return entity
}