package product_operations

import (
	repo "github.com/bakeable/bkry/data/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Delete(repository repo.IRepository, productID string) {
	// Perform before delete actions for Product entity
	beforeDelete(productID)

	// Delete Product
	err := repository.DeleteProduct(productID)
	if err != nil {
		panic(err)
	}

	// Perform after delete actions for Product entity
	afterDelete(productID)
}