import type IDtoList from '../../base_classes/dto_list'
import { type JSONData } from '../../base_classes/dto.d';
import { type Pagination } from '../../base_classes/dto_list.d';
import { type Product } from '.';


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

export interface IProductList extends IDtoList {

    /// ///////////////////////////////////////
    /// //////// PRIVATE VARIABLES ////////////
    /// ///////////////////////////////////////

    /// ///////////////////////////////////////
    /// ///////// PUBLIC VARIABLES ////////////
    /// ///////////////////////////////////////

    /// ///////////////////////////////////////
    /// ////////////// METHODS ////////////////
    /// ///////////////////////////////////////

    /**
     * Build an instance of type Product from a JSON object
     * @param pathVars - The path variables
     * @returns A promise of Product[]
     */
    _buildInstance: (data: JSONData) => Product

    /**
     * Get all Products
     * @param pathVars - The path variables
     * @returns A promise of Product[]
     */
    getAll: (pathVars?: string | string[] | Record<string, string>) => Promise<Product[]>

    /**
     * Get paginated Products
     * @param pathVars - The path variables
     * @param pagination - The pagination object
     * @returns A promise of {
     *      items: Product[],
     *      pagination: Pagination,
     *  }
     */
    getPaginated: (pathVars: string | string[], pagination: Pagination) => Promise<{
        items: Product[],
        pagination: Pagination,
    }>

    /**
     * Search Products
     * @param query - The search query
     * @returns A promise of Product[]
     */
    search: (query: string, pagination?: Pagination) => Promise<Product[]>
}