package examination_property_operations

import (
	examination_property "github.com/bakeable/bkry/internal/server/models/entities/examination_property"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Find(repository repo.IRepository, queries []datastore.Query) examination_property.ExaminationProperty {
	// Find ExaminationProperty
	entity, err := repository.FindExaminationProperty(queries)
	if err != nil {
		panic(err)
	}

	// Process ExaminationProperty entity
	entity = afterFind(entity)

	// Return ExaminationProperty
	return entity
}