package airline_order_group_controllers

import (
	"net/http"
	airline_order_group_operations "github.com/bakeable/bkry/internal/server/transport/operations/airline_order_group"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func Get(c *gin.Context) {

	// Get airline_order_group ID from URL
	airlineOrderGroupID := c.Param("airlineOrderGroupID")

	// Get airline_order_group
	entity := airline_order_group_operations.Get(getRepository(), airlineOrderGroupID)

	// Return airline_order_group
	c.JSON(http.StatusOK, gin.H{ "item": entity })
}
