package game_modus_operations

import (
	game_modus "github.com/bakeable/bkry/internal/server/models/entities/game_modus"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
	"github.com/bakeable/bkry/internal/server/database"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAllPaginated(repository repo.IRepository, pagination database.Pagination) ([]game_modus.GameModus, database.Pagination) {
	// Get GameModus
	entities, pagination, err := repository.GetAllGameModusPaginated(pagination)
	if err != nil {
		panic(err)
	}

	// Process GameModus entities
	entities = afterGetAllPaginated(entities, pagination.PageSize, pagination.PageNumber, pagination.OrderBy, pagination.Ascending)

	// Return GameModus
	return entities, pagination
}