import { type GameModus } from './interface.gen'
import { type Store } from 'pinia'
import { Pagination } from "../../general/pagination"
import { Query } from "../../general/query"

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Represents the state of the gameModus store.
 */
export interface GameModusStoreState {
  /**
   * The currently active gameModus ID
   */
  activeID: string | null

  /**
   * A cache of gameModuss.
   */
  cache: Record<string, {
    ids: string[]
    pagination: Pagination
    retrievalTimestamp: number
  }>

  /**
   * The list of gameModuss.
   */
  list: GameModus[]

  /**
   * The retrieval timestamp
   */
  retrievalTimestamp: number

  /**
   * A key that is updated to force the update of the entity.
   */
  updateKey: number

  /**
   * A timeout before emitting a store update event.
   */
  storeUpdateTimeout: window.Timeout | null
}

/**
 * Represents an GameModusStore that extends the Store interface.
 */
export interface GameModusStore extends GameModusStoreState, Store {
  /**
   * The currently active gameModus
   */
  active: GameModus | null

  /**
   * Adds an gameModus to the local GameModusStore.
   * @param gameModus The gameModus to be added.
   */
  add: (gameModus: GameModus) => void

  /**
   * Checks whether the list contains an instance with the provided ID.
   * @param id The id to be searched.
   * @returns {boolean} A boolean indicating whether the list contains the ID.
   */
  contains: (id: string) => boolean

  /**
   * Creates a new gameModus in the external database and updates the store.
   * @param gameModus The gameModus to be created.
   * @returns {Promise<GameModus>} A promise that resolves with the created gameModus.
   */
  create: (gameModus: GameModus) => Promise<GameModus>

  /**
   * Deletes an gameModus from the GameModusStore from the external database.
   * @param gameModus The gameModus to be deleted.
   * @returns {Promise<void>} A promise that resolves when the gameModus is deleted.
   */
  delete: (gameModus: GameModus) => Promise<void>

  /**
   * Deletes an gameModus by ID from the GameModusStore from the external database.
   * @param id The ID to be deleted.
   * @returns {Promise<void>} A promise that resolves when the gameModus is deleted.
   */
  deleteById: (id: string) => Promise<void>

  /**
   * Fire a form update event for the GameModus.
   */
  emitFormUpdateEvent: (id: string) => void

  /**
   * Fire a store update event for all GameModuss.
   */
  emitStoreUpdateEvent: () => void

  /**
   * Get a GameModus from the local GameModusStore.
   * @returns { GameModus | null } The gameModus.
   */
  get: (id: string) => GameModus | null

  /**
   * Queries gameModuss from the external source
   * @param queries The queries to be used for filtering.
   * @param pagination The pagination to be used for the query.
   * @param force Whether to force the query to the external source.
   * @returns {Promise<{ pagination: Pagination; items: GameModus[] }>} A promise that resolves with queried gameModuss.
   */
  query: (queries: Query[], pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: GameModus[]
  }>

  /**
   * Reinserts an gameModus to the GameModusStore list.
   * @param gameModus The gameModus to be reinserted.
   * @returns {void}
   */
  reinsert: (gameModus: GameModus) => void

  /**
   * Removes an gameModus from the local GameModusStore.
   * @param gameModus The gameModus to be removed.
   * @returns {void}
   */
  remove: ({ id }: GameModus) => void

  /**
   * Determines whether a refresh of the store is required
   */
  refreshRequired: boolean

  /**
   * Retrieves a single GameModus from either the local GameModusStore or external source, if forced or required.
   * @param id The ID of the GameModus to retrieve.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<GameModus>} A promise that resolves when the gameModus is set as active.
   */
  retrieve: (id: string, force?: boolean) => Promise<GameModus>

  /**
   * Retrieves all gameModuss from the GameModusStore or external source, depending if a refresh is required.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<{ active: string | null; items: GameModus[] }>} A promise that resolves with an array of gameModuss.
   */
  retrieveAll: (force?: boolean) => Promise<{
    active: string | null
    items: GameModus[]
  }>

  /**
   * Retrieves gameModuss paginated from the external source.
   * @param pagination The pagination to be used for the query.
   * @param force Whether to force the query to the external source.
   * @returns {Promise<{ pagination: Pagination; items: GameModus[] }>} A promise that resolves with paginated gameModuss.
   */
  retrievePaginated: (pagination?: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: GameModus[]
  }>

  /**
   * Searches for gameModuss in the external source.
   * @param search The search query string.
   * @param pagination The pagination to be used for the search.
   * @param force Whether to force the search to the external source.
   * @returns {Promise<{ pagination: Pagination; items: GameModus[] }>} A promise that resolves with search results.
   */
  search: (search: string, pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: GameModus[]
  }>

  /**
   * Update an gameModus from the GameModusStore in the external database.
   * @param gameModus The gameModus to be updated.
   * @returns {Promise<GameModus>} A promise that resolves with the updated gameModus.
   */
  update: (gameModus: GameModus) => Promise<GameModus>
}
