import { type AirlinePricing } from './entity'
import { type Store } from 'pinia'


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Represents the state of the airlinePricing store.
 */
export interface AirlinePricingStoreState {
  /**
   * The currently active airlinePricing ID
   */
  activeID: string | null

  /**
   * A cache of airlinePricings.
   */
  cache: Record<string, {
    ids: string[]
    pagination: Pagination
    retrievalTimestamp: number
  }>

  /**
   * The list of airlinePricings.
   */
  list: AirlinePricing[]

  /**
   * The retrieval timestamp
   */
  retrievalTimestamp: number

  /**
   * A key that is updated to force the update of the entity.
   */
  updateKey: number

  /**
   * A timeout before emitting a store update event.
   */
  storeUpdateTimeout: window.Timeout | null
}

/**
 * Represents an AirlinePricingStore that extends the Store interface.
 */
export interface AirlinePricingStore extends AirlinePricingStoreState, Store {
  /**
   * Fire a form update event for the AirlinePricing.
   */
  emitFormUpdateEvent: (id: string) => void

  /**
   * Fire a store update event for all AirlinePricing.
   */
  emitStoreUpdateEvent: () => void

  /**
   * The currently active airlinePricing
   */
  active: AirlinePricing

  /**
   * Adds an airlinePricing to the local AirlinePricingStore.
   * @param airlinePricing The airlinePricing to be added.
   */
  add: (airlinePricing: AirlinePricing) => void

  /**
   * Checks whether the list contains an instance with the provided ID.
   * @param id The id to be searched.
   * @returns {boolean} A boolean indicating whether the list contains the ID.
   */
  contains: (id: string) => boolean

  /**
   * Deletes an airlinePricing from the AirlinePricingStore from the external database.
   * @param airlinePricing The airlinePricing to be deleted.
   * @returns {Promise<void>} A promise that resolves when the airlinePricing is deleted.
   */
  delete: (airlinePricing: AirlinePricing) => Promise<void>

  /**
   * Deletes an airlinePricing by ID from the AirlinePricingStore from the external database.
   * @param id The ID to be deleted.
   * @returns {Promise<void>} A promise that resolves when the airlinePricing is deleted.
   */
  deleteById: (id: string) => Promise<void>

  /**
   * Get a AirlinePricing from the local AirlinePricingStore.
   * @returns { AirlinePricing | null } The airlinePricing.
   */
  get: (id: string) => AirlinePricing | null

  /**
   * Reinserts an airlinePricing to the AirlinePricingStore list.
   * @param airlinePricing The airlinePricing to be reinserted.
   * @returns {void}
   */
  reinsert: (airlinePricing: AirlinePricing) => void

  /**
   * Removes an airlinePricing from the local AirlinePricingStore.
   * @param airlinePricing The airlinePricing to be removed.
   * @returns {void}
   */
  remove: (airlinePricing: AirlinePricing) => void

  /**
   * Determines whether a refresh of the store is required
   */
  refreshRequired: boolean

  /**
   * Retrieves a single AirlinePricing from either the local AirlinePricingStore or external source, if forced or required.
    * @param id The ID of the AirlinePricing to retrieve.
    * @param force Indicates whether a refresh is forced.
   * @returns {Promise<void>} A promise that resolves when the airlinePricing is set as active.
   */
  retrieve: (id: string, force?: boolean) => Promise<AirlinePricing>

  /**
   * Retrieves all airlinePricings from the AirlinePricingStore or external source, depending if a refresh is required.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<void>} A promise that resolves with an array of airlinePricings.
   */
  retrieveAll: (force?: boolean) => Promise<{
    active: string | null
    items: AirlinePricing[]
  }>

  /**
    * Retrieves airlinePricings paginated from the external source
    * @param pagination The pagination to be used for the query.
    * @param force Whether to force the query to the external source.
    * @returns {Promise<void>} A promise that resolves with an array of airlinePricings.
    */
  retrievePaginated: (pagination?: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: AirlinePricing[]
  }>

  /**
    * Queries airlinePricings from the external source
    * @param queries The queries to be used for filtering.
    * @param pagination The pagination to be used for the query.
    * @param force Whether to force the query to the external source.
    * @returns {Promise<void>} A promise that resolves with an array of airlinePricings.
    */
  query: (queries: Query[], pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: AirlinePricing[]
  }>

  /**
   * Update an airlinePricing from the AirlinePricingStore in the external database.
   * @param airlinePricing The airlinePricing to be updated.
   * @param connect Indicates whether the airlinePricing should be connected to the user on update.
   * @returns {Promise<string>} A promise that resolves to the ID as a string when the airlinePricing is updated.
   */
  update: (airlinePricing: AirlinePricing) => Promise<string>

  /**
    * Searches for airlinePricings in the external source.
    * @param query The query to be used for searching.
    * @returns {Promise<void>} A promise that resolves with an array of airlinePricings.
    */
  search: (query: string, pagination: Pagination, force?: boolean) => Promise<AirlinePricing[]>
}
