package entities

var examinationPropertyFields = []FieldConfig{
	{
		FieldName:    "Kind",
		FieldType:    "string",
		JsonName:     "_kind",
		Description:  "The kind of the object",
		DefaultValue: "ExaminationProperty",
	},
	{
		FieldName:    "Description",
		FieldType:    "string",
		JsonName:     "description",
		Description:  "A description of the property to be examined",
		DefaultValue: "",
	},
	{
		FieldName:    "Examine",
		FieldType:    "bool",
		JsonName:     "examine",
		Description:  "Whether the property needs to be examined",
		DefaultValue: "true",
	},
	{
		FieldName:    "InputType",
		FieldType:    "ExaminationInputType",
		JsonName:     "inputType",
		Description:  "The input type of the property",
		IsEnum:       true,
		EnumValues:   []string{"value", "confirm"},
		DefaultValue: "value",
	},
	{
		FieldName:    "Instructions",
		FieldType:    "string",
		JsonName:     "instructions",
		Description:  "A set of instructions for the examiner of the property",
		DefaultValue: "",
	},
	{
		FieldName:    "Info",
		FieldType:    "map[string]interface{}",
		JsonName:     "info",
		Description:  "All additional information about the property",
	},
	{
		FieldName:    "Key",
		FieldType:    "string",
		JsonName:     "key",
		Description:  "The key of the property to be examined",
		DefaultValue: "",
	},
	{
		FieldName:    "ProductId",
		FieldType:    "string",
		JsonName:     "productId",
		Description:  "The ID of the product to which the property belongs",
		DefaultValue: "",
	},
	{
		FieldName:    "Name",
		FieldType:    "string",
		JsonName:     "name",
		Description:  "The name of the property to be examined",
		DefaultValue: "",
	},
	{
		FieldName:    "ProductSpecific",
		FieldType:    "bool",
		JsonName:     "productSpecific",
		Description:  "Whether the property is product specific",
		DefaultValue: "false",
	},
	{
		FieldName:    "Required",
		FieldType:    "bool",
		JsonName:     "required",
		Description:  "Whether it is required to observe the property",
		DefaultValue: "true",
	},
	{
		FieldName:    "Testable",
		FieldType:    "bool",
		JsonName:     "testable",
		Description:  "Whether the property is testable",
		DefaultValue: "true",
	},
	{
		FieldName:    "Type",
		FieldType:    "string",
		JsonName:     "type",
		Description:  "The type of the property to be examined",
		DefaultValue: "",
	},
	{
		FieldName:    "UnitType",
		FieldType:    "string",
		JsonName:     "unitType",
		Description:  "The unit type of the property to be examined",
		DefaultValue: "",
	},
	{
		FieldName:    "AcceptanceRegion",
		FieldType:    "AcceptanceRegion",
		JsonName:     "acceptanceRegion",
		Description:  "The acceptance region of the property",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName:    "Max",
				FieldType:    "float64",
				JsonName:     "max",
				Description:  "The maximum value of the acceptance region",
				DefaultValue: "0.0",
			},
			{
				FieldName:    "Min",
				FieldType:    "float64",
				JsonName:     "min",
				Description:  "The minimum value of the acceptance region",
				DefaultValue: "0.0",
			},
			{
				FieldName:    "Symmetric",
				FieldType:    "bool",
				JsonName:     "symmetric",
				Description:  "Whether the acceptance region is symmetric",
				DefaultValue: "false",
			},
			{
				FieldName:    "Type",
				FieldType:    "string",
				JsonName:     "type",
				Description:  "The type of the acceptance region",
				DefaultValue: "",
			},
			{
				FieldName:    "Value",
				FieldType:    "float64",
				JsonName:     "value",
				Description:  "The value of the acceptance region",
				DefaultValue: "0.0",
			},
		},
	},
}
