package entities

var priceConfigurationFields = []FieldConfig{
	{
		FieldName: "Kind",
		FieldType: "string",
		JsonName: "_kind",
		Description: "The kind of the object",
		DefaultValue: "PriceConfiguration",
	},
	{
		FieldName: "AdditionalCosts",
		FieldType: "float64",
		JsonName: "additional_costs",
		Description: "The additional costs",
		DefaultValue: "0",
	},
	{
		FieldName: "Currency",
		FieldType: "string",
		JsonName: "currency",
		Description: "The currency used in the response",
		DefaultValue: "EUR",
	},
	{
		FieldName: "FinalPrice",
		FieldType: "float64",
		JsonName: "final_price",
		Description: "The final price",
		DefaultValue: "0",
	},
	{
		FieldName: "FixedCosts",
		FieldType: "float64",
		JsonName: "fixed_costs",
		Description: "The fixed costs",
		DefaultValue: "0",
	},
	{
		FieldName: "MarginAmount",
		FieldType: "float64",
		JsonName: "margin_amount",
		Description: "The margin amount",
		DefaultValue: "0",
	},
	{
		FieldName: "MarginPercentage",
		FieldType: "float64",
		JsonName: "margin_percentage",
		Description: "The margin percentage",
		DefaultValue: "0",
	},
	{
		FieldName: "ProductId",
		FieldType: "string",
		JsonName: "product_id",
		Description: "The priceConfiguration's corresponding product ID",
		DefaultValue: "",
	},
	{
		FieldName: "Sku",
		FieldType: "string",
		JsonName: "sku",
		Description: "The priceConfiguration's corresponding product SKU",
		DefaultValue: "",
	},
	{
		FieldName: "TotalCosts",
		FieldType: "float64",
		JsonName: "total_costs",
		Description: "The total costs",
		DefaultValue: "0",
	},
	{
		FieldName: "Units",
		FieldType: "int",
		JsonName: "units",
		Description: "The number of units",
		DefaultValue: "0",
	},
	{
		FieldName: "UnitCosts",
		FieldType: "float64",
		JsonName: "unit_costs",
		Description: "The costs associated with a single unit",
		DefaultValue: "0",
	},
	{
		FieldName: "UnitMargin",
		FieldType: "float64",
		JsonName: "unit_margin",
		Description: "The costs associated with a single unit",
		DefaultValue: "0",
	},
	{
		FieldName: "VariableCosts",
		FieldType: "float64",
		JsonName: "variable_costs",
		Description: "The costs associated with a single unit",
		DefaultValue: "0",
	},
	{
		FieldName: "Attributes",
		FieldType: "map[string]string",
		JsonName: "attributes",
		Description: "The attribute configuration for this price configuration",
		DefaultValue: "map[string]string{}",
	},
}
