package entities

var productFields = []FieldConfig{
	{
		FieldName: "Kind",
		FieldType: "string",
		JsonName: "_kind",
		Description: "The kind of the object",
		DefaultValue: "Product",
	},
	{
		FieldName: "Attributes",
		FieldType: "string",
		JsonName: "attributes",
		IsArray: true,
		Description: "The Products default attributes",
		
	},
	{
		FieldName: "AttributeMap",
		FieldType: "map[string]interface{}",
		JsonName: "attributeMap",
		Description: "The Products default attributes",
	},
	{
		FieldName: "Categories",
		FieldType: "string",
		IsArray: true,
		JsonName: "categories",
		Description: "The product's categories",
	},
	{
		FieldName: "ConfigurablePrice",
		FieldType: "bool",
		JsonName: "configurablePrice",
		Description: "Whether the product has a configurable price",
		DefaultValue: "false",
	},
	{
		FieldName: "Examine",
		FieldType: "bool",
		JsonName: "examine",
		Description: "Whether the product needs to be examined",
		DefaultValue: "false",
	},
	{
		FieldName: "Examination",
		FieldType: "Examination",
		JsonName: "examination",
		Description: "The product's examination",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName: "PriorityScore",
				FieldType: "int",
				JsonName: "priorityScore",
				Description: "The priority score of the examination",

			},
			{
				FieldName: "Priority",
				FieldType: "bool",
				JsonName: "priority",
				Description: "Whether the examination is a priority",
			},
			{
				FieldName: "Timeout",
				FieldType: "int",
				JsonName: "timeout",
				Description: "The timeout of the examination",
			},
			{
				FieldName: "Properties",
				FieldType: "map[string]interface{}",
				JsonName: "properties",
				Description: "External properties of the examination",
			},
		},
	},
	{
		FieldName: "Family",
		FieldType: "string",
		JsonName: "family",
		Description: "The product's family",
	},
	{
		FieldName: "Margin",
		FieldType: "margin.Margin",
		JsonName: "margin",
		Description: "The product's defalt margin",
	},
	{
		FieldName: "Margins",
		FieldType: "Margins",
		JsonName: "margins",
		Description: "The product's margins",
		IsChildStruct: true,
		Fields: []FieldConfig{
			{
				FieldName: "Standard",
				FieldType: "margin.Margin",
				JsonName: "standard",
				Description: "The standard margin",
			},
			{
				FieldName: "Premium",
				FieldType: "margin.Margin",
				JsonName: "premium",
				Description: "The premium margin",
			},
			{
				FieldName: "Direct",
				FieldType: "margin.Margin",
				JsonName: "direct",
				Description: "The direct margin",
			},
		},
	},
	{
		FieldName: "Name",
		FieldType: "string",
		JsonName: "name",
		Description: "The product's name",
		DefaultValue: "",
	},
	{
		FieldName: "Options",
		FieldType: "string",
		IsArray: true,
		JsonName: "options",
		Description: "The products attribute options",
		
	},
	{
		FieldName: "PriceConfigurationGenerated",
		FieldType: "bool",
		JsonName: "priceConfigurationsGenerated",
		Description: "Whether all price configurations have been generated",
	},
	{
		FieldName: "PriceConfigurationGeneratedTimestamp",
		FieldType: "int",
		JsonName: "priceConfigurationGeneratedTimestamp",
		Description: "Whether all price configurations have been generated",
		DefaultValue: "0",
	},
	{
		FieldName: "PriceLayerIDs",
		FieldType: "string",
		JsonName: "priceLayerIds",
		Description: "The price layers ID's",
		IsArray: true,
	},
	{
		FieldName: "PriceLayers",
		FieldType: "price_layer.PriceLayer",
		JsonName: "priceLayers",
		Description: "The price layers determining the product price",
		IsArray: true,
	},
	{
		FieldName: "Properties",
		FieldType: "map[string]interface{}",
		JsonName: "properties",
		Description: "External properties of the product",
	},
	{
		FieldName: "Sku",
		FieldType: "string",
		JsonName: "sku",
		Description: "The product's SKU",
	},
	{
		FieldName: "Status",
		FieldType: "ProductStatus",
		JsonName: "status",
		Description: "The product's status",
		IsEnum: true,
		EnumValues: []string{"concept", "ready"},
		DefaultValue: "concept",
	},
	{
		FieldName: "StatusIndex",
		FieldType: "int",
		DefaultValue: "0",
		JsonName:  "statusIndex",
		Description: "The ordering index of the status",
	},
}