package entities

var userFields = []FieldConfig{
	{
		FieldName: "Email",
		FieldType: "string",
		JsonName: "email",
		Description: "The actual e-mail of the user",
	},
	{
		FieldName: "UserName",
		FieldType: "string",
		JsonName: "user_name",
		Description: "A nick-name for the user to use in games",
	},
	{
		FieldName: "Locale",
		FieldType: "Locale",
		IsChildStruct: true,
		JsonName: "locale",
		Description: "The preferred locale settings of the user",
		Fields: []FieldConfig{
			{
				FieldName: "Code",
				FieldType: "string",
				JsonName: "code",
				Description: "The preferred locale extended with accent",
				DefaultValue: "nl-NL",
			},
			{
				FieldName: "TwoDigitCode",
				FieldType: "string",
				JsonName: "two_digit_code",
				Description: "Fallback on this locale if the preferred accent is not available",
				DefaultValue: "nl",
			},
		},
	},
	{
		FieldName: "Profile",
		FieldType: "Profile",
		IsChildStruct: true,
		JsonName: "profile",
		Description: "The profile information of the user",
		Fields: []FieldConfig{
			{
				FieldName: "Prefix",
				FieldType: "string",
				JsonName: "prefix",
				Description: "The user's prefix",
			},
			{
				FieldName: "FirstName",
				FieldType: "string",
				JsonName: "first_name",
				Description: "The user's first name",
			},
			{
				FieldName: "Infix",
				FieldType: "string",
				JsonName: "infix",
				Description: "The user's infix",
			},
			{
				FieldName: "LastName",
				FieldType: "string",
				JsonName: "last_name",
				Description: "The user's last name",
			},
			{
				FieldName: "Gender",
				FieldType: "Gender",
				JsonName: "gender",
				IsEnum: true,
				EnumValues: []string{"Unknown","Male","Female"},
				DefaultValue: "Unknown",
				Description: "The user's gender",
			},
			{
				FieldName: "DateOfBirth",
				FieldType: "string",
				JsonName: "date_of_birth",
				Description: "The user's date of birth",
			},
			{
				FieldName: "IsGrownUp",
				FieldType: "bool",
				JsonName: "is_grown_up",
				Description: "Indicates whether the user is an adult",
			},
		},
	},
	{
		FieldName: "Address",
		FieldType: "Address",
		IsChildStruct: true,
		JsonName: "address",
		Description: "The address of the user",
		Fields: []FieldConfig{
			{
				FieldName: "Line1",
				FieldType: "string",
				JsonName: "line1",
				Description: "The first line of the address",
			},
			{
				FieldName: "Line2",
				FieldType: "string",
				JsonName: "line2",
				Description: "The second line of the address",
			},
			{
				FieldName: "Street",
				FieldType: "string",
				JsonName: "street",
				Description: "The street of the address",
			},
			{
				FieldName: "City",
				FieldType: "string",
				JsonName: "city",
				Description: "The city of the address",
			},
			{
				FieldName: "State",
				FieldType: "string",
				JsonName: "state",
				Description: "The state of the address",
			},
			{
				FieldName: "PostalCode",
				FieldType: "string",
				JsonName: "postal_code",
				Description: "The postal code of the address",
			},
			{
				FieldName: "CountryCode",
				FieldType: "string",
				JsonName: "country_code",
				Description: "The country code of the address",
			},
		},
	},
	{
		FieldName: "Avatar",
		FieldType: "media.Media",
		JsonName: "avatar",
		Description: "A user's avatar",
	},
	{
		FieldName: "Settings",
		FieldType: "string",
		JsonName: "settings",
		Description: "The user's settings",
	},
	{
		FieldName: "MuteSound",
		FieldType: "bool",
		JsonName: "mute_sound",
		Description: "Indicates whether the sound is muted for the user",
	},
}
