package airline_order_grouping_operations

import (
	airline_order_grouping "github.com/bakeable/bkry/data/entities/airline_order_grouping"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func QueryGroup(repository repo.IRepository, queries []datastore.Query) []airline_order_grouping.AirlineOrderGrouping {
	// Query AirlineOrderGroupings group
	entities, err := repository.QueryAirlineOrderGroupingsGroup(queries)
	if err != nil {
		panic(err)
	}

	// Process AirlineOrderGrouping entities
	entities = afterQueryGroup(entities)

	// Return AirlineOrderGroupings
	return entities
}