package price_layer_operations

import (
	price_layer "github.com/bakeable/bkry/internal/server/models/entities/price_layer"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAllPaginated(repository repo.IRepository, pagination datastore.Pagination) ([]price_layer.PriceLayer, datastore.Pagination) {
	// Get PriceLayers
	entities, pagination, err := repository.GetAllPriceLayersPaginated(pagination)
	if err != nil {
		panic(err)
	}

	// Process PriceLayer entities
	entities = afterGetAllPaginated(entities, pagination.PageSize, pagination.PageNumber, pagination.OrderBy, pagination.Ascending)

	// Return PriceLayers
	return entities, pagination
}