package price_layer_operations

import (
	price_layer "github.com/bakeable/bkry/data/entities/price_layer"
	repo "github.com/bakeable/bkry/data/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAll(repository repo.IRepository, ) []price_layer.PriceLayer {
	// Get PriceLayers
	entities, err := repository.GetAllPriceLayers()
	if err != nil {
		panic(err)
	}

	// Process PriceLayer entities
	entities = afterGetAll(entities)

	// Return PriceLayers
	return entities
}