package price_layer_operations

import (
	price_layer "github.com/bakeable/bkry/internal/server/models/entities/price_layer"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func QueryGroup(repository repo.IRepository, queries []datastore.Query) []price_layer.PriceLayer {
	// Query PriceLayers group
	entities, err := repository.QueryPriceLayersGroup(queries)
	if err != nil {
		panic(err)
	}

	// Process PriceLayer entities
	entities = afterQueryGroup(entities)

	// Return PriceLayers
	return entities
}