package price_layer_operations

import (
	price_layer "github.com/bakeable/bkry/data/entities/price_layer"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Query(repository repo.IRepository, queries []datastore.Query, pagination datastore.Pagination) []price_layer.PriceLayer {
	// Get PriceLayers
	entities, err := repository.QueryPriceLayers(queries, pagination)
	if err != nil {
		panic(err)
	}

	// Process PriceLayer entities
	entities = afterQuery(entities)

	// Return PriceLayers
	return entities
}