import { type PriceLayer } from './entity'
import { type Store } from 'pinia'


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Represents the state of the priceLayer store.
 */
export interface PriceLayerStoreState {
  /**
   * The currently active priceLayer ID
   */
  activeID: string | null

  /**
   * A cache of priceLayers.
   */
  cache: Record<string, {
    ids: string[]
    pagination: Pagination
    retrievalTimestamp: number
  }>

  /**
   * The list of priceLayers.
   */
  list: PriceLayer[]

  /**
   * The retrieval timestamp
   */
  retrievalTimestamp: number

  /**
   * A key that is updated to force the update of the entity.
   */
  updateKey: number

  /**
   * A timeout before emitting a store update event.
   */
  storeUpdateTimeout: window.Timeout | null
}

/**
 * Represents an PriceLayerStore that extends the Store interface.
 */
export interface PriceLayerStore extends PriceLayerStoreState, Store {
  /**
   * Fire a form update event for the PriceLayer.
   */
  emitFormUpdateEvent: (id: string) => void

  /**
   * Fire a store update event for all PriceLayer.
   */
  emitStoreUpdateEvent: () => void

  /**
   * The currently active priceLayer
   */
  active: PriceLayer

  /**
   * Adds an priceLayer to the local PriceLayerStore.
   * @param priceLayer The priceLayer to be added.
   */
  add: (priceLayer: PriceLayer) => void

  /**
   * Checks whether the list contains an instance with the provided ID.
   * @param id The id to be searched.
   * @returns {boolean} A boolean indicating whether the list contains the ID.
   */
  contains: (id: string) => boolean

  /**
   * Deletes an priceLayer from the PriceLayerStore from the external database.
   * @param priceLayer The priceLayer to be deleted.
   * @returns {Promise<void>} A promise that resolves when the priceLayer is deleted.
   */
  delete: (priceLayer: PriceLayer) => Promise<void>

  /**
   * Deletes an priceLayer by ID from the PriceLayerStore from the external database.
   * @param id The ID to be deleted.
   * @returns {Promise<void>} A promise that resolves when the priceLayer is deleted.
   */
  deleteById: (id: string) => Promise<void>

  /**
   * Get a PriceLayer from the local PriceLayerStore.
   * @returns { PriceLayer | null } The priceLayer.
   */
  get: (id: string) => PriceLayer | null

  /**
   * Reinserts an priceLayer to the PriceLayerStore list.
   * @param priceLayer The priceLayer to be reinserted.
   * @returns {void}
   */
  reinsert: (priceLayer: PriceLayer) => void

  /**
   * Removes an priceLayer from the local PriceLayerStore.
   * @param priceLayer The priceLayer to be removed.
   * @returns {void}
   */
  remove: (priceLayer: PriceLayer) => void

  /**
   * Determines whether a refresh of the store is required
   */
  refreshRequired: boolean

  /**
   * Retrieves a single PriceLayer from either the local PriceLayerStore or external source, if forced or required.
    * @param id The ID of the PriceLayer to retrieve.
    * @param force Indicates whether a refresh is forced.
   * @returns {Promise<void>} A promise that resolves when the priceLayer is set as active.
   */
  retrieve: (id: string, force?: boolean) => Promise<PriceLayer>

  /**
   * Retrieves all priceLayers from the PriceLayerStore or external source, depending if a refresh is required.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<void>} A promise that resolves with an array of priceLayers.
   */
  retrieveAll: (force?: boolean) => Promise<{
    active: string | null
    items: PriceLayer[]
  }>

  /**
    * Retrieves priceLayers paginated from the external source
    * @param pagination The pagination to be used for the query.
    * @param force Whether to force the query to the external source.
    * @returns {Promise<void>} A promise that resolves with an array of priceLayers.
    */
  retrievePaginated: (pagination?: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: PriceLayer[]
  }>

  /**
    * Queries priceLayers from the external source
    * @param queries The queries to be used for filtering.
    * @param pagination The pagination to be used for the query.
    * @param force Whether to force the query to the external source.
    * @returns {Promise<void>} A promise that resolves with an array of priceLayers.
    */
  query: (queries: Query[], pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: PriceLayer[]
  }>

  /**
   * Update an priceLayer from the PriceLayerStore in the external database.
   * @param priceLayer The priceLayer to be updated.
   * @param connect Indicates whether the priceLayer should be connected to the user on update.
   * @returns {Promise<string>} A promise that resolves to the ID as a string when the priceLayer is updated.
   */
  update: (priceLayer: PriceLayer) => Promise<string>

  /**
    * Searches for priceLayers in the external source.
    * @param query The query to be used for searching.
    * @returns {Promise<void>} A promise that resolves with an array of priceLayers.
    */
  search: (query: string, pagination: Pagination, force?: boolean) => Promise<PriceLayer[]>
}
