package tag_localisation_operations

import (
	tag_localisation "github.com/bakeable/bkry/internal/server/models/entities/tag_localisation"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Save(repository repo.IRepository, tagID string, entity tag_localisation.TagLocalisation, editorID *string) *string {
	// Preprocess TagLocalisation
	entity = beforeSave(tagID, entity, editorID)

	// Save TagLocalisation
	id, err := repository.SaveTagLocalisation(tagID, entity, editorID)
	if err != nil {
		panic(err)
	}

	// Set ID on entity
	entity.ID = id

	// Take care of business logic after saving TagLocalisation entity
	afterSave(tagID, entity, editorID)

	// Return TagLocalisation
	return &id
}