package question_bundle_operations

import (
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Delete(repository repo.IRepository, questionBundleID string) {
	// Perform before delete actions for QuestionBundle entity
	beforeDelete(questionBundleID)

	// Delete QuestionBundle
	err := repository.DeleteQuestionBundle(questionBundleID)
	if err != nil {
		panic(err)
	}

	// Perform after delete actions for QuestionBundle entity
	afterDelete(questionBundleID)
}