package question_bundle_operations

import (
	question_bundle "github.com/bakeable/bkry/internal/server/models/entities/question_bundle"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
	"github.com/bakeable/bkry/internal/server/database"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAllPaginated(repository repo.IRepository, pagination database.Pagination) ([]question_bundle.QuestionBundle, database.Pagination) {
	// Get QuestionBundles
	entities, pagination, err := repository.GetAllQuestionBundlesPaginated(pagination)
	if err != nil {
		panic(err)
	}

	// Process QuestionBundle entities
	entities = afterGetAllPaginated(entities, pagination.PageSize, pagination.PageNumber, pagination.OrderBy, pagination.Ascending)

	// Return QuestionBundles
	return entities, pagination
}