package question_bundle_operations

import (
	question_bundle "github.com/bakeable/bkry/internal/server/models/entities/question_bundle"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Save(repository repo.IRepository, entity question_bundle.QuestionBundle, editorID *string) *string {
	// Preprocess QuestionBundle
	entity = beforeSave(entity, editorID)

	// Save QuestionBundle
	id, err := repository.SaveQuestionBundle(entity, editorID)
	if err != nil {
		panic(err)
	}

	// Set ID on entity
	entity.ID = id

	// Take care of business logic after saving QuestionBundle entity
	afterSave(entity, editorID)

	// Return QuestionBundle
	return &id
}