package airline_order_grouping_controllers

import (
	"net/http"
	airline_order_grouping_operations "github.com/bakeable/bkry/internal/server/transport/operations/airline_order_grouping"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func Delete(c *gin.Context) {

	// Get airline_order_grouping ID from URL
	airlineOrderGroupingID := c.Param("airlineOrderGroupingID")

	// Delete AirlineOrderGrouping
	airline_order_grouping_operations.Delete(getRepository(), airlineOrderGroupingID)

	// Send response
	c.Status(http.StatusNoContent)

}

