package api_key_operations

import (
	api_key "github.com/bakeable/bkry/internal/server/models/entities/api_key"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAll(repository repo.IRepository, ) []api_key.ApiKey {
	// Get ApiKeys
	entities, err := repository.GetAllApiKeys()
	if err != nil {
		panic(err)
	}

	// Process ApiKey entities
	entities = afterGetAll(entities)

	// Return ApiKeys
	return entities
}