import { defineStore } from 'pinia'
import { ProductPackage } from './interface.gen'
import type { ProductPackageStore, ProductPackageStoreState } from './store.gen.d'
import { Pagination, paginationAndQueriesToCacheKey } from "../../general/pagination";
import { Query } from "../../general/query";
import { ProductPackageTransporter } from './transport.gen'

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

export const useProductPackageStore = defineStore('productPackageStore', {
  state: (): ProductPackageStoreState => ({
    activeID: null,
    cache: {},
    list: [] as ProductPackage[],
    retrievalTimestamp: 0,
    updateKey: 0,
    storeUpdateTimeout: null,
  }),
  actions: {
    emitFormUpdateEvent(id: string): void {
      window.dispatchEvent(new CustomEvent("form.update.product_package", { detail: { id } }));
    },
    emitStoreUpdateEvent(): void {
      // Clear existing timeout
      if (this.storeUpdateTimeout !== null) {
        clearTimeout(this.storeUpdateTimeout)
      }

      // Set new timeout
      this.storeUpdateTimeout = setTimeout(() => {
        window.dispatchEvent(new CustomEvent("store.update.product_package"));
        this.storeUpdateTimeout = null
      }, 1500)
    },
    async activate(productPackage: ProductPackage): Promise<void> {
      // Set active
      this.activeID = productPackage.id
    },
    add(productPackage: ProductPackage): void {
      const id = productPackage.id
      if (typeof id === 'string' && !this.contains(id)) {
        this.list.push(productPackage)

        // Set active
        if (this.active === null) {
          this.activeID = productPackage.id
        }
      } else {
        this.reinsert(productPackage)
      }
      this.updateKey += 1;
    },
    async delete(productPackage: ProductPackage): Promise<void> {
      await ProductPackageTransporter.Delete(productPackage).then(() => {
        this.remove(productPackage)
      }).finally(() => {
        this.emitStoreUpdateEvent()
      });
    },
    async deleteById(id: string): Promise<void> {
      const productPackage = (this.list as ProductPackage[]).find((x: ProductPackage) => x.id === id)
      if (productPackage !== undefined) {
        await this.delete(productPackage)
      } else {
        throw new Error('Could not find ProductPackage with id: ' + id)
      }
    },
    contains(id: string): boolean {
      return (this.list as ProductPackage[]).some((x: ProductPackage) => x.id === id)
    },
    async create(productPackage: ProductPackage): Promise<ProductPackage> {
      // Create productPackage
      const item = await ProductPackageTransporter.Create({
      }, productPackage)

      // Reinsert productPackage
      this.reinsert(item)

      // Activate productPackage
      if (this.active === null) {
        await this.activate(item)
      }
      
      this.emitStoreUpdateEvent()

      return item
    },
    get(id: string): ProductPackage | null {
      return (this.list as ProductPackage[]).find((x: ProductPackage) => x.id === id) || null
    },
    reinsert(productPackage: ProductPackage): void {
      const index = (this.list as ProductPackage[]).findIndex((x: ProductPackage) => x.id === productPackage.id)
      if (index !== -1) {
        this.list = [
          ...this.list.slice(0, index),
          productPackage,
          ...this.list.slice(index + 1),
        ]
      } else {
        this.add(productPackage)
      }
      this.updateKey += 1;
    },
    remove({ id }: ProductPackage): void {
      const index = (this.list as ProductPackage[]).findIndex((x: ProductPackage) => x.id === id)
      if (index !== -1) {
        this.list = [
          ...this.list.slice(0, index),
          ...this.list.slice(index + 1),
        ]
      }
      this.updateKey += 1;
    },
    async retrieve(id: string, force = false): Promise<ProductPackage> {
      // Check if a refresh is required
      if (!force && !this.refreshRequired) {
        const productPackage = this.get(id)
        if (productPackage !== null) {
          return productPackage
        }
      }

      // Get productPackage
      const productPackage = await ProductPackageTransporter.Get({
        id,
      }).then(async (entity) => {
        this.reinsert(entity)

        // Activate productPackage
        await this.activate(entity)

        return entity
      })

      return productPackage
    },
    async retrieveAll(force = false): Promise<{
      active: string | null
      items: ProductPackage[]
    }> {
      // Check if a refresh is required
      if (!force && !this.refreshRequired) {
        return {
          active: this.activeID,
          items: this.list as ProductPackage[],
        }
      }

      // Clear list
      while (this.list.length > 0) {
        this.list.pop()
      }

      // Retrieve list
      await ProductPackageTransporter.GetAll({
      }).then(async (list) => {
        list.forEach((productPackage) => {
          this.reinsert(productPackage)
        })

        // Activate productPackage
        if (list.length > 0) {
          if (this.activeID === null) {
            await this.activate(list[0])
          }
        }
      })

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now()

      return {
        active: this.activeID,
        items: this.list as ProductPackage[],
      }
    },
    async retrievePaginated(pagination: Pagination, force = false): Promise<{
      pagination: Pagination;
      items: ProductPackage[];
    }> {
      // Check pagination
      let newPagination = new Pagination(pagination).deepCopy();

      // Get cachekey
      const cacheKey = pagination.toCacheKey();

      // Check if a refresh is required
      if (!force && this.cache[cacheKey]) {
        const cached = this.cache[cacheKey]
        return {
          pagination: cached.pagination.deepCopy(),
          items: cached.ids.map((id: string) => this.get(id) as ProductPackage),
        };
      }

      // Retrieve list
      const items = await ProductPackageTransporter.GetPaginated(pagination).then(async ({items, pagination }) => {
        items.forEach((productPackage) => {
          this.reinsert(productPackage);
        });

        // Set new pagination
        newPagination = pagination.deepCopy();

        return items;
      });

      // Set cache
      this.cache[cacheKey] = {
        ids: items.map((x: ProductPackage) => x.id),
        pagination: newPagination,
        retrievalTimestamp: Date.now(),
      };

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now();

      return {
        pagination: newPagination,
        items,
      };
    },
    async query(pagination: Pagination, queries: Query[], force = false): Promise<{
      pagination: Pagination;
      items: ProductPackage[];
    }> {
      // Check pagination
      let newPagination = new Pagination(pagination).deepCopy();

      // Get cachekey
      const cacheKey = paginationAndQueriesToCacheKey(pagination, queries);

      // Check if a refresh is required
      if (!force && this.cache[cacheKey]) {
        const cached = this.cache[cacheKey]
        return {
          pagination: cached.pagination.deepCopy(),
          items: cached.ids.map((id: string) => this.get(id) as ProductPackage),
        };
      }

      // Retrieve list
      const items = await ProductPackageTransporter.Query(
        pagination,
        queries,
      ).then(async ({ items, pagination }) => {
        items.forEach((productPackage) => {
          this.reinsert(productPackage);
        });

        // Set new pagination
        newPagination = pagination.deepCopy();;

        return items
      });

      // Set cache
      this.cache[cacheKey] = {
        ids: items.map((x: ProductPackage) => x.id),
        pagination: newPagination.deepCopy(),
        retrievalTimestamp: Date.now(),
      };

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now();

      return {
        pagination: newPagination,
        items: items,
      };
    },
    async search(
      
      pagination: Pagination,
      search: string,
      force = false,
    ): Promise<{
      pagination: Pagination;
      items: ProductPackage[];
    }> {
      // Check pagination
      let newPagination = new Pagination(pagination).deepCopy();

      // Get cachekey
      const cacheKey = search.replaceAll(" ", "_") + '-' + pagination.toCacheKey();

      // Check if a refresh is required
      if (!force && this.cache[cacheKey]) {
        const cached = this.cache[cacheKey]
        return {
          items: cached.ids.map(
            (id: string) => this.get(id) as ProductPackage,
          ),
          pagination: cached.pagination.deepCopy(),
        };
      }

      // Retrieve list
      const items = await ProductPackageTransporter.Search(
        pagination,
        search,
      ).then(async ({ items, pagination }) => {
        items.forEach((productPackage) => {
          this.reinsert(productPackage);
        });

        // Set new pagination
        newPagination = pagination.deepCopy();;

        return items
      });

      // Set cache
      this.cache[cacheKey] = {
        ids: items.map((x: ProductPackage) => x.id),
        pagination: newPagination.deepCopy(),
        retrievalTimestamp: Date.now(),
      };

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now();

      return {
        items: items,
        pagination: newPagination,
      };
    },
    async update(productPackage: ProductPackage): Promise<ProductPackage> {
      // Update productPackage
      const item = await ProductPackageTransporter.Update(productPackage)

      // Reinsert productPackage
      this.reinsert(item)

      // Activate productPackage
      if (this.active === null) {
        await this.activate(item)
      }
      
      this.emitStoreUpdateEvent()

      return item
    },
  },
  getters: {
    active(): ProductPackage | null {
      if (this.activeID === null) {
        return null
      }

      const productPackage = (this.list as ProductPackage[]).find((x: ProductPackage) => x.id === this.activeID)
      if (productPackage === undefined) {
        return null
      }

      return productPackage
    },
    refreshRequired(): boolean {
      return (
        this.retrievalTimestamp === 0 ||
        this.retrievalTimestamp < Date.now() - 30 * 60000 ||
        this.list.length === 0
      )
    },
  },
})

// Export a function to create a new instance of the store
export function createProductPackageStore(): ProductPackageStore {
  const store = useProductPackageStore()
  // Run the initializeStore action when the store is created
  store.initializeStore()
  return store as unknown as ProductPackageStore // TODO: Fix this
}
