import { defineStore } from 'pinia'
import { QuestionContextLocalisation } from './interface.gen'
import type { QuestionContextLocalisationStore, QuestionContextLocalisationStoreState } from './store.gen.d'
import { Pagination, paginationAndQueriesToCacheKey } from "../../general/pagination";
import { Query } from "../../general/query";
import { QuestionContextLocalisationTransporter } from './transport.gen'

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

export const useQuestionContextLocalisationStore = defineStore('questionContextLocalisationStore', {
  state: (): QuestionContextLocalisationStoreState => ({
    activeID: null,
    cache: {},
    list: [] as QuestionContextLocalisation[],
    retrievalTimestamp: 0,
    updateKey: 0,
    storeUpdateTimeout: null,
  }),
  actions: {
    emitFormUpdateEvent(id: string): void {
      window.dispatchEvent(new CustomEvent("form.update.question_context_localisation", { detail: { id } }));
    },
    emitStoreUpdateEvent(): void {
      // Clear existing timeout
      if (this.storeUpdateTimeout !== null) {
        clearTimeout(this.storeUpdateTimeout)
      }

      // Set new timeout
      this.storeUpdateTimeout = setTimeout(() => {
        window.dispatchEvent(new CustomEvent("store.update.question_context_localisation"));
        this.storeUpdateTimeout = null
      }, 1500)
    },
    async activate(questionContextLocalisation: QuestionContextLocalisation): Promise<void> {
      // Set active
      this.activeID = questionContextLocalisation.id
    },
    add(questionContextLocalisation: QuestionContextLocalisation): void {
      const id = questionContextLocalisation.id
      if (typeof id === 'string' && !this.contains(id)) {
        this.list.push(questionContextLocalisation)

        // Set active
        if (this.active === null) {
          this.activeID = questionContextLocalisation.id
        }
      } else {
        this.reinsert(questionContextLocalisation)
      }
      this.updateKey += 1;
    },
    async delete(questionContextLocalisation: QuestionContextLocalisation): Promise<void> {
      await QuestionContextLocalisationTransporter.Delete(questionContextLocalisation).then(() => {
        this.remove(questionContextLocalisation)
      }).finally(() => {
        this.emitStoreUpdateEvent()
      });
    },
    async deleteById(id: string): Promise<void> {
      const questionContextLocalisation = (this.list as QuestionContextLocalisation[]).find((x: QuestionContextLocalisation) => x.id === id)
      if (questionContextLocalisation !== undefined) {
        await this.delete(questionContextLocalisation)
      } else {
        throw new Error('Could not find QuestionContextLocalisation with id: ' + id)
      }
    },
    contains(id: string): boolean {
      return (this.list as QuestionContextLocalisation[]).some((x: QuestionContextLocalisation) => x.id === id)
    },
    async create(questionContextId: string, questionContextLocalisation: QuestionContextLocalisation): Promise<QuestionContextLocalisation> {
      // Create questionContextLocalisation
      const item = await QuestionContextLocalisationTransporter.Create({
        questionContext_id: questionContextId,
      }, questionContextLocalisation)

      // Reinsert questionContextLocalisation
      this.reinsert(item)

      // Activate questionContextLocalisation
      if (this.active === null) {
        await this.activate(item)
      }
      
      this.emitStoreUpdateEvent()

      return item
    },
    get(id: string): QuestionContextLocalisation | null {
      return (this.list as QuestionContextLocalisation[]).find((x: QuestionContextLocalisation) => x.id === id) || null
    },
    reinsert(questionContextLocalisation: QuestionContextLocalisation): void {
      const index = (this.list as QuestionContextLocalisation[]).findIndex((x: QuestionContextLocalisation) => x.id === questionContextLocalisation.id)
      if (index !== -1) {
        this.list = [
          ...this.list.slice(0, index),
          questionContextLocalisation,
          ...this.list.slice(index + 1),
        ]
      } else {
        this.add(questionContextLocalisation)
      }
      this.updateKey += 1;
    },
    remove({ id }: QuestionContextLocalisation): void {
      const index = (this.list as QuestionContextLocalisation[]).findIndex((x: QuestionContextLocalisation) => x.id === id)
      if (index !== -1) {
        this.list = [
          ...this.list.slice(0, index),
          ...this.list.slice(index + 1),
        ]
      }
      this.updateKey += 1;
    },
    async retrieve(questionContextId: string, id: string, force = false): Promise<QuestionContextLocalisation> {
      // Check if a refresh is required
      if (!force && !this.refreshRequired) {
        const questionContextLocalisation = this.get(id)
        if (questionContextLocalisation !== null) {
          return questionContextLocalisation
        }
      }

      // Get questionContextLocalisation
      const questionContextLocalisation = await QuestionContextLocalisationTransporter.Get({
        question_context_id: question_contextId,
        id,
      }).then(async (entity) => {
        this.reinsert(entity)

        // Activate questionContextLocalisation
        await this.activate(entity)

        return entity
      })

      return questionContextLocalisation
    },
    async retrieveAll(questionContextId: string, force = false): Promise<{
      active: string | null
      items: QuestionContextLocalisation[]
    }> {
      // Check if a refresh is required
      if (!force && !this.refreshRequired) {
        return {
          active: this.activeID,
          items: this.list as QuestionContextLocalisation[],
        }
      }

      // Clear list
      while (this.list.length > 0) {
        this.list.pop()
      }

      // Retrieve list
      await QuestionContextLocalisationTransporter.GetAll({
        question_context_id: question_contextId,
      }).then(async (list) => {
        list.forEach((questionContextLocalisation) => {
          this.reinsert(questionContextLocalisation)
        })

        // Activate questionContextLocalisation
        if (list.length > 0) {
          if (this.activeID === null) {
            await this.activate(list[0])
          }
        }
      })

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now()

      return {
        active: this.activeID,
        items: this.list as QuestionContextLocalisation[],
      }
    },
    async retrievePaginated(questionContextId: string, pagination: Pagination, force = false): Promise<{
      pagination: Pagination;
      items: QuestionContextLocalisation[];
    }> {
      // Check pagination
      let newPagination = new Pagination(pagination).deepCopy();

      // Get cachekey
      const cacheKey = pagination.toCacheKey();

      // Check if a refresh is required
      if (!force && this.cache[cacheKey]) {
        const cached = this.cache[cacheKey]
        return {
          pagination: cached.pagination.deepCopy(),
          items: cached.ids.map((id: string) => this.get(id) as QuestionContextLocalisation),
        };
      }

      // Retrieve list
      const items = await QuestionContextLocalisationTransporter.GetPaginated({
        question_context_id: question_contextId,
      },pagination).then(async ({items, pagination }) => {
        items.forEach((questionContextLocalisation) => {
          this.reinsert(questionContextLocalisation);
        });

        // Set new pagination
        newPagination = pagination.deepCopy();

        return items;
      });

      // Set cache
      this.cache[cacheKey] = {
        ids: items.map((x: QuestionContextLocalisation) => x.id),
        pagination: newPagination,
        retrievalTimestamp: Date.now(),
      };

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now();

      return {
        pagination: newPagination,
        items,
      };
    },
    async query(questionContextId: string, pagination: Pagination, queries: Query[], force = false): Promise<{
      pagination: Pagination;
      items: QuestionContextLocalisation[];
    }> {
      // Check pagination
      let newPagination = new Pagination(pagination).deepCopy();

      // Get cachekey
      const cacheKey = paginationAndQueriesToCacheKey(pagination, queries);

      // Check if a refresh is required
      if (!force && this.cache[cacheKey]) {
        const cached = this.cache[cacheKey]
        return {
          pagination: cached.pagination.deepCopy(),
          items: cached.ids.map((id: string) => this.get(id) as QuestionContextLocalisation),
        };
      }

      // Retrieve list
      const items = await QuestionContextLocalisationTransporter.Query({
        question_context_id: question_contextId,
      },
        pagination,
        queries,
      ).then(async ({ items, pagination }) => {
        items.forEach((questionContextLocalisation) => {
          this.reinsert(questionContextLocalisation);
        });

        // Set new pagination
        newPagination = pagination.deepCopy();;

        return items
      });

      // Set cache
      this.cache[cacheKey] = {
        ids: items.map((x: QuestionContextLocalisation) => x.id),
        pagination: newPagination.deepCopy(),
        retrievalTimestamp: Date.now(),
      };

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now();

      return {
        pagination: newPagination,
        items: items,
      };
    },
    async search(
      questionContextId: string, 
      pagination: Pagination,
      search: string,
      force = false,
    ): Promise<{
      pagination: Pagination;
      items: QuestionContextLocalisation[];
    }> {
      // Check pagination
      let newPagination = new Pagination(pagination).deepCopy();

      // Get cachekey
      const cacheKey = search.replaceAll(" ", "_") + '-' + pagination.toCacheKey();

      // Check if a refresh is required
      if (!force && this.cache[cacheKey]) {
        const cached = this.cache[cacheKey]
        return {
          items: cached.ids.map(
            (id: string) => this.get(id) as QuestionContextLocalisation,
          ),
          pagination: cached.pagination.deepCopy(),
        };
      }

      // Retrieve list
      const items = await QuestionContextLocalisationTransporter.Search({
        question_context_id: question_contextId,
      },
        pagination,
        search,
      ).then(async ({ items, pagination }) => {
        items.forEach((questionContextLocalisation) => {
          this.reinsert(questionContextLocalisation);
        });

        // Set new pagination
        newPagination = pagination.deepCopy();;

        return items
      });

      // Set cache
      this.cache[cacheKey] = {
        ids: items.map((x: QuestionContextLocalisation) => x.id),
        pagination: newPagination.deepCopy(),
        retrievalTimestamp: Date.now(),
      };

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now();

      return {
        items: items,
        pagination: newPagination,
      };
    },
    async update(questionContextLocalisation: QuestionContextLocalisation): Promise<QuestionContextLocalisation> {
      // Update questionContextLocalisation
      const item = await QuestionContextLocalisationTransporter.Update(questionContextLocalisation)

      // Reinsert questionContextLocalisation
      this.reinsert(item)

      // Activate questionContextLocalisation
      if (this.active === null) {
        await this.activate(item)
      }
      
      this.emitStoreUpdateEvent()

      return item
    },
  },
  getters: {
    active(): QuestionContextLocalisation | null {
      if (this.activeID === null) {
        return null
      }

      const questionContextLocalisation = (this.list as QuestionContextLocalisation[]).find((x: QuestionContextLocalisation) => x.id === this.activeID)
      if (questionContextLocalisation === undefined) {
        return null
      }

      return questionContextLocalisation
    },
    refreshRequired(): boolean {
      return (
        this.retrievalTimestamp === 0 ||
        this.retrievalTimestamp < Date.now() - 30 * 60000 ||
        this.list.length === 0
      )
    },
  },
})

// Export a function to create a new instance of the store
export function createQuestionContextLocalisationStore(): QuestionContextLocalisationStore {
  const store = useQuestionContextLocalisationStore()
  // Run the initializeStore action when the store is created
  store.initializeStore()
  return store as unknown as QuestionContextLocalisationStore // TODO: Fix this
}
