package airline_order_group_operations

import (
	airline_order_group "github.com/bakeable/bkry/data/entities/airline_order_group"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Query(repository repo.IRepository, queries []datastore.Query, pagination datastore.Pagination) []airline_order_group.AirlineOrderGroup {
	// Get AirlineOrderGroups
	entities, err := repository.QueryAirlineOrderGroups(queries, pagination)
	if err != nil {
		panic(err)
	}

	// Process AirlineOrderGroup entities
	entities = afterQuery(entities)

	// Return AirlineOrderGroups
	return entities
}