package airline_pricing_operations

import (
	airline_pricing "github.com/bakeable/bkry/internal/server/models/entities/airline_pricing"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Find(repository repo.IRepository, queries []datastore.Query) airline_pricing.AirlinePricing {
	// Find AirlinePricing
	entity, err := repository.FindAirlinePricing(queries)
	if err != nil {
		panic(err)
	}

	// Process AirlinePricing entity
	entity = afterFind(entity)

	// Return AirlinePricing
	return entity
}