package airline_pricing_operations

import (
	airline_pricing "github.com/bakeable/bkry/internal/server/models/entities/airline_pricing"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAll(repository repo.IRepository, ) []airline_pricing.AirlinePricing {
	// Get AirlinePricings
	entities, err := repository.GetAllAirlinePricings()
	if err != nil {
		panic(err)
	}

	// Process AirlinePricing entities
	entities = afterGetAll(entities)

	// Return AirlinePricings
	return entities
}