package airline_pricing_operations

import (
	airline_pricing "github.com/bakeable/bkry/data/entities/airline_pricing"
	repo "github.com/bakeable/bkry/data/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Save(repository repo.IRepository, entity airline_pricing.AirlinePricing, editorID *string) *string {
	// Preprocess AirlinePricing
	entity = beforeSave(entity, editorID)

	// Save AirlinePricing
	id, err := repository.SaveAirlinePricing(entity, editorID)
	if err != nil {
		panic(err)
	}

	// Set ID on entity
	entity.ID = id

	// Take care of business logic after saving AirlinePricing entity
	afterSave(entity, editorID)

	// Return AirlinePricing
	return &id
}