package airline_settings_operations

import (
	airline_settings "github.com/bakeable/bkry/internal/server/models/entities/airline_settings"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Find(repository repo.IRepository, queries []datastore.Query) airline_settings.AirlineSettings {
	// Find AirlineSettings
	entity, err := repository.FindAirlineSettings(queries)
	if err != nil {
		panic(err)
	}

	// Process AirlineSettings entity
	entity = afterFind(entity)

	// Return AirlineSettings
	return entity
}