package airline_settings_operations

import (
	airline_settings "github.com/bakeable/bkry/data/entities/airline_settings"
	repo "github.com/bakeable/bkry/data/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Get(repository repo.IRepository, airlineSettingsID string) airline_settings.AirlineSettings {
	// Get AirlineSettings
	entity, err := repository.GetAirlineSettings(airlineSettingsID)
	if err != nil {
		panic(err)
	}

	// Process AirlineSettings entity
	entity = afterGet(airlineSettingsID, entity)

	// Return AirlineSettings
	return entity
}