package airline_settings_operations

import (
	airline_settings "github.com/bakeable/bkry/internal/server/models/entities/airline_settings"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Query(repository repo.IRepository, queries []datastore.Query, pagination datastore.Pagination) []airline_settings.AirlineSettings {
	// Get AirlineSettings
	entities, err := repository.QueryAirlineSettings(queries, pagination)
	if err != nil {
		panic(err)
	}

	// Process AirlineSettings entities
	entities = afterQuery(entities)

	// Return AirlineSettings
	return entities
}