import { type QuestionContext } from './interface.gen'
import { type Store } from 'pinia'
import { Pagination } from "../../general/pagination"
import { Query } from "../../general/query"

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Represents the state of the questionContext store.
 */
export interface QuestionContextStoreState {
  /**
   * The currently active questionContext ID
   */
  activeID: string | null

  /**
   * A cache of questionContexts.
   */
  cache: Record<string, {
    ids: string[]
    pagination: Pagination
    retrievalTimestamp: number
  }>

  /**
   * The list of questionContexts.
   */
  list: QuestionContext[]

  /**
   * The retrieval timestamp
   */
  retrievalTimestamp: number

  /**
   * A key that is updated to force the update of the entity.
   */
  updateKey: number

  /**
   * A timeout before emitting a store update event.
   */
  storeUpdateTimeout: window.Timeout | null
}

/**
 * Represents an QuestionContextStore that extends the Store interface.
 */
export interface QuestionContextStore extends QuestionContextStoreState, Store {
  /**
   * The currently active questionContext
   */
  active: QuestionContext | null

  /**
   * Adds an questionContext to the local QuestionContextStore.
   * @param questionContext The questionContext to be added.
   */
  add: (questionContext: QuestionContext) => void

  /**
   * Checks whether the list contains an instance with the provided ID.
   * @param id The id to be searched.
   * @returns {boolean} A boolean indicating whether the list contains the ID.
   */
  contains: (id: string) => boolean

  /**
   * Creates a new questionContext in the external database and updates the store.
   * @param questionContext The questionContext to be created.
   * @returns {Promise<QuestionContext>} A promise that resolves with the created questionContext.
   */
  create: (questionContext: QuestionContext) => Promise<QuestionContext>

  /**
   * Deletes an questionContext from the QuestionContextStore from the external database.
   * @param questionContext The questionContext to be deleted.
   * @returns {Promise<void>} A promise that resolves when the questionContext is deleted.
   */
  delete: (questionContext: QuestionContext) => Promise<void>

  /**
   * Deletes an questionContext by ID from the QuestionContextStore from the external database.
   * @param id The ID to be deleted.
   * @returns {Promise<void>} A promise that resolves when the questionContext is deleted.
   */
  deleteById: (id: string) => Promise<void>

  /**
   * Fire a form update event for the QuestionContext.
   */
  emitFormUpdateEvent: (id: string) => void

  /**
   * Fire a store update event for all QuestionContexts.
   */
  emitStoreUpdateEvent: () => void

  /**
   * Get a QuestionContext from the local QuestionContextStore.
   * @returns { QuestionContext | null } The questionContext.
   */
  get: (id: string) => QuestionContext | null

  /**
   * Queries questionContexts from the external source
   * @param queries The queries to be used for filtering.
   * @param pagination The pagination to be used for the query.
   * @param force Whether to force the query to the external source.
   * @returns {Promise<{ pagination: Pagination; items: QuestionContext[] }>} A promise that resolves with queried questionContexts.
   */
  query: (queries: Query[], pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: QuestionContext[]
  }>

  /**
   * Reinserts an questionContext to the QuestionContextStore list.
   * @param questionContext The questionContext to be reinserted.
   * @returns {void}
   */
  reinsert: (questionContext: QuestionContext) => void

  /**
   * Removes an questionContext from the local QuestionContextStore.
   * @param questionContext The questionContext to be removed.
   * @returns {void}
   */
  remove: ({ id }: QuestionContext) => void

  /**
   * Determines whether a refresh of the store is required
   */
  refreshRequired: boolean

  /**
   * Retrieves a single QuestionContext from either the local QuestionContextStore or external source, if forced or required.
   * @param id The ID of the QuestionContext to retrieve.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<QuestionContext>} A promise that resolves when the questionContext is set as active.
   */
  retrieve: (id: string, force?: boolean) => Promise<QuestionContext>

  /**
   * Retrieves all questionContexts from the QuestionContextStore or external source, depending if a refresh is required.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<{ active: string | null; items: QuestionContext[] }>} A promise that resolves with an array of questionContexts.
   */
  retrieveAll: (force?: boolean) => Promise<{
    active: string | null
    items: QuestionContext[]
  }>

  /**
   * Retrieves questionContexts paginated from the external source.
   * @param pagination The pagination to be used for the query.
   * @param force Whether to force the query to the external source.
   * @returns {Promise<{ pagination: Pagination; items: QuestionContext[] }>} A promise that resolves with paginated questionContexts.
   */
  retrievePaginated: (pagination?: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: QuestionContext[]
  }>

  /**
   * Searches for questionContexts in the external source.
   * @param search The search query string.
   * @param pagination The pagination to be used for the search.
   * @param force Whether to force the search to the external source.
   * @returns {Promise<{ pagination: Pagination; items: QuestionContext[] }>} A promise that resolves with search results.
   */
  search: (search: string, pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: QuestionContext[]
  }>

  /**
   * Update an questionContext from the QuestionContextStore in the external database.
   * @param questionContext The questionContext to be updated.
   * @returns {Promise<QuestionContext>} A promise that resolves with the updated questionContext.
   */
  update: (questionContext: QuestionContext) => Promise<QuestionContext>
}
