package portal_event_operations

import (
	portal_event "github.com/bakeable/bkry/internal/server/models/entities/portal_event"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAllPaginated(repository repo.IRepository, pagination datastore.Pagination) ([]portal_event.PortalEvent, datastore.Pagination) {
	// Get PortalEvents
	entities, pagination, err := repository.GetAllPortalEventsPaginated(pagination)
	if err != nil {
		panic(err)
	}

	// Process PortalEvent entities
	entities = afterGetAllPaginated(entities, pagination.PageSize, pagination.PageNumber, pagination.OrderBy, pagination.Ascending)

	// Return PortalEvents
	return entities, pagination
}