package portal_event_operations

import (
	portal_event "github.com/bakeable/bkry/internal/server/models/entities/portal_event"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAll(repository repo.IRepository, ) []portal_event.PortalEvent {
	// Get PortalEvents
	entities, err := repository.GetAllPortalEvents()
	if err != nil {
		panic(err)
	}

	// Process PortalEvent entities
	entities = afterGetAll(entities)

	// Return PortalEvents
	return entities
}