package portal_event_operations

import (
	portal_event "github.com/bakeable/bkry/data/entities/portal_event"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func QueryGroup(repository repo.IRepository, queries []datastore.Query) []portal_event.PortalEvent {
	// Query PortalEvents group
	entities, err := repository.QueryPortalEventsGroup(queries)
	if err != nil {
		panic(err)
	}

	// Process PortalEvent entities
	entities = afterQueryGroup(entities)

	// Return PortalEvents
	return entities
}