package media_operations

import (
	media "github.com/bakeable/bkry/internal/server/models/entities/media"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
	"github.com/bakeable/bkry/internal/server/database"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAllPaginated(repository repo.IRepository, pagination database.Pagination) ([]media.Media, database.Pagination) {
	// Get Media
	entities, pagination, err := repository.GetAllMediaPaginated(pagination)
	if err != nil {
		panic(err)
	}

	// Process Media entities
	entities = afterGetAllPaginated(entities, pagination.PageSize, pagination.PageNumber, pagination.OrderBy, pagination.Ascending)

	// Return Media
	return entities, pagination
}