package media_operations

import (
	media "github.com/bakeable/bkry/internal/server/models/entities/media"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
	"github.com/bakeable/bkry/internal/server/database"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Query(repository repo.IRepository, queries []database.Query, pagination database.Pagination) []media.Media {
	// Get Media
	entities, err := repository.QueryMedia(queries, pagination)
	if err != nil {
		panic(err)
	}

	// Process Media entities
	entities = afterQuery(entities)

	// Return Media
	return entities
}