import type IDtoList from '../../base_classes/dto_list'
import { type JSONData } from '../../base_classes/dto.d';
import { type Pagination } from '../../base_classes/pagination';
import { type ExaminationSettings } from '.';


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

export interface IExaminationSettingsList extends IDtoList {

    /// ///////////////////////////////////////
    /// //////// PRIVATE VARIABLES ////////////
    /// ///////////////////////////////////////

    /// ///////////////////////////////////////
    /// ///////// PUBLIC VARIABLES ////////////
    /// ///////////////////////////////////////

    /// ///////////////////////////////////////
    /// ////////////// METHODS ////////////////
    /// ///////////////////////////////////////

    /**
     * Build an instance of type ExaminationSettings from a JSON object
     * @param pathVars - The path variables
     * @returns A promise of ExaminationSettings[]
     */
    _buildInstance: (data: JSONData) => ExaminationSettings

    /**
     * Get all ExaminationSettingss
     * @param pathVars - The path variables
     * @returns A promise of ExaminationSettings[]
     */
    getAll: (pathVars?: string | string[] | Record<string, string>) => Promise<ExaminationSettings[]>

    /**
     * Get paginated ExaminationSettingss
     * @param pathVars - The path variables
     * @param pagination - The pagination object
     * @returns A promise of {
     *      items: ExaminationSettings[],
     *      pagination: Pagination,
     *  }
     */
    getPaginated: (pathVars: string | string[], pagination: Pagination) => Promise<{
        items: ExaminationSettings[],
        pagination: Pagination,
    }>

    /**
     * Query ExaminationSettingss
     * @param queries - The filters to query on
     * @returns A promise of ExaminationSettings[]
     */
    query: (queries: Query[], pagination?: Pagination) => Promise<{
        items: ExaminationSettings[],
        pagination: Pagination,
    }>

    /**
     * Search ExaminationSettingss
     * @param query - The search query
     * @returns A promise of ExaminationSettings[]
     */
    search: (query: string, pagination: Pagination) => Promise<{
        items: ExaminationSettings[],
        pagination: Pagination,
    }>
}