package airline_order_operations

import (
	airline_order "github.com/bakeable/bkry/internal/server/models/entities/airline_order"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Query(repository repo.IRepository, queries []datastore.Query, pagination datastore.Pagination) []airline_order.AirlineOrder {
	// Get AirlineOrders
	entities, err := repository.QueryAirlineOrders(queries, pagination)
	if err != nil {
		panic(err)
	}

	// Process AirlineOrder entities
	entities = afterQuery(entities)

	// Return AirlineOrders
	return entities
}