package attribute_controllers

import (
	"net/http"
	attribute_operations "github.com/bakeable/bkry/internal/server/transport/operations/attribute"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func Delete(c *gin.Context) {

	// Get attribute ID from URL
	attributeID := c.Param("attributeID")

	// Delete Attribute
	attribute_operations.Delete(getRepository(), attributeID)

	// Send response
	c.Status(http.StatusNoContent)

}

