package email_operations

import (
	email "github.com/bakeable/bkry/data/entities/email"
	repo "github.com/bakeable/bkry/data/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAll(repository repo.IRepository, ) []email.Email {
	// Get Emails
	entities, err := repository.GetAllEmails()
	if err != nil {
		panic(err)
	}

	// Process Email entities
	entities = afterGetAll(entities)

	// Return Emails
	return entities
}