package email_operations

import (
	email "github.com/bakeable/bkry/internal/server/models/entities/email"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Save(repository repo.IRepository, entity email.Email, editorID *string) *string {
	// Preprocess Email
	entity = beforeSave(entity, editorID)

	// Save Email
	id, err := repository.SaveEmail(entity, editorID)
	if err != nil {
		panic(err)
	}

	// Set ID on entity
	entity.ID = id

	// Take care of business logic after saving Email entity
	afterSave(entity, editorID)

	// Return Email
	return &id
}