package delivery_entry_operations

import (
	delivery_entry "github.com/bakeable/bkry/data/entities/delivery_entry"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func GetAllPaginated(repository repo.IRepository, pagination datastore.Pagination) ([]delivery_entry.DeliveryEntry, datastore.Pagination) {
	// Get DeliveryEntries
	entities, pagination, err := repository.GetAllDeliveryEntriesPaginated(pagination)
	if err != nil {
		panic(err)
	}

	// Process DeliveryEntry entities
	entities = afterGetAllPaginated(entities, pagination.PageSize, pagination.PageNumber, pagination.OrderBy, pagination.Ascending)

	// Return DeliveryEntries
	return entities, pagination
}