package delivery_entry_operations

import (
	delivery_entry "github.com/bakeable/bkry/internal/server/models/entities/delivery_entry"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func QueryGroup(repository repo.IRepository, queries []datastore.Query) []delivery_entry.DeliveryEntry {
	// Query DeliveryEntries group
	entities, err := repository.QueryDeliveryEntriesGroup(queries)
	if err != nil {
		panic(err)
	}

	// Process DeliveryEntry entities
	entities = afterQueryGroup(entities)

	// Return DeliveryEntries
	return entities
}