import { type Category } from './interface.gen'
import { type Store } from 'pinia'
import { Pagination } from "../../general/pagination"
import { Query } from "../../general/query"

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Represents the state of the category store.
 */
export interface CategoryStoreState {
  /**
   * The currently active category ID
   */
  activeID: string | null

  /**
   * A cache of categorys.
   */
  cache: Record<string, {
    ids: string[]
    pagination: Pagination
    retrievalTimestamp: number
  }>

  /**
   * The list of categorys.
   */
  list: Category[]

  /**
   * The retrieval timestamp
   */
  retrievalTimestamp: number

  /**
   * A key that is updated to force the update of the entity.
   */
  updateKey: number

  /**
   * A timeout before emitting a store update event.
   */
  storeUpdateTimeout: window.Timeout | null
}

/**
 * Represents an CategoryStore that extends the Store interface.
 */
export interface CategoryStore extends CategoryStoreState, Store {
  /**
   * The currently active category
   */
  active: Category | null

  /**
   * Adds an category to the local CategoryStore.
   * @param category The category to be added.
   */
  add: (category: Category) => void

  /**
   * Checks whether the list contains an instance with the provided ID.
   * @param id The id to be searched.
   * @returns {boolean} A boolean indicating whether the list contains the ID.
   */
  contains: (id: string) => boolean

  /**
   * Creates a new category in the external database and updates the store.
   * @param category The category to be created.
   * @returns {Promise<Category>} A promise that resolves with the created category.
   */
  create: (category: Category) => Promise<Category>

  /**
   * Deletes an category from the CategoryStore from the external database.
   * @param category The category to be deleted.
   * @returns {Promise<void>} A promise that resolves when the category is deleted.
   */
  delete: (category: Category) => Promise<void>

  /**
   * Deletes an category by ID from the CategoryStore from the external database.
   * @param id The ID to be deleted.
   * @returns {Promise<void>} A promise that resolves when the category is deleted.
   */
  deleteById: (id: string) => Promise<void>

  /**
   * Fire a form update event for the Category.
   */
  emitFormUpdateEvent: (id: string) => void

  /**
   * Fire a store update event for all Categorys.
   */
  emitStoreUpdateEvent: () => void

  /**
   * Get a Category from the local CategoryStore.
   * @returns { Category | null } The category.
   */
  get: (id: string) => Category | null

  /**
   * Queries categorys from the external source
   * @param queries The queries to be used for filtering.
   * @param pagination The pagination to be used for the query.
   * @param force Whether to force the query to the external source.
   * @returns {Promise<{ pagination: Pagination; items: Category[] }>} A promise that resolves with queried categorys.
   */
  query: (queries: Query[], pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: Category[]
  }>

  /**
   * Reinserts an category to the CategoryStore list.
   * @param category The category to be reinserted.
   * @returns {void}
   */
  reinsert: (category: Category) => void

  /**
   * Removes an category from the local CategoryStore.
   * @param category The category to be removed.
   * @returns {void}
   */
  remove: ({ id }: Category) => void

  /**
   * Determines whether a refresh of the store is required
   */
  refreshRequired: boolean

  /**
   * Retrieves a single Category from either the local CategoryStore or external source, if forced or required.
   * @param id The ID of the Category to retrieve.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<Category>} A promise that resolves when the category is set as active.
   */
  retrieve: (id: string, force?: boolean) => Promise<Category>

  /**
   * Retrieves all categorys from the CategoryStore or external source, depending if a refresh is required.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<{ active: string | null; items: Category[] }>} A promise that resolves with an array of categorys.
   */
  retrieveAll: (force?: boolean) => Promise<{
    active: string | null
    items: Category[]
  }>

  /**
   * Retrieves categorys paginated from the external source.
   * @param pagination The pagination to be used for the query.
   * @param force Whether to force the query to the external source.
   * @returns {Promise<{ pagination: Pagination; items: Category[] }>} A promise that resolves with paginated categorys.
   */
  retrievePaginated: (pagination?: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: Category[]
  }>

  /**
   * Searches for categorys in the external source.
   * @param search The search query string.
   * @param pagination The pagination to be used for the search.
   * @param force Whether to force the search to the external source.
   * @returns {Promise<{ pagination: Pagination; items: Category[] }>} A promise that resolves with search results.
   */
  search: (search: string, pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: Category[]
  }>

  /**
   * Update an category from the CategoryStore in the external database.
   * @param category The category to be updated.
   * @returns {Promise<Category>} A promise that resolves with the updated category.
   */
  update: (category: Category) => Promise<Category>
}
