import { defineStore } from 'pinia'
import { GameModusLocalisation } from './interface.gen'
import type { GameModusLocalisationStore, GameModusLocalisationStoreState } from './store.gen.d'
import { Pagination, paginationAndQueriesToCacheKey } from "../../general/pagination";
import { Query } from "../../general/query";
import { GameModusLocalisationTransporter } from './transport.gen'

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

export const useGameModusLocalisationStore = defineStore('gameModusLocalisationStore', {
  state: (): GameModusLocalisationStoreState => ({
    activeID: null,
    cache: {},
    list: [] as GameModusLocalisation[],
    retrievalTimestamp: 0,
    updateKey: 0,
    storeUpdateTimeout: null,
  }),
  actions: {
    emitFormUpdateEvent(id: string): void {
      window.dispatchEvent(new CustomEvent("form.update.game_modus_localisation", { detail: { id } }));
    },
    emitStoreUpdateEvent(): void {
      // Clear existing timeout
      if (this.storeUpdateTimeout !== null) {
        clearTimeout(this.storeUpdateTimeout)
      }

      // Set new timeout
      this.storeUpdateTimeout = setTimeout(() => {
        window.dispatchEvent(new CustomEvent("store.update.game_modus_localisation"));
        this.storeUpdateTimeout = null
      }, 1500)
    },
    async activate(gameModusLocalisation: GameModusLocalisation): Promise<void> {
      // Set active
      this.activeID = gameModusLocalisation.id
    },
    add(gameModusLocalisation: GameModusLocalisation): void {
      const id = gameModusLocalisation.id
      if (typeof id === 'string' && !this.contains(id)) {
        this.list.push(gameModusLocalisation)

        // Set active
        if (this.active === null) {
          this.activeID = gameModusLocalisation.id
        }
      } else {
        this.reinsert(gameModusLocalisation)
      }
      this.updateKey += 1;
    },
    async delete(gameModusLocalisation: GameModusLocalisation): Promise<void> {
      await GameModusLocalisationTransporter.Delete(gameModusLocalisation).then(() => {
        this.remove(gameModusLocalisation)
      }).finally(() => {
        this.emitStoreUpdateEvent()
      });
    },
    async deleteById(id: string): Promise<void> {
      const gameModusLocalisation = (this.list as GameModusLocalisation[]).find((x: GameModusLocalisation) => x.id === id)
      if (gameModusLocalisation !== undefined) {
        await this.delete(gameModusLocalisation)
      } else {
        throw new Error('Could not find GameModusLocalisation with id: ' + id)
      }
    },
    contains(id: string): boolean {
      return (this.list as GameModusLocalisation[]).some((x: GameModusLocalisation) => x.id === id)
    },
    async create(gameModusId: string, gameModusLocalisation: GameModusLocalisation): Promise<GameModusLocalisation> {
      // Create gameModusLocalisation
      const item = await GameModusLocalisationTransporter.Create({
        gameModus_id: gameModusId,
      }, gameModusLocalisation)

      // Reinsert gameModusLocalisation
      this.reinsert(item)

      // Activate gameModusLocalisation
      if (this.active === null) {
        await this.activate(item)
      }
      
      this.emitStoreUpdateEvent()

      return item
    },
    get(id: string): GameModusLocalisation | null {
      return (this.list as GameModusLocalisation[]).find((x: GameModusLocalisation) => x.id === id) || null
    },
    reinsert(gameModusLocalisation: GameModusLocalisation): void {
      const index = (this.list as GameModusLocalisation[]).findIndex((x: GameModusLocalisation) => x.id === gameModusLocalisation.id)
      if (index !== -1) {
        this.list = [
          ...this.list.slice(0, index),
          gameModusLocalisation,
          ...this.list.slice(index + 1),
        ]
      } else {
        this.add(gameModusLocalisation)
      }
      this.updateKey += 1;
    },
    remove({ id }: GameModusLocalisation): void {
      const index = (this.list as GameModusLocalisation[]).findIndex((x: GameModusLocalisation) => x.id === id)
      if (index !== -1) {
        this.list = [
          ...this.list.slice(0, index),
          ...this.list.slice(index + 1),
        ]
      }
      this.updateKey += 1;
    },
    async retrieve(gameModusId: string, id: string, force = false): Promise<GameModusLocalisation> {
      // Check if a refresh is required
      if (!force && !this.refreshRequired) {
        const gameModusLocalisation = this.get(id)
        if (gameModusLocalisation !== null) {
          return gameModusLocalisation
        }
      }

      // Get gameModusLocalisation
      const gameModusLocalisation = await GameModusLocalisationTransporter.Get({
        game_modus_id: game_modusId,
        id,
      }).then(async (entity) => {
        this.reinsert(entity)

        // Activate gameModusLocalisation
        await this.activate(entity)

        return entity
      })

      return gameModusLocalisation
    },
    async retrieveAll(gameModusId: string, force = false): Promise<{
      active: string | null
      items: GameModusLocalisation[]
    }> {
      // Check if a refresh is required
      if (!force && !this.refreshRequired) {
        return {
          active: this.activeID,
          items: this.list as GameModusLocalisation[],
        }
      }

      // Clear list
      while (this.list.length > 0) {
        this.list.pop()
      }

      // Retrieve list
      await GameModusLocalisationTransporter.GetAll({
        game_modus_id: game_modusId,
      }).then(async (list) => {
        list.forEach((gameModusLocalisation) => {
          this.reinsert(gameModusLocalisation)
        })

        // Activate gameModusLocalisation
        if (list.length > 0) {
          if (this.activeID === null) {
            await this.activate(list[0])
          }
        }
      })

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now()

      return {
        active: this.activeID,
        items: this.list as GameModusLocalisation[],
      }
    },
    async retrievePaginated(gameModusId: string, pagination: Pagination, force = false): Promise<{
      pagination: Pagination;
      items: GameModusLocalisation[];
    }> {
      // Check pagination
      let newPagination = new Pagination(pagination).deepCopy();

      // Get cachekey
      const cacheKey = pagination.toCacheKey();

      // Check if a refresh is required
      if (!force && this.cache[cacheKey]) {
        const cached = this.cache[cacheKey]
        return {
          pagination: cached.pagination.deepCopy(),
          items: cached.ids.map((id: string) => this.get(id) as GameModusLocalisation),
        };
      }

      // Retrieve list
      const items = await GameModusLocalisationTransporter.GetPaginated({
        game_modus_id: game_modusId,
      },pagination).then(async ({items, pagination }) => {
        items.forEach((gameModusLocalisation) => {
          this.reinsert(gameModusLocalisation);
        });

        // Set new pagination
        newPagination = pagination.deepCopy();

        return items;
      });

      // Set cache
      this.cache[cacheKey] = {
        ids: items.map((x: GameModusLocalisation) => x.id),
        pagination: newPagination,
        retrievalTimestamp: Date.now(),
      };

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now();

      return {
        pagination: newPagination,
        items,
      };
    },
    async query(gameModusId: string, pagination: Pagination, queries: Query[], force = false): Promise<{
      pagination: Pagination;
      items: GameModusLocalisation[];
    }> {
      // Check pagination
      let newPagination = new Pagination(pagination).deepCopy();

      // Get cachekey
      const cacheKey = paginationAndQueriesToCacheKey(pagination, queries);

      // Check if a refresh is required
      if (!force && this.cache[cacheKey]) {
        const cached = this.cache[cacheKey]
        return {
          pagination: cached.pagination.deepCopy(),
          items: cached.ids.map((id: string) => this.get(id) as GameModusLocalisation),
        };
      }

      // Retrieve list
      const items = await GameModusLocalisationTransporter.Query({
        game_modus_id: game_modusId,
      },
        pagination,
        queries,
      ).then(async ({ items, pagination }) => {
        items.forEach((gameModusLocalisation) => {
          this.reinsert(gameModusLocalisation);
        });

        // Set new pagination
        newPagination = pagination.deepCopy();;

        return items
      });

      // Set cache
      this.cache[cacheKey] = {
        ids: items.map((x: GameModusLocalisation) => x.id),
        pagination: newPagination.deepCopy(),
        retrievalTimestamp: Date.now(),
      };

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now();

      return {
        pagination: newPagination,
        items: items,
      };
    },
    async search(
      gameModusId: string, 
      pagination: Pagination,
      search: string,
      force = false,
    ): Promise<{
      pagination: Pagination;
      items: GameModusLocalisation[];
    }> {
      // Check pagination
      let newPagination = new Pagination(pagination).deepCopy();

      // Get cachekey
      const cacheKey = search.replaceAll(" ", "_") + '-' + pagination.toCacheKey();

      // Check if a refresh is required
      if (!force && this.cache[cacheKey]) {
        const cached = this.cache[cacheKey]
        return {
          items: cached.ids.map(
            (id: string) => this.get(id) as GameModusLocalisation,
          ),
          pagination: cached.pagination.deepCopy(),
        };
      }

      // Retrieve list
      const items = await GameModusLocalisationTransporter.Search({
        game_modus_id: game_modusId,
      },
        pagination,
        search,
      ).then(async ({ items, pagination }) => {
        items.forEach((gameModusLocalisation) => {
          this.reinsert(gameModusLocalisation);
        });

        // Set new pagination
        newPagination = pagination.deepCopy();;

        return items
      });

      // Set cache
      this.cache[cacheKey] = {
        ids: items.map((x: GameModusLocalisation) => x.id),
        pagination: newPagination.deepCopy(),
        retrievalTimestamp: Date.now(),
      };

      // Set retrieval timestamp
      this.retrievalTimestamp = Date.now();

      return {
        items: items,
        pagination: newPagination,
      };
    },
    async update(gameModusLocalisation: GameModusLocalisation): Promise<GameModusLocalisation> {
      // Update gameModusLocalisation
      const item = await GameModusLocalisationTransporter.Update(gameModusLocalisation)

      // Reinsert gameModusLocalisation
      this.reinsert(item)

      // Activate gameModusLocalisation
      if (this.active === null) {
        await this.activate(item)
      }
      
      this.emitStoreUpdateEvent()

      return item
    },
  },
  getters: {
    active(): GameModusLocalisation | null {
      if (this.activeID === null) {
        return null
      }

      const gameModusLocalisation = (this.list as GameModusLocalisation[]).find((x: GameModusLocalisation) => x.id === this.activeID)
      if (gameModusLocalisation === undefined) {
        return null
      }

      return gameModusLocalisation
    },
    refreshRequired(): boolean {
      return (
        this.retrievalTimestamp === 0 ||
        this.retrievalTimestamp < Date.now() - 30 * 60000 ||
        this.list.length === 0
      )
    },
  },
})

// Export a function to create a new instance of the store
export function createGameModusLocalisationStore(): GameModusLocalisationStore {
  const store = useGameModusLocalisationStore()
  // Run the initializeStore action when the store is created
  store.initializeStore()
  return store as unknown as GameModusLocalisationStore // TODO: Fix this
}
