package tag_controllers

import (
	"net/http"
	tag_operations "github.com/bakeable/bkry/internal/server/transport/operations/tag"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func Delete(c *gin.Context) {

	// Get tag ID from URL
	tagID := c.Param("tagID")

	// Delete Tag
	tag_operations.Delete(getRepository(), tagID)

	// Send response
	c.Status(http.StatusNoContent)

}

