package product_operations

import (
	product "github.com/bakeable/bkry/data/entities/product"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Find(repository repo.IRepository, queries []datastore.Query) product.Product {
	// Find Product
	entity, err := repository.FindProduct(queries)
	if err != nil {
		panic(err)
	}

	// Process Product entity
	entity = afterFind(entity)

	// Return Product
	return entity
}