package product_operations

import (
	product "github.com/bakeable/bkry/internal/server/models/entities/product"
	repo "github.com/bakeable/bkry/internal/server/database/repository"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func QueryGroup(repository repo.IRepository, queries []datastore.Query) []product.Product {
	// Query Products group
	entities, err := repository.QueryProductsGroup(queries)
	if err != nil {
		panic(err)
	}

	// Process Product entities
	entities = afterQueryGroup(entities)

	// Return Products
	return entities
}