package product_operations

import (
	product "github.com/bakeable/bkry/data/entities/product"
	repo "github.com/bakeable/bkry/data/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Save(repository repo.IRepository, entity product.Product, editorID *string) *string {
	// Preprocess Product
	entity = beforeSave(entity, editorID)

	// Save Product
	id, err := repository.SaveProduct(entity, editorID)
	if err != nil {
		panic(err)
	}

	// Set ID on entity
	entity.ID = id

	// Take care of business logic after saving Product entity
	afterSave(entity, editorID)

	// Return Product
	return &id
}