package packing_slip_operations

import (
	packing_slip "github.com/bakeable/bkry/data/entities/packing_slip"
	repo "github.com/bakeable/bkry/data/repository/entities"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Save(repository repo.IRepository, entity packing_slip.PackingSlip, editorID *string) *string {
	// Preprocess PackingSlip
	entity = beforeSave(entity, editorID)

	// Save PackingSlip
	id, err := repository.SavePackingSlip(entity, editorID)
	if err != nil {
		panic(err)
	}

	// Set ID on entity
	entity.ID = id

	// Take care of business logic after saving PackingSlip entity
	afterSave(entity, editorID)

	// Return PackingSlip
	return &id
}