package product_package_operations

import (
	product_package "github.com/bakeable/bkry/internal/server/models/entities/product_package"
	repo "github.com/bakeable/bkry/internal/server/database/repository/entities"
	"github.com/bakeable/bkry/internal/server/database"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Find(repository repo.IRepository, queries []database.Query) product_package.ProductPackage {
	// Find ProductPackage
	entity, err := repository.FindProductPackage(queries)
	if err != nil {
		panic(err)
	}

	// Process ProductPackage entity
	entity = afterFind(entity)

	// Return ProductPackage
	return entity
}