import { type PrintingOrder } from './entity'
import { type Store } from 'pinia'


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// IF YOU WANT TO EDIT THIS FILE, REMOVE THE .gen. FROM THE FILENAME. THE FILE WILL THEN BE IGNORED.
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Represents the state of the printingOrder store.
 */
export interface PrintingOrderStoreState {
  /**
   * The currently active printingOrder ID
   */
  activeID: string | null

  /**
   * A cache of printingOrders.
   */
  cache: Record<string, {
    ids: string[]
    pagination: Pagination
    retrievalTimestamp: number
  }>

  /**
   * The list of printingOrders.
   */
  list: PrintingOrder[]

  /**
   * The retrieval timestamp
   */
  retrievalTimestamp: number

  /**
   * A key that is updated to force the update of the entity.
   */
  updateKey: number

  /**
   * A timeout before emitting a store update event.
   */
  storeUpdateTimeout: window.Timeout | null
}

/**
 * Represents an PrintingOrderStore that extends the Store interface.
 */
export interface PrintingOrderStore extends PrintingOrderStoreState, Store {
  /**
   * Fire a form update event for the PrintingOrder.
   */
  emitFormUpdateEvent: (id: string) => void

  /**
   * Fire a store update event for all PrintingOrder.
   */
  emitStoreUpdateEvent: () => void

  /**
   * The currently active printingOrder
   */
  active: PrintingOrder

  /**
   * Adds an printingOrder to the local PrintingOrderStore.
   * @param printingOrder The printingOrder to be added.
   */
  add: (printingOrder: PrintingOrder) => void

  /**
   * Checks whether the list contains an instance with the provided ID.
   * @param id The id to be searched.
   * @returns {boolean} A boolean indicating whether the list contains the ID.
   */
  contains: (id: string) => boolean

  /**
   * Deletes an printingOrder from the PrintingOrderStore from the external database.
   * @param printingOrder The printingOrder to be deleted.
   * @returns {Promise<void>} A promise that resolves when the printingOrder is deleted.
   */
  delete: (printingOrder: PrintingOrder) => Promise<void>

  /**
   * Deletes an printingOrder by ID from the PrintingOrderStore from the external database.
   * @param id The ID to be deleted.
   * @returns {Promise<void>} A promise that resolves when the printingOrder is deleted.
   */
  deleteById: (id: string) => Promise<void>

  /**
   * Get a PrintingOrder from the local PrintingOrderStore.
   * @returns { PrintingOrder | null } The printingOrder.
   */
  get: (id: string) => PrintingOrder | null

  /**
   * Reinserts an printingOrder to the PrintingOrderStore list.
   * @param printingOrder The printingOrder to be reinserted.
   * @returns {void}
   */
  reinsert: (printingOrder: PrintingOrder) => void

  /**
   * Removes an printingOrder from the local PrintingOrderStore.
   * @param printingOrder The printingOrder to be removed.
   * @returns {void}
   */
  remove: (printingOrder: PrintingOrder) => void

  /**
   * Determines whether a refresh of the store is required
   */
  refreshRequired: boolean

  /**
   * Retrieves a single PrintingOrder from either the local PrintingOrderStore or external source, if forced or required.
    * @param id The ID of the PrintingOrder to retrieve.
    * @param force Indicates whether a refresh is forced.
   * @returns {Promise<void>} A promise that resolves when the printingOrder is set as active.
   */
  retrieve: (id: string, force?: boolean) => Promise<PrintingOrder>

  /**
   * Retrieves all printingOrders from the PrintingOrderStore or external source, depending if a refresh is required.
   * @param force Indicates whether a refresh is forced.
   * @returns {Promise<void>} A promise that resolves with an array of printingOrders.
   */
  retrieveAll: (force?: boolean) => Promise<{
    active: string | null
    items: PrintingOrder[]
  }>

  /**
    * Retrieves printingOrders paginated from the external source
    * @param pagination The pagination to be used for the query.
    * @param force Whether to force the query to the external source.
    * @returns {Promise<void>} A promise that resolves with an array of printingOrders.
    */
  retrievePaginated: (pagination?: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: PrintingOrder[]
  }>

  /**
    * Queries printingOrders from the external source
    * @param queries The queries to be used for filtering.
    * @param pagination The pagination to be used for the query.
    * @param force Whether to force the query to the external source.
    * @returns {Promise<void>} A promise that resolves with an array of printingOrders.
    */
  query: (queries: Query[], pagination: Pagination, force?: boolean) => Promise<{
    pagination: Pagination
    items: PrintingOrder[]
  }>

  /**
   * Update an printingOrder from the PrintingOrderStore in the external database.
   * @param printingOrder The printingOrder to be updated.
   * @param connect Indicates whether the printingOrder should be connected to the user on update.
   * @returns {Promise<string>} A promise that resolves to the ID as a string when the printingOrder is updated.
   */
  update: (printingOrder: PrintingOrder) => Promise<string>

  /**
    * Searches for printingOrders in the external source.
    * @param query The query to be used for searching.
    * @returns {Promise<void>} A promise that resolves with an array of printingOrders.
    */
  search: (query: string, pagination: Pagination, force?: boolean) => Promise<PrintingOrder[]>
}
