import { type JSONData } from '../../base_classes/dto.d'
import type IDto from '../../base_classes/dto.d'

/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////


// Types

// Interfaces

// Data Transfer Object Interface
export interface IAirlineOrderGroupDto extends IDto {
  /// ///////////////////////////////////////
  /// //////// PRIVATE VARIABLES ////////////
  /// ///////////////////////////////////////
  /**
   * The path to the corresponding API endpoint with variables marked as {?}
   */
  _path: string

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////

    // The AFAS order numbers of the airline orders in the group
    afasOrderNumbers: string[]

    // The kind of the object
    _kind: string

    // The name of the airline order group
    name: string

    // The list of airline orders within the group
    orders: airline_order.AirlineOrder[]

    // The pricing tables
    pricingTables: airline_pricing.AirlinePricing[]

    // The airline settings
    settings: airline_settings.AirlineSettings

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////

  /**
   * Set the AirlineOrderGroup's properties
   */
  set: (data: JSONData) => void
}
