import { AirlineSettings } from './entity'
import DtoList from '../../base_classes/dto_list'
import { type JSONData } from '../../base_classes/dto.d'
import { type IAirlineSettingsList } from './list.gen.d'
import { type Pagination, type Query } from '../../base_classes/dto_list.d'


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////


export class AirlineSettingsList 
extends DtoList 
implements IAirlineSettingsList 
{
  /// ///////////////////////////////////////
  /// //////// PRIVATE VARIABLES ////////////
  /// ///////////////////////////////////////
  _path = '/airline_settings'
  _kind = 'AirlineSettings'
  _name = 'airline_settings'

  /// ///////////////////////////////////////
  /// ///////// PUBLIC VARIABLES ////////////
  /// ///////////////////////////////////////
  list: AirlineSettings[] = []
  queriedList: AirlineSettings[] = []

  /// ///////////////////////////////////////
  /// ////////////// METHODS ////////////////
  /// ///////////////////////////////////////

  _buildInstance(data: JSONData): AirlineSettings {
    return new AirlineSettings([], data)
  }

  override async getAll(
    pathVars?: string | string[] | Record<string, string>
  ): Promise<AirlineSettings[]> {
    return (await super.getAll(pathVars)) as AirlineSettings[]
  }

  override async getPaginated(
    pathVars: string | string[],
    pagination: Pagination
  ): Promise<{
    items: AirlineSettings[],
    pagination: Pagination,
  }> {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    return (await super.getPaginated(pathVars, pagination)) as {
      items: AirlineSettings[],
      pagination: Pagination,
    }
  }

  override async query(queries: Query[], pagination?: Pagination): Promise<AirlineSettings[]> {
    return (await super.query(queries, pagination)) as AirlineSettings[];
  }

  override async search(query: string, pagination?: Pagination): Promise<AirlineSettings[]> {
    return (await super.search(query, pagination)) as AirlineSettings[];
  }
}
