import type IDtoList from '../../base_classes/dto_list'
import { type JSONData } from '../../base_classes/dto.d';
import { type Pagination } from '../../base_classes/pagination';
import { type PrintingOrderItem } from '.';


/// ///////////////////////////////////////////////////////////////////////////////////////////////////
/// WARNING! THIS FILE IS AUTOMATICALLY GENERATED, ANY CHANGES WILL BE LOST ON NEXT GENERATION
/// ///////////////////////////////////////////////////////////////////////////////////////////////////

export interface IPrintingOrderItemList extends IDtoList {

    /// ///////////////////////////////////////
    /// //////// PRIVATE VARIABLES ////////////
    /// ///////////////////////////////////////

    /// ///////////////////////////////////////
    /// ///////// PUBLIC VARIABLES ////////////
    /// ///////////////////////////////////////

    /// ///////////////////////////////////////
    /// ////////////// METHODS ////////////////
    /// ///////////////////////////////////////

    /**
     * Build an instance of type PrintingOrderItem from a JSON object
     * @param pathVars - The path variables
     * @returns A promise of PrintingOrderItem[]
     */
    _buildInstance: (data: JSONData) => PrintingOrderItem

    /**
     * Get all PrintingOrderItems
     * @param pathVars - The path variables
     * @returns A promise of PrintingOrderItem[]
     */
    getAll: (pathVars?: string | string[] | Record<string, string>) => Promise<PrintingOrderItem[]>

    /**
     * Get paginated PrintingOrderItems
     * @param pathVars - The path variables
     * @param pagination - The pagination object
     * @returns A promise of {
     *      items: PrintingOrderItem[],
     *      pagination: Pagination,
     *  }
     */
    getPaginated: (pathVars: string | string[], pagination: Pagination) => Promise<{
        items: PrintingOrderItem[],
        pagination: Pagination,
    }>

    /**
     * Query PrintingOrderItems
     * @param queries - The filters to query on
     * @returns A promise of PrintingOrderItem[]
     */
    query: (queries: Query[], pagination?: Pagination) => Promise<{
        items: PrintingOrderItem[],
        pagination: Pagination,
    }>

    /**
     * Search PrintingOrderItems
     * @param query - The search query
     * @returns A promise of PrintingOrderItem[]
     */
    search: (query: string, pagination: Pagination) => Promise<{
        items: PrintingOrderItem[],
        pagination: Pagination,
    }>
}