package generator

var structImports = map[string]string{
	"auditinfo.AuditInfo": "github.com/bakeable/bkry/data/general/auditinfo",
	"docref.DocRef": "github.com/bakeable/bkry/data/general/docref",
	"media.Media": "github.com/bakeable/bkry/data/entities/media",
	"dimension.Dimension": "github.com/bakeable/bkry/data/general/dimension",
	"airline_order.AirlineOrder": "github.com/bakeable/bkry/data/entities/airline_order",
	"airline_pricing.AirlinePricing": "github.com/bakeable/bkry/data/entities/airline_pricing",
	"airline_settings.AirlineSettings": "github.com/bakeable/bkry/data/entities/airline_settings",
	"airline_order_group.AirlineOrderGroup": "github.com/bakeable/bkry/data/entities/airline_order_group",
	"examination_task.ExaminationTask": "github.com/bakeable/bkry/data/entities/examination_task",
	"price_layer.PriceLayer": "github.com/bakeable/bkry/data/entities/price_layer",
	"product.Product": "github.com/bakeable/bkry/data/entities/product",
	"margin.Margin": "github.com/bakeable/bkry/data/general/margin",
	"attribute_option.AttributeOption": "github.com/bakeable/bkry/data/entities/attribute_option",
	"attribute_option_set.AttributeOptionSet": "github.com/bakeable/bkry/data/entities/attribute_option_set",
}
var typeScriptImports = map[string]string{
	"auditinfo.AuditInfo": "import { AuditInfo } from '../../general/audit_info'",
	"docref.DocRef": "import { DocRef } from '../../general/doc_ref'",
	"media.Media": "import { Media } from '../media'",
	"airline_order.AirlineOrder": "import { AirlineOrder } from '../airline_order'",
	"airline_pricing.AirlinePricing": "import { AirlinePricing } from '../airline_pricing'",
	"airline_settings.AirlineSettings": "import { AirlineSettings } from '../airline_settings'",
	"airline_order_group.AirlineOrderGroup": "import { AirlineOrderGroup } from '../airline_order_group'",
	"examination_task.ExaminationTask": "import { ExaminationTask } from '../examination_task'",
	"price_layer.PriceLayer": "import { PriceLayer } from '../price_layer'",
	"product.Product": "import { Product } from '../product'",
	"dimension.Dimension": "import { Dimension } from '../../general/dimension'",
	"margin.Margin": "import { Margin } from '../../general/margin'",
	"attribute_option.AttributeOption": "import { AttributeOption } from '../attribute_option'",
	"attribute_option_set.AttributeOptionSet": "import { AttributeOptionSet } from '../attribute_option_set'",
}
var typeScriptTypeImports = map[string]string{
	"auditinfo.AuditInfo": "import { type AuditInfo } from '../../general/audit_info'",
	"docref.DocRef": "import { type DocRef } from '../../general/doc_ref'",
	"media.Media": "import { type Media } from '../media'",
	"airline_order.AirlineOrder": "import { type AirlineOrder } from '../airline_order'",
	"airline_pricing.AirlinePricing": "import { type AirlinePricing } from '../airline_pricing'",
	"airline_settings.AirlineSettings": "import { type AirlineSettings } from '../airline_settings'",
	"airline_order_group.AirlineOrderGroup": "import { type AirlineOrderGroup } from '../airline_order_group'",
	"examination_task.ExaminationTask": "import { type ExaminationTask } from '../examination_task'",
	"price_layer.PriceLayer": "import { type PriceLayer } from '../price_layer'",
	"product.Product": "import { type Product } from '../product'",
	"dimension.Dimension": "import { type Dimension } from '../../general/dimension'",
	"margin.Margin": "import { type Margin } from '../../general/margin'",
	"attribute_option.AttributeOption": "import { type AttributeOption } from '../attribute_option'",
	"attribute_option_set.AttributeOptionSet": "import { type AttributeOptionSet } from '../attribute_option_set'",
}

var fieldTypeDecoders = map[string]string{
	"[]auditinfo.AuditInfo": "auditinfo.DecodeAll",
	"auditinfo.AuditInfo": "auditinfo.Decode",
	"[]docref.DocRef": "docref.DecodeAll",
	"docref.DocRef": "docref.Decode",
	"[]media.Media": "media.DecodeAll",
	"media.Media": "media.Decode",
	"time.Time": "utils.DecodeTime",
	"[]time.Time": "utils.DecodeTimeArray",
	"airline_order.AirlineOrder": "airline_order.Decode",
	"airline_pricing.AirlinePricing": "airline_pricing.Decode",
	"airline_order_group.AirlineOrderGroup": "airline_order_group.Decode",
	"airline_settings.AirlineSettings": "airline_settings.Decode",
	"examination_task.ExaminationTask": "examination_task.Decode",
	"attribute_option.AttributeOption": "attribute_option.Decode",
	"price_layer.PriceLayer": "price_layer.Decode",
	"product.Product": "product.Decode",
	"dimension.Dimension": "dimension.Decode",
	"margin.Margin": "margin.Decode",
	"string": "utils.DecodeString",
	"int": "utils.DecodeInt",
	"int8": "utils.DecodeInt8",
	"int32": "utils.DecodeInt32",
	"int64": "utils.DecodeInt64",
	"float32": "utils.DecodeFloat32",
	"float64": "utils.DecodeFloat64",
	"bool": "utils.DecodeBool",
	"[]string": "utils.DecodeStringArray",
	"[]int": "utils.DecodeIntArray",
	"[][]int": "utils.DecodeIntArrayArray",
	"[]int8": "utils.DecodeInt8Array",
	"[]int32": "utils.DecodeInt32Array",
	"[]int64": "utils.DecodeInt64Array",
	"[]float64": "utils.DecodeFloatArray",
	"[]bool": "utils.DecodeBoolArray",
	"[]interface{}": "utils.DecodeInterfaceArray",
	"[]map[string]interface{}": "utils.DecodeMapArray",
	"interface{}": "utils.DecodeInterface",
	"map[string]interface{}": "utils.DecodeMap",
	"map[string]int": "utils.DecodeIntMap",
	"map[string]float64": "utils.DecodeFloatMap",
	"map[string]bool": "utils.DecodeBoolMap",
	"map[string]string": "utils.DecodeStringMap",
	"map[int]int": "utils.DecodeIntIntMap",
	"attribute_option_set.AttributeOptionSet": "attribute_option_set.Decode",
}
var emptyDefaultValueMap = map[string]string{
	"string": "\"\"",
	"int": "0",
	"int8": "0",
	"int32": "0",
	"int64": "0",
	"float64": "0",
	"bool": "false",
	"interface{}": "nil",
	"map[string]interface{}": "nil",
	"map[string]int": "map[string]int{}",
	"map[string]float64": "map[string]float64{}",
	"map[string]bool": "map[string]bool{}",
	"map[string]string": "map[string]string{}",
	"[]map[string]interface{}": "[]map[string]interface{}{}",
	"[]map[string]int": "[]map[string]int{}",
	"[]map[string]float64": "[]map[string]float64{}",
	"[]map[string]bool": "[]map[string]bool{}",
	"[]map[string]string": "[]map[string]string{}",
	"[]string": "[]string{}",
	"[]int": "[]int{}",
	"[]float64": "[]float64{}",
	"[]bool": "[]bool{}",
	"[]interface{}": "[]interface{}{}",
	"[]auditinfo.AuditInfo": "[]auditinfo.AuditInfo{}",
	"[]docref.DocRef": "[]docref.DocRef{}",
	"media.Media": "media.Media{}",
	"[]media.Media": "[]media.Media{}",
	"dimension.Dimension": "dimension.Dimension{}",
	"[]dimension.Dimension": "[]dimension.Dimension{}",
	"airline_order.AirlineOrder": "airline_order.AirlineOrder{}",
	"[]airline_order.AirlineOrder": "[]airline_order.AirlineOrder{}",
	"airline_pricing.AirlinePricing": "airline_pricing.AirlinePricing{}",
	"[]airline_pricing.AirlinePricing": "[]airline_pricing.AirlinePricing{}",
	"airline_order_group.AirlineOrderGroup": "airline_order_group.AirlineOrderGroup{}",
	"[]airline_order_group.AirlineOrderGroup": "[]airline_order_group.AirlineOrderGroup{}",
	"airline_settings.AirlineSettings": "airline_settings.AirlineSettings{}",
	"examination_task.ExaminationTask": "examination_task.ExaminationTask{}",
	"price_layer.PriceLayer": "price_layer.PriceLayer{}",
	"product.Product": "product.Product{}",
	"[]product.Product": "[]product.Product{}",
	"[]price_layer.PriceLayer": "[]price_layer.PriceLayer{}",
	"[]examination_task.ExaminationTask": "[]examination_task.ExaminationTask{}",
	"[]airline_settings.AirlineSettings": "[]airline_settings.AirlineSettings{}",
	"[]attribute_option.AttributeOption": "[]attribute_option.AttributeOption{}",
	"attribute_option.AttributeOption": "attribute_option.AttributeOption{}",
	"attribute_option_set.AttributeOptionSet": "attribute_option_set.AttributeOptionSet{}",
}

var forbiddenDeclarators = []string{
	"package",
	"var",
	"import",
	"const",
	"func",
	"return",
	"break",
	"continue",
	"goto",
	"fallthrough",
	"defer",
	"if",
	"else",
	"switch",
	"case",
	"default",
	"select",
	"for",
	"range",
	"type",
	"struct",
	"interface",
	"chan",
	"map",
}

var goTypesToTypeScriptTypes = map[string]string{
	"auditinfo.AuditInfo": "AuditInfo",
	"docref.DocRef": "DocRef<any>",
	"media.Media": "Media",
	"dimension.Dimension": "Dimension",
	"margin.Margin": "Margin",
    "string":       "string",
    "bool":         "boolean",
    "int":          "number",
    "int8":         "number",
    "int16":        "number",
    "int32":        "number",
    "int64":        "number",
    "uint":         "number",
    "uint8":        "number",
    "uint16":       "number",
    "uint32":       "number",
    "uint64":       "number",
    "uintptr":      "number",
    "float32":      "number",
    "float64":      "number",
    "complex64":    "any",
    "complex128":   "any",
    "byte":         "number",
    "rune":         "string",
    "map[string]string": "Record<string, string>",
    "map[string]interface{}": "Record<string, any>",
	"map[string]int": "Record<string, number>",
	"map[string]float64": "Record<string, number>",
	"map[string]bool": "Record<string, boolean>",
    "[]string":     "string[]",
    "[]bool":       "boolean[]",
    "[]int":        "number[]",
    "[]int8":       "number[]",
    "[]int16":      "number[]",
    "[]int32":      "number[]",
    "[]int64":      "number[]",
    "[]uint":       "number[]",
    "[]uint8":      "number[]",
    "[]uint16":     "number[]",
    "[]uint32":     "number[]",
    "[]uint64":     "number[]",
    "[]uintptr":    "number[]",
    "[]float32":    "number[]",
    "[]float64":    "number[]",
    "[]complex64":  "any[]",
    "[]complex128": "any[]",
    "[]byte":       "number[]",
    "[]rune":       "string[]",
	"[]interface{}": "any[]",
	"[]map[string]interface{}": "Record<string, any>[]",
	"[]auditinfo.AuditInfo": "AuditInfo[]",
	"[]docref.DocRef": "DocRef[]",
	"[]dimension.Dimension": "Dimension[]",
	"airline_order.AirlineOrder": "AirlineOrder",
	"[]airline_order.AirlineOrder": "AirlineOrder[]",
	"airline_pricing.AirlinePricing": "AirlinePricing",
	"[]airline_pricing.AirlinePricing": "AirlinePricing[]",
	"airline_order_group.AirlineOrderGroup": "AirlineOrderGroup",
	"[]airline_order_group.AirlineOrderGroup": "AirlineOrderGroup[]",
	"airline_settings.AirlineSettings": "AirlineSettings",
	"examination_task.ExaminationTask": "ExaminationTask",
	"price_layer.PriceLayer": "PriceLayer",
	"product.Product": "Product",
	"[]product.Product": "Product[]",
	"[]price_layer.PriceLayer": "PriceLayer[]",
	"[]examination_task.ExaminationTask": "ExaminationTask[]",
	"[]airline_settings.AirlineSettings": "AirlineSettings[]",
	"[][]int": "number[][]",
	"map[int]int": "Record<number, number>",
	"attribute_option.AttributeOption": "AttributeOption",
	"[]attribute_option.AttributeOption": "AttributeOption[]",
	"attribute_option_set.AttributeOptionSet": "AttributeOptionSet",
	"[]attribute_option_set.AttributeOptionSet": "AttributeOptionSet[]",
}

var defaultValueClientMap = map[string]string{
	"string": "\"\"",
	"int": "0",
	"int8": "0",
	"int32": "0",
	"int64": "0",
	"float64": "0",
	"bool": "false",
	"interface{}": "nil",
	"map[string]interface{}": "{} satisfies Record<string, any>",
	"map[string]int": "{} satisfies Record<string, number>",
	"map[string]float64": "{} satisfies Record<string, number>",
	"map[string]bool": "{} satisfies Record<string, boolean>",
	"map[string]string": "{} satisfies Record<string, string>",
	"[]string": "[] as string[]",
	"[]int": "[] as number[]",
	"[][]int": "[] as Array<number[]>",
	"[]float64": "[] as number[]",
	"[]bool": "[] as boolean[]",
	"[]interface{}": "[]",
	"[]map[string]interface{}": "[]",
	"[]auditinfo.AuditInfo": "[] as AuditInfo[]",
	"[]docref.DocRef": "[] as DocRef[]",
	"[]media.Media": "[] as Media[]",
	"dimension.Dimension": "{} as Dimension",
	"[]dimension.Dimension": "[] as Dimension[]",
	"[]string{}": "[] as string[]",
	"[]int{}": "[] as number[]",
	"[]float64{}": "[] as number[]",
	"[]bool{}": "[] as boolean[]",
	"[]interface{}{}": "[]",
	"[]map[string]interface{}{}": "[]",
	"airline_order.AirlineOrder": "{} as AirlineOrder",
	"[]airline_order.AirlineOrder": "[] as AirlineOrder[]",
	"airline_pricing.AirlinePricing": "{} as AirlinePricing",
	"[]airline_pricing.AirlinePricing": "[] as AirlinePricing[]",
	"airline_order_group.AirlineOrderGroup": "{} as AirlineOrderGroup",
	"[]airline_order_group.AirlineOrderGroup": "[] as AirlineOrderGroup[]",
	"airline_settings.AirlineSettings": "{} as AirlineSettings",
	"examination_task.ExaminationTask": "{} as ExaminationTask",
	"price_layer.PriceLayer": "new PriceLayer()",
	"product.Product": "new Product()",
	"[]product.Product": "[] as Product[]",
	"[]price_layer.PriceLayer": "[] as PriceLayer[]",
	"attribute_option.AttributeOption": "{} as AttributeOption",
	"[]attribute_option.AttributeOption": "[] as AttributeOption[]",
	"map[string]interface{}{}": "{} satisfies Record<string, any>",
	"attribute_option_set.AttributeOptionSet": "{} as AttributeOptionSet",
	"[]attribute_option_set.AttributeOptionSet": "[] as AttributeOptionSet[]",
}