package printing_order_operations

import (
	printing_order "github.com/bakeable/bkry/data/entities/printing_order"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Find(repository repo.IRepository, queries []datastore.Query) printing_order.PrintingOrder {
	// Find PrintingOrder
	entity, err := repository.FindPrintingOrder(queries)
	if err != nil {
		panic(err)
	}

	// Process PrintingOrder entity
	entity = afterFind(entity)

	// Return PrintingOrder
	return entity
}