package printing_order_operations

import (
	printing_order "github.com/bakeable/bkry/data/entities/printing_order"
	repo "github.com/bakeable/bkry/data/repository/entities"
	"github.com/bakeable/bkry/third_party/gcloud/datastore"	
	
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT

func Query(repository repo.IRepository, queries []datastore.Query, pagination datastore.Pagination) []printing_order.PrintingOrder {
	// Get PrintingOrders
	entities, err := repository.QueryPrintingOrders(queries, pagination)
	if err != nil {
		panic(err)
	}

	// Process PrintingOrder entities
	entities = afterQuery(entities)

	// Return PrintingOrders
	return entities
}