package purchase_controllers

import (
	"net/http"
	purchase_operations "github.com/bakeable/bkry/internal/server/transport/operations/purchase"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func GetAll(c *gin.Context) {

	// Get user ID from URL
	userID := c.Param("userID")

	// Get purchase
	entities := purchase_operations.GetAll(getRepository(), userID)

	// Return purchase
	c.JSON(http.StatusOK, gin.H{ "items": entities})

}