package price_layer_controllers

import (
	"net/http"
	price_layer_operations "github.com/bakeable/bkry/internal/server/transport/operations/price_layer"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func Delete(c *gin.Context) {

	// Get price_layer ID from URL
	priceLayerID := c.Param("priceLayerID")

	// Delete PriceLayer
	price_layer_operations.Delete(getRepository(), priceLayerID)

	// Send response
	c.Status(http.StatusNoContent)

}

