package price_layer_controllers

import (
	"net/http"
	price_layer_operations "github.com/bakeable/bkry/internal/server/transport/operations/price_layer"

	"github.com/gin-gonic/gin"
)

//// THIS FILE IS AUTOGENERATED. DO NOT EDIT
//// IF YOU WISH TO EDIT THIS CONTROLLER, REMOVE THE .gen.go EXTENSION
//// THIS WAY, IT WON'T BE OVERWRITTEN AND THERE WON'T BE A CONTROLLER GENERATED

func Get(c *gin.Context) {

	// Get price_layer ID from URL
	priceLayerID := c.Param("priceLayerID")

	// Get price_layer
	entity := price_layer_operations.Get(getRepository(), priceLayerID)

	// Return price_layer
	c.JSON(http.StatusOK, gin.H{ "item": entity })
}
